### ISSUE TITLE
Add support for configuring mock/proxy behavior via the CLI

### ISSUE THREAD

**Issue by m-roberts** [mockoon/mockoon#1024]
It would be great if it were possible to use a single mock server definition/specification (i.e. JSON file) for various different development patterns.

For example:
* use as defined in file
* override mode to be fully mocking (i.e. disable "proxy mode", keep routes enabled/disabled)
* override mode to be partial mocking (i.e. enable "proxy mode", keep routes enabled/disabled)
* override mode to be no mocking (i.e. enable "proxy mode", disable all routes) - meaning pure passthrough

This means that a simple app config can handle "run as in production", "run in isolation" (failing on undefined tests) and partial mocking (allow for easy addition of missing mocks).

This allows a developer to easily replicate the behaviour of an app in production, run a test suite or develop a new integration/e2e test without ever needing to change the hostname of the server endpoint.

This ability to control its proxy behavior at runtime adds a significant amount of value to using Mockoon as an easy-to-use mock/proxy server for rapid application and test development.

**Comment by aaron-junot** [comment]
@255kb The mockoon docs say that the CLI is supposed to support proxy mode, but I can't find documentation on how to enable it, and nothing in the repo makes it clear how to use proxy mode.

![Screenshot 2024-05-21 at 5 03 10 PM](https://github.com/mockoon/mockoon/assets/2008701/486613c5-3058-4d3f-ba8b-12fb8ba6efd9)

Can you please shed some light on the timeline for adding this feature?

**Comment by 255kb** [comment]
@aaron-junot The CLI is not a standalone app. It is designed to run Mockoon data files created using the desktop app. All the features you can activate in the desktop app are supported by the CLI, this is the case for the [proxy](https://mockoon.com/docs/latest/server-configuration/proxy-mode/).
The CLI has some flags to override various configuration at runtime but not for the proxy yet.

**Comment by aaron-junot** [comment]
@255kb I looked at the docs again, I was using the wrong verbiage. I don't think this issue is actually relevant to what I wanted to do. I wanted to be able to [record requests](https://mockoon.com/docs/latest/logging-and-recording/auto-mocking-and-recording/#record-your-api-calls) via the CLI.

For reference, the use case is that we have mocks, but the third party API that we're mocking has a breaking change and now our mocks must be re-recorded. We want to be able to re-record these in CI and then open a PR with the change to our JSON mocks repo.

Should I open a separate GitHub issue to discuss this?

**Comment by 255kb** [comment]
@aaron-junot yes, I would say it's unrelated to this issue. Enabling disabling recording mode programmaticaly through a CLI flag or through the admin API requires more work and of different kind. Currently, the recording is a feature from the desktop app only. 
I suggest you open a new issue. It's also a topic I'm looking into right now.

**Comment by aaron-junot** [comment]
@255kb FYI I discussed it with my team, and we're going to use the UI for recording for now. Since I don't have a vested interest anymore, I don't intend to open up an issue at this time. Thanks!

**Comment by 255kb** [comment]
📦This was added in [v9.1.0](https://mockoon.com/releases/9.1.0/).
 Wildcard support in `--disable-routes=*` flag and new `--proxy enabled|disabled` flag.
