### ISSUE TITLE
Display Response Status Code in logging list.

### ISSUE THREAD

**Issue by 255kb** [mockoon/mockoon#1031]
### Discussed in https://github.com/mockoon/mockoon/discussions/1030

<div type='discussions-op-text'>

<sup>Originally posted by **endruszeit** May  5, 2023</sup>
Hello, I have a feature request/ idea. 

It would be nice to have an option to display the status code of the server response in the list tile of the logging tab. 

It would be much easier to find failing calls, which may require a mock while developing.

![image](https://user-images.githubusercontent.com/22318955/236392121-5b5fc675-36da-42d8-a61d-48f593f01a98.png)

Sincerely</div>

**Comment by vishwasganatra** [comment]
Hey @255kb , I would like to work on this issue and contribute to the project, if possible can you assign it to me?

**Comment by 255kb** [comment]
Sure. Let me know if you have any question. You can ask here or reach me on our [Discord server](https://discord.com/invite/JmTBk59MTb).
