### ISSUE TITLE
HTML entities in generated responses

### ISSUE THREAD

**Issue by yohny** [mockoon/mockoon#1032]
**Describe the bug**
Currently it can happen that the generated faker data contains HTML entities instead of real characters they represent.

**To Reproduce**
take for example a response template like this:
```json
{
  "Name": "{{faker 'name.lastName'}}"
}
```
currently it might result in response as follows:
```json
{
  "Name": "D&#x27;Amore"
}
```
notice that generated name `D&#x27;Amore` contains HTML entity `&#x27;` (apostrophe), but expected value is  `D'Amore` as its responsibility of the consuming application to properly escape the values if necesary, API should return data in its original form

**Mockoon version:**

1.23.0

**OS / OS version:**

Windows 10

**Comment by yohny** [comment]
ok, just found out that to prevent escaping tripple braces are suppoorted, so this works as expected:
```json
{
  "Name": "{{{faker 'name.lastName'}}}"
}
```
maybe it would be worth to mention this explicitly in Mockoon documentation

**Comment by 255kb** [comment]
You are right I will add a section in the docs templating overview. 
thanks
