### ISSUE TITLE
Allow resizing route column

### ISSUE THREAD

**Issue by DevRyanDonahue** [mockoon/mockoon#104]
**Is your feature request related to a problem? Please describe.**
When the routes in my environment become long, it can become impossible to differentiate which is which based on the routes list. The last of the text is truncated so I have to navigate to each route to see what it is

**Describe the solution you'd like**
Allowing resizing of this column would likely be the best solution. A hover tooltip on route items would be a next best.

**Describe alternatives you've considered**
Truncating at beginning of text or the middle, but they could still hold valuable information that making the column bigger could still display.

**Additional context**

**Comment by axc450** [comment]
I can look into adding this, but it might not make it into the next release

**Comment by sotcha** [comment]
Hi, I have a close to final implementation for this feature. Do you want to get a PR for this ?

**Comment by 255kb** [comment]
Hi @sotcha . All contributions are welcome! 
However, I would like to discuss the implementation with you first. How do you plan to do this? Like a traditional resize (mouse click on the border, hold, move, release click)? As it may leads to lots of repaint, because of column resize, how are the performances? 
Also, On the master branch (upcoming version), I worked on a collapsible environments menu with lots of refactoring. You absolutely **must** start your work from this branch :)

**Comment by sotcha** [comment]
Hi @255kb , yes I forked from the master branch.

Well, I created a directive which works (as you described like the traditional resize) :

- Start when onMouseClick on the directive
- Register _mousemove_ and _mouseup_ listener on the body
- Release on mouse up

The performance seems to be OK, at least on my laptop.

I have a draft commit here : 
https://github.com/sotcha/mockoon/tree/feature/allow-resizing-route-column-%23104

Have a look if you want.

**Comment by 255kb** [comment]
This looks great! Feel free to open the PR. I will try to review it in the coming days/weeks. Anyway, it can make it for the next release. I have still things I am working on and bugs I want to solve for 1.8.0.

**Comment by sotcha** [comment]
Hi @255kb , what do you think about adding the same functionality into the environment logs column.

Something like this 
![image](https://user-images.githubusercontent.com/1183265/76159496-bff0bc80-6129-11ea-9920-02ca6554ab82.png)
 

Also as I can see into the description it is we would like to add a hover tooltip over the url name 

![image](https://user-images.githubusercontent.com/1183265/76159580-e4996400-612a-11ea-9ba0-2927acde0159.png)

Should I add these to this PR?

**Comment by 255kb** [comment]
I would say it's a great idea and I think it was requested already. If you don't mind, I would prefer that you open a new issue and PR so it's easier for me to test and review 🤗
