### ISSUE TITLE
Mockoon GUI app doesn't completely exit when quitting

### ISSUE THREAD

**Issue by mfrancisbeehive** [mockoon/mockoon#1040]
**Describe the bug**

This issue is specific to macOS. 

The Mockoon GUI application doesn't completely quit when exiting. After quitting, the mockoon icon is still shown in the Dock as if it is still running. I have to right-click on the Dock icon and hit quit again.  This happens even though the mockoon server isn't running. This also prevents the computer from shutting down. 

**To Reproduce**

With the Mockoon GUI open, quit using Command-Q or quitting from the utility bar at the top of the screen. The Mockon icon still shows in the Dock as if it is still running although no windows are open. 

If I click on the running Mockoon icon, the app behaves as if it is opening for the first time, showing the splash screen and then the GUI window. 

To quit the application fully, I must right-click on the Mockoon icon in the Dock (after having tried quitting the first time) and click "Quit" again.

This is also reproducible by right-clicking on the mockoon icon and clicking "Quit" twice (starting with the Mockoon GUI window open".

**Mockoon version:**

1.23.0

**OS / OS version:**

macOS Ventura 13.13.1

**Comment by 255kb** [comment]
I think there are two separated questions which are also discussed in #838. 

I am not a mac user so I don't have a strong opinion on this. I initially followed the recommended way of closing an application on MacOS which is what you describe: closing the app close the window but keep the app in the dock. When you click the icon in the dock, the application gets restored. It worked well for years without any questions from the users.
I don't think we should change this behavior as it is the one that is recommended absolutely everywhere ([one example](https://www.electronjs.org/docs/latest/tutorial/tutorial-first-app#open-a-window-if-none-are-open-macos)). 

Still, it seems that there is a bug preventing the computer to shut down. According to #838 it happens only with Apple Silicon hardware. I asked for feedback on #838, and especially for retesting with the latest version 3.0.0. I am currently waiting for answers and I would be glad if you could help with the testing. 
Thank you! 

I will close this issue as a duplicate.
