### ISSUE TITLE
CRUD - replace :id with a different var

### ISSUE THREAD

**Issue by aba-koepke** [mockoon/mockoon#1041]
### Discussed in https://github.com/mockoon/mockoon/discussions/1038

<div type='discussions-op-text'>

<sup>Originally posted by **aba-koepke** May 12, 2023</sup>
Hi there, i like to ask if its possible to use a different var instead of "id" in a databucket to do CRUD-Operations, we normally name unique-Ids "uuid" in our datasets..

Thanks for any Help.</div>

**Comment by n1ce1041** [comment]
I shall work on this

**Comment by 255kb** [comment]
📦 This is now available with [release v4.0.0](https://mockoon.com/releases/4.0.0).
