### ISSUE TITLE
Response Duplication with Complete Component Preservation

### ISSUE THREAD

**Issue by pf-burak-sinan** [mockoon/mockoon#1051]
To test different data states, I produce multiple variations of a response. This can sometimes be as simple as a boolean flag update in a large json file. To accomplish this, I'm currently copying and pasting the response body after making a new response. However, I must copy the headers as well. If I required to copy Rules, Settings, I'd also copied these fields, which is a quite boilerplate procedure. 

I'd appreciated a feature that allows us to duplicate a response with all its components: **Body**, **Headers**, **Rules**, **Settings**. In this manner, we can focus just on the data cases.✌🏻

**Comment by 255kb** [comment]
You can duplicate using this button on the right: 
![image](https://github.com/mockoon/mockoon/assets/7489814/9a5a73e4-9e8e-422e-a292-44a8a0a13f0c)
