### ISSUE TITLE
Support route disabling

### ISSUE THREAD

**Issue by kingvagabond** [mockoon/mockoon#106]
This is a feature request. Instead of deleting a route if I don't want it right now, can we disable it now? And we can enable it any time in the future to save some time in case need it again?

**Comment by axc450** [comment]
I can look into adding this, but it might not make it into the next release

**Comment by javikr** [comment]
This feature will be great! Thanks @axc450 for your work :)

**Comment by XaeroDegreaz** [comment]
+1 This would pair great with enabling proxy mode.

**Comment by gabrielperes97** [comment]
I'm working on it :)
