### ISSUE TITLE
faker methods with numbers in their name not working like ipv4 & ipv6

### ISSUE THREAD

**Issue by ajatkj** [mockoon/mockoon#1078]
**Faker methods with numbers in their name not working like ipv4, ipv6**

use {{faker 'internet.ipv4'}} or {{faker 'internet.ipv6'}}
{{faker 'internet.ip'}} works just fine

v3.1.0

Issue seems to be in mockoon/packages/commons-server/src/libs/templating-helpers/faker-wrapper.ts

Offending code - 
    if (
      !fakerName ||
      !fakerName.match(/^[a-z]+\.[a-z]+$/i) ||
      !fakerPrimaryMethod ||
      !fakerSecondaryMethod ||
      !faker[fakerPrimaryMethod] ||
      !faker[fakerPrimaryMethod][fakerSecondaryMethod]
    ) 
The matching regex should also include a number in secondaryMethod name like - 
    if (
      !fakerName ||
      !fakerName.match(/^[a-z]+\.[a-z0-9]+$/i) ||
      !fakerPrimaryMethod ||
      !fakerSecondaryMethod ||
      !faker[fakerPrimaryMethod] ||
      !faker[fakerPrimaryMethod][fakerSecondaryMethod]
    ) {

Let me know if I can raise a PR for same? or do you want to handle this issue more specifically as only 2 secondary methods ipv4 and ipv6 have numbers in their name.

MacOS Ventura

**Comment by 255kb** [comment]
Nice catch! I never noticed these two methods. 
Feel free to open a PR and I will assign the issue to you.

PS: saw your profile, I love Iron Maiden :)

**Comment by ajatkj** [comment]
Sure, will do!
Always make me happy to meet a fellow Iron Maiden fan :)

**Comment by 255kb** [comment]
📦 This is now available with [release v4.0.0](https://mockoon.com/releases/4.0.0).
