### ISSUE TITLE
stringify is not compatible with Objects

### ISSUE THREAD

**Issue by ARiyou2000** [mockoon/mockoon#1080]
**Describe the bug**

creating an array of objects using [`array templating`](https://mockoon.com/docs/latest/templating/mockoon-helpers/#array) will produce something like this

```
{&quot;publicId&quot;: &quot;{{guid}}&quot;, &quot;title&quot;: &quot;School&quot;},
{&quot;publicId&quot;: &quot;{{guid}}&quot;,&quot;title&quot;: &quot;Shopcenter&quot;},
{&quot;publicId&quot;:&quot;{{guid}}&quot;, &quot;title&quot;: &quot;Highway&quot;},
{&quot;publicId&quot;: &quot;{{guid}}&quot;, &quot;title&quot;: &quot;Home&quot;}
```
 **This is what I intended:**
```json
    {
      "publicId": "{{guid}}",
      "title": "School"
    },
    {
      "publicId": "{{guid}}",
      "title": "Shopcenter"
    },
    {
      "publicId": "{{guid}}",
      "title": "Highway"
    },
    {
      "publicId": "{{guid}}",
      "title": "Home"
    }
```

I have driven more into it and found out the same goes for `stringify`
**To Reproduce**
`{{array '{"publicId":"ce197f7b-34e7-4598-83ec-365156250954","title":"School"}' '{"publicId":"19bf16ad-415d-4bf1-ab15-9d31d0aae676","title":"Shopcenter"}' '{"publicId":"7c2fa1cc-af2a-45e0-b909-85192c1a2b14","title":"Highway"}' '{"publicId":"3a876cda-afbe-48f4-a5a7-39691240b214","title":"Home"}'}}`

or something like this:
```json
{
"type": {{oneOf (array '{"publicId":"ce197f7b-34e7-4598-83ec-365156250954","title":"School"}' '{"publicId":"19bf16ad-415d-4bf1-ab15-9d31d0aae676","title":"Shopcenter"}' '{"publicId":"7c2fa1cc-af2a-45e0-b909-85192c1a2b14","title":"Highway"}' '{"publicId":"3a876cda-afbe-48f4-a5a7-39691240b214","title":"Home"}')}}
}
```

or even:
```json
{
"type": {{stringify '{"publicId":"ce197f7b-34e7-4598-83ec-365156250954","title":"School"}'}}
}
```

**Suggestion:**
Before anything else, provide a templating like `JSON` that will get a strigified object/array and return actual value (not something like [object Object]).
then you can dive more into this issue and solve it in all functionalities as well.

**Mockoon version:**
3.0.1

**OS / OS version:**
Ubuntu 22.04.2 LTS

**Comment by 255kb** [comment]
This is a limitation of Handlebars. 
By doing something like this:
```
{{array '{"publicId":"ce197f7b-34e7-4598-83ec-365156250954","title":"School"}' '{"publicId":"19bf16ad-415d-4bf1-ab15-9d31d0aae676","title":"Shopcenter"}' '{"publicId":"7c2fa1cc-af2a-45e0-b909-85192c1a2b14","title":"Highway"}' '{"publicId":"3a876cda-afbe-48f4-a5a7-39691240b214","title":"Home"}'}}
```
You are in fact passing strings, and creating an array of strings. Handlebars will also escape curly braces, which you can avoid using triple curly braces: `{{{...}}}`

You must store this object(s) somewhere else, like in a data bucket. 
I will close it as not planned.
