### ISSUE TITLE
RFC: Remove PM2 dependency from Mockoon CLI

### ISSUE THREAD

**Issue by martin-bucinskas** [mockoon/mockoon#1081]
Proposing to remove PM2 dependency from Mockoon CLI.

## Why

Considering that most people that do use mockoon cli use the docker functionality and wrap it as a container image,
there seems to be no need to allow virtual horizontal scaling that PM2 offers to run multiple mockoon processes within the "same" NodeJS process, as orchestrators such as kubernetes (other tools also available) already handle the vertical and horizontal scaling of pods or containers. There is little benefit of having a huge dependency on something that would run perfectly without the daemon process management that PM2 offers.

## Context

In the last couple of days, there have been some CVEs raised regarding VM2 affecting all versions reaching the score of 9.8.
- https://security.snyk.io/vuln/SNYK-JS-VM2-5772823
- https://security.snyk.io/vuln/SNYK-JS-VM2-5772825

Unfortunately a dependency that Mockoon CLI uses, also uses the vulnerable VM2 dependency, making any sort of automated vulnerability checking as part of pipelines flag up as a vulnerable component. There is no easy way to mitigate this as of now, since the maintainer of [VM2 has dropped support of the project](https://github.com/patriksimek/vm2/issues/533).

There is an alternative available package called `isolated-vm` which can do the same job as VM2 did but its got issues on its own, but this is for the PM2 maintainers to decide, and there is no clear timelines when PM2 will be updated and resolved. - https://github.com/Unitech/pm2/issues/5639

---

_edit: 14/07/23 - just adding a note that despite mockoon cli using PM2 as a dependency, the PM2 and VM2 functionality is behind a feature flag that is generally disabled when running the cli as a container image - shouldn't need to worry about existing running components!_

**Comment by 255kb** [comment]
📦 This is now available with [release v4.0.0](https://mockoon.com/releases/4.0.0).
