### ISSUE TITLE
Increase width of log entry list

### ISSUE THREAD

**Issue by AlexanderThiele** [mockoon/mockoon#1085]
Hey Mockoon!

I love your tool and use it regularly when developing my App!
Something is always bugging me, whenever i open the Logs-Tab and look at my Log-Overview, it stops expanding until a certain width. We have many calls with the same path and i have to click every log entry 1 by 1 to find my call. 

It is possible to expand it even more so that i can see my call when browsing the Log-List?

That would be awesome!

I'm using the Mac App currently with version 3.1.0

And here a screenshot:

![Screenshot 2023-07-17 at 13 12 18](https://github.com/mockoon/mockoon/assets/4806327/aa6a19a0-3089-48aa-9720-f920acc55082)

Thank you very much!
Best,
Alex

**Comment by 255kb** [comment]
Hi Alex

Currently, the width of this menu is shared with all the similar menus (routes, etc.). It's a % of the application full width. It is limited to avoid right part of the UI to collapse when it's too small. I agree that for the logs it doesn't really make sense. 

Handling the menus size independently would fix this, but there is a quicker fix that we could implement. 

There is a setting to avoid long names/paths truncation: 
![image](https://github.com/mockoon/mockoon/assets/7489814/ba8ccd7b-b5d4-45ae-887c-de03134ee7cc)

The result is that the environment names, route paths, and data bucket names are not truncated anymore. 
![image](https://github.com/mockoon/mockoon/assets/7489814/6d7d0bd1-202e-486e-af87-5edadd26006e)

This is not yet activated for the logs but could solve your problem. 
What do you think?

**Comment by AlexanderThiele** [comment]
Hey @255kb,
thanks for the prompt answer!

Yes, that would probably help, but it might get a little confusing if all the URLs are split into multiple lines. 

But definitely an improvement!

Thank you!

**Comment by 255kb** [comment]
Let's test that for a while, it will be quick to do on my side. After that, feel free to open a new issue if it doesn't solve your issue properly :)

**Comment by 255kb** [comment]
📦 This is now available with [release v4.0.0](https://mockoon.com/releases/4.0.0).

**Comment by AlexanderThiele** [comment]
Looks great! Thanks for the swift update!
