### ISSUE TITLE
The same template randomly generates either valid or not valid jSON

### ISSUE THREAD

**Issue by dmitry-k-fe-bw** [mockoon/mockoon#1088]
**Describe the bug**
My template generate JSON that not valid and not parsed by Browser/Zod

**To Reproduce**
{
  "totalElements": 1000,
  "totalPages": {{subtract 1000 (queryParam 'size' '10')}},
  "size": {{queryParam 'size' '10'}},
  "number": {{queryParam 'page' '0'}},
  "numberOfElements": 10,
  "content": [
    {{#repeat (queryParam 'size' '10')}}
      { 
        "id": "{{@index}}", 
        "isAlive": {{faker 'datatype.boolean'}},
        "name": "{{faker 'vehicle.vehicle'}}",
        "customer": {
          "id": "{{faker 'datatype.uuid'}}",
          "name": "{{faker 'word.interjection'}}"
        },
        "farm": {
          "id": "{{faker 'datatype.uuid'}}",
          "name": "{{faker 'word.interjection'}}"
        },
        "kitId": "{{faker 'datatype.string'}}",
        "hlcVersion": "2.1.3",
        "chassisId": "100",
        "llcVersion": "2.4.1",
        "opStatus": "{{oneOf (array "AUTONOMOUS" "SEMI_AUTONOMOUS")}}",
        "implement": {
          "id": "{{faker 'datatype.uuid'}}",
          "implementType": "{{faker 'word.noun'}}"
        },
        "vehicleTask": {
          "id": "{{faker 'datatype.uuid'}}",
          "name": "{{faker 'vehicle.model'}}"
        }
      }
    {{/repeat}}
  ]
}

**Mockoon version:**
v.3.1.0

**OS / OS version:**
Mac OS

**Comment by 255kb** [comment]
It's your responsibility to ensure that the generated JSON is valid. With the variety of helpers and things that could go wrong, it's hard to make sure that it's 100% valid. 
it seems that `datatype.string` that you are using for `kitId` can use any character including [ and { which can break the JSON. I suggest that you use [`random.alphanumeric`](https://v7.fakerjs.dev/api/random.html#alphanumeric) or `datatype.uuid` that should be safer.

**Comment by dmitry-k-fe-bw** [comment]
> It's your responsibility to ensure that the generated JSON is valid. With the variety of helpers and things that could go wrong, it's hard to make sure that it's 100% valid. it seems that `datatype.string` that you are using for `kitId` can use any character including [ and { which can break the JSON. I suggest that you use [`random.alphanumeric`](https://v7.fakerjs.dev/api/random.html#alphanumeric) or `datatype.uuid` that should be safer.

Thank you for the answer, kitId it was exactly the cause of the problem
