### ISSUE TITLE
[Feature Request] - Request Body Field Datatype Verification in rules

### ISSUE THREAD

**Issue by ghost** [mockoon/mockoon#1092]
I didn't see a way already to do this looking at the documentation, but it would be great if add datatypes to the rules so maybe something like this

![image](https://github.com/mockoon/mockoon/assets/139786662/317a0ddc-2a50-4006-90cb-21830eab221e)

Or maybe like this

![rules mock](https://github.com/mockoon/mockoon/assets/139786662/fb47fb44-83ff-43ae-b899-6623c90c5d42)

**Comment by ajatkj** [comment]
@condrovic Would you be able to provide some use cases where such a rule can be used?

**Comment by 255kb** [comment]
This will be handled in #1452 through the creation of a new rule used to validate anything against a JSOn schema.
