### ISSUE TITLE
Mockoon-CLI 4.0.0 timeout on CI

### ISSUE THREAD

**Issue by Kamilton** [mockoon/mockoon#1096]
**Describe the bug**

Since version 4.0.0 mockoon-cli seems to run on main thread instead in background. This causes terminal to stay occupied and timeout build in CI (Azure). Is there a way to make it work with CI?

**To Reproduce**

`npm install -g @mockoon/cli && mockoon-cli start --data ./new_mocks.json`

but if I tested with older version like: `npm install -g @mockoon/cli@3.1.0 && mockoon-cli start --data ./new_mocks.json`

than it works fine

**Mockoon version:**

4.0.0

**OS / OS version:**

macOS 12/13

**Comment by 255kb** [comment]
@Kamilton Hi, 
We took opportunity with this major version to simplify the CLI and remove all the process management code (which was using PM2). There are plenty of other ways to manage processes, like containerization. 
The CLI is now running in foreground by default and it's up to you to manage the process or send it to the background. 

You should be able to do this in your CI pipeline by adding a `&` at the end of the command: 
`mockoon-cli start -d ./data-file.json &`

This is the technique we use in our official [GitHub Action](https://github.com/marketplace/actions/mockoon-cli).

Let me know if this solves your issue.

**Comment by Kamilton** [comment]
> @Kamilton Hi, We took opportunity with this major version to simplify the CLI and remove all the process management code (which was using PM2). There are plenty of other ways to manage processes, like containerization. The CLI is now running in foreground by default and it's up to you to manage the process or send it to the background.
> 
> You should be able to do this in your CI pipeline by adding a `&` at the end of the command: `mockoon-cli start -d ./data-file.json &`
> 
> This is the technique we use in our official [GitHub Action](https://github.com/marketplace/actions/mockoon-cli).
> 
> Let me know if this solves your issue.

Yes, that helps. Just needed to figure how to stop the process a the end since there is no more a "stop" command but it's fine. Thank you.

**Comment by Kamilton** [comment]
After using `&` to send it to background it's not blocking anything

**Comment by 255kb** [comment]
OK, thank you for the precision!
