### ISSUE TITLE
On macOS Cmd-W should close active window and Cmd-Q should quit app

### ISSUE THREAD

**Issue by afedotov** [mockoon/mockoon#1097]
I would like to rise issue #838 back.
Actually on **macOS** commonly adopted behavior should be:

 - Pressing `Cmd-W` will close active window keeping application running in Dock
 - Pressing `Cmd-Q` will quit application completely even from Dock

For reference just look at behavior of Visual Studio Code as it is also Electron based, or any other macOS application. Current behavior is very annoying. You should press `Cmd-Q` literally multiple times to actually quit application, and `Cmd-W` is just ignored.

**Comment by ruittenb** [comment]
IMO the behavior should indeed be changed. It is used by other applications as well:
- closing a window with Cmd-W or the red button in the title bar closes the window, but leaves the application running 
- closing the application with Cmd-Q or from the [File] menu quits the application, also from the dock

This is actually also mentioned in the links which were referenced by @255kb  in https://github.com/mockoon/mockoon/issues/838 :

- https://stackoverflow.com/questions/35008347/electron-close-w-x-vs-right-click-dock-and-quit (which specifies that the application keeps running when a _window_ is closed, not when Cmd-Q is used)
- https://www.electronjs.org/docs/latest/tutorial/tutorial-first-app#open-a-window-if-none-are-open-macos (which says that _macOS apps generally continue running even without any windows open_, which is not the same as _when the application is quit with Cmd-Q_ or from the [File] menu)
- https://stackoverflow.com/questions/44316306/how-to-quit-electron-app-on-mac (which says that _when a window is closed_, the application stays running in the dock, but Cmd-Q should quit the application completely).
-

**Comment by 255kb** [comment]
📦 This is now updated in [v6.2.0](https://mockoon.com/releases/6.2.0/). Let us know what you think!

**Comment by afedotov** [comment]
Yes, thank you, `Cmd-Q` and `Cmd-W` behavior is as expected now!

But looks like some other things should be updated to match this behavior, maybe need to create different issue:

- When active application window is closed, no any possibilities to bring it back except clicking on the application dock icon. Typically in applications some keyboard shortcut and menu command exists like `Open New Window`. But since this application design is single-window, maybe there should be some shortcut complementary to `Cmd-W`, like `Open Application Window`, `Cmd-Shift-N` or `Cmd-T`?
- Other application menu items and shortcuts should be updated for the case when application window is in closed state. They should be disabled or just bring closed application window back when used. For now when using such commands/shortcuts when window is closed, like `Open Environment Cmd-O` or `Settings Cmd-,` they just being ignored.

**Comment by HighLiuk** [comment]
Hey @255kb thanks finally! That was a very frustrating bug on macos for Mockoon, but it now works as expected!
