### ISSUE TITLE
"." in parameter name not working for queryParam and queryParamRaw

### ISSUE THREAD

**Issue by ajatkj** [mockoon/mockoon#1115]
**Describe the bug**
[PR 768](https://github.com/mockoon/mockoon/pull/768) fixed similar issue in helper functions body and bodyRaw but not in queryParam and queryParamRaw

**To Reproduce**
Use queryParam param.name and it won't work.

I am proposing a fix in request-helpers.ts to add code similar to body and bodyRaw functions to fix queryParam and queryParamRaw functions.

Let me know if I can raise a PR to fix this or has this been left out on purpose in PR 768 for some known issue?

**Comment by 255kb** [comment]
@ajatkj It wasn't left out on purpose. it should have been fixed then I guess.
Feel free to propose a fix. I assigned the issue to you.

**Comment by ajatkj** [comment]
@255kb Thanks. Will raise a PR soon.

**Comment by 255kb** [comment]
📦 This is now available with [release v4.1.0](https://mockoon.com/releases/4.1.0).
