### ISSUE TITLE
Specify MIME Type When Loading Templates From FilePath

### ISSUE THREAD

**Issue by ezweave** [mockoon/mockoon#1120]
Editors and linters complain about the `.json` extension on non-pure `JSON` files.  E.g. files with handlebar templating.  However, the same editors and linters understand `.handlebars` or `.hbs` as being Handlebars templates (and don't try to fix/format/lint them).

It would be nice if we could specify and _not_ autodetect the MIME type so that we can make both Mockoon and your editor happy.

![image](https://github.com/mockoon/mockoon/assets/568995/4620a3b1-ad12-4f9e-affe-71193ebea3bd)

**Comment by 255kb** [comment]
The MIME type indicated here is the one detected by the library we are using. It will be used as the Content-Type when making requests, unless you override it in the route headers.
It's working correctly with .hbs:
![image](https://github.com/mockoon/mockoon/assets/7489814/96038ee7-774d-429b-a692-8faf49b8196b)
But it gets served with `text/x-handlebars-template` as the Content-Type, which is probably not what you want.
![image](https://github.com/mockoon/mockoon/assets/7489814/bd86bfe7-f43e-4a83-a14a-32adedefc19c)

If you add a `application/json` Content-Type route header, it will always override the MIME type and you will be able to serve as JSON while using a .hbs or .handlebars file. 

I don't think there is something to fix here.

**Comment by ezweave** [comment]
> The MIME type indicated here is the one detected by the library we are using. It will be used as the Content-Type when making requests, unless you override it in the route headers. It's working correctly with .hbs: ![image](https://user-images.githubusercontent.com/7489814/262590874-96038ee7-774d-429b-a692-8faf49b8196b.png) But it gets served with `text/x-handlebars-template` as the Content-Type, which is probably not what you want. ![image](https://user-images.githubusercontent.com/7489814/262590814-bd86bfe7-f43e-4a83-a14a-32adedefc19c.png)
> 
> If you add a `application/json` Content-Type route header, it will always override the MIME type and you will be able to serve as JSON while using a .hbs or .handlebars file.
> 
> I don't think there is something to fix here.

Sadly, that does not actually solve this problem.

Setting the `Content-Type` in the Response does not convert it to JSON, it remains a `hbs`.

![image](https://github.com/mockoon/mockoon/assets/568995/a200ccbe-93d5-4cb0-b8d2-eaa400f746e5)

The UI does not render the response, which is not the worst:

![image](https://github.com/mockoon/mockoon/assets/568995/83591338-72ad-42e7-932f-6d8916021eed)

However it also does not process the template and returns a raw `hbs` file:

![image](https://github.com/mockoon/mockoon/assets/568995/05688155-72e8-4e8e-8fff-742c5be647e7)

Mockoon seems to now think this is JSON:

![image](https://github.com/mockoon/mockoon/assets/568995/3cdcc17a-9f0f-4f14-add5-235eb1502b47)

Even if we remove the `Content-Type` from the response it still does not process it.  The only way to make it work is to keep using a `.json` extension.

**Comment by 255kb** [comment]
Ok I see the issue now. There is a limited number of file types in which we parse the templating. Hbs is not part of it.
It's a small fix, it will do it for the next release, which happens to be today :)

**Comment by 255kb** [comment]
📦 This is now available with [release v4.1.0](https://mockoon.com/releases/4.1.0).
