### ISSUE TITLE
[Feature] Make filter helper works with nested objects

### ISSUE THREAD

**Issue by edtoken** [mockoon/mockoon#1123]
The actual implementation of the filter helper allows filtering like `key=value` structure,  
so allows us to filter by values only of the 1 level of the object.

It could be great to have the ability to filter by nested structures.

```
filter (dataRaw 'my-data') (object key=(object subKey="sub-value"))
```

Should be possible with easy fix of the filter helper [here](https://github.com/mockoon/mockoon/blob/main/packages/commons-server/src/libs/templating-helpers/helpers/filter.ts#L26)

<img width="619" alt="Screenshot 2023-08-26 at 19 55 46" src="https://github.com/mockoon/mockoon/assets/4567083/a9f9b66e-11d6-4661-adc7-663c1a596ecd">

**Comment by 255kb** [comment]
📦This was released in [v9.0.0](https://mockoon.com/releases/9.0.0/)
