### ISSUE TITLE
[Feature] Allow regular expression in path string for body, bodyRaw, query & queryRaw

### ISSUE THREAD

**Issue by ajatkj** [mockoon/mockoon#1129]
For some use cases, it is required to get all keys matching a regex - ex. 
```json
{
   "filter-1": "filter-value-1",
   "filter-2": "filter-value-2",
   "filter-3": "filter-value-3"
}
```

So I was thinking something like `{{bodyRaw '/filter-./'}}` could be used to extract all values - ['filter-value-1', 'filter-value-2', 'filter-value-3']

Some thoughts around this-
- Only paths which have 2 forward slashes (/) match for regular expression
- Any thing before first / is treated as the nested path (will provide example below)
- Anything after the last / is treated at regex flags

Nested example-

```json
{
    "Subject": "regex-filters",
    "Property.1.Value.1": "property-value-1",
    "Property.1.Value.2": "property-value-2",
    "Property": {
        "InnerProperty": {
            "Property1Name": "property-1-name",
            "Property2Name": "property-2-name",
            "Property3name": "property-3-name"
        },
        "Inner.Property": {
            "PropertyName": "property-name"
        }
    }
}
```

In this case you could use something like
- `{{body '/Property.1.*/'}}` => `['property-1-name', 'property-2-name', 'property-3-name']`
- `{{body 'Property.InnerProperty./.*Name/i'}}` => `['property-value-1', 'property-value-2']`
- `{{body 'Property.Inner\\.Property./.*Name/'}}` => `['property-name]`

This can in turn be used with any helpers that work with arrays like oneOf, someOf.

Let me know your thought and if I can raise a PR for the same as I have been working on these changes.

**Comment by ajatkj** [comment]
What you say makes sense. Better to have a well known solution then to implement something which is not scalable and very specific. 
I will work on JSON path implementation and we can close this issue.
Are you on discord by any chance where I can dm you in case I need some help with JSON path implementation. No pressure though :)

**Comment by 255kb** [comment]
Nice !
Could you please comment on the other issue so I can assign it to you?

You can find me on our [Discord server](https://discord.com/invite/JmTBk59MTb)  (or DMs it's the same username). Feel free to ask if you have any question.
