### ISSUE TITLE
npm run test:commons-server fails due to incorrect import

### ISSUE THREAD

**Issue by ajatkj** [mockoon/mockoon#1130]
**Describe the bug**

Running `npm run test:commons-server` fails with below error-
```
> @mockoon/commons-server:test

> @mockoon/commons-server@4.1.0 test
> ts-mocha -p ./tsconfig-build-cjs.json --timeout 10000 --forbid-only "./test/suites/**/*.spec.ts"
Error: Cannot find module '@mockoon/commons/src'
```

**To Reproduce**

Install a new module jsonpath-plus in packages/commons-server => `npm install --save jsonpath-plus@7.2.0`
Build commons-server => `npm run build:commons-server`
Run tests => `npm run test:commons-server`

I could see the offending code in 
`packages/commons-server/test/suites/response-rules/response-rules-interpreter.spec.ts`

```js
import {
  BodyTypes,
  EnvironmentDefault,
  ResponseMode,
  ResponseRuleTargets,
  RouteResponse
} from '@mockoon/commons';
import { expect } from 'chai';
import { Request } from 'express';
import QueryString from 'qs';
import { xml2js } from 'xml-js';
import { ResponseRulesInterpreter } from '../../../src/libs/response-rules-interpreter';
import { GenerateDatabucketID } from '@mockoon/commons/src';
```

This should be replaced with

```js
import {
  BodyTypes,
  EnvironmentDefault,
  GenerateDatabucketID,
  ResponseMode,
  ResponseRuleTargets,
  RouteResponse
} from '@mockoon/commons';
import { expect } from 'chai';
import { Request } from 'express';
import QueryString from 'qs';
import { xml2js } from 'xml-js';
import { ResponseRulesInterpreter } from '../../../src/libs/response-rules-interpreter';
```

After this change, tests run fine.

I am working on PR for jsonpath-plus. Let me know if can I include this in the same PR or raise a new one just for this fix?

**Mockoon version:**

4.1.0

**OS / OS version:**

Mac OS

**Comment by 255kb** [comment]
Sure you can solve this in the same PR.
Same happened to me some days ago. VSCode imported from /src which is wrong. 
I just wonder how this went into the main branch unnoticed
