### ISSUE TITLE
Add Docker Image Tag for Major Versions

### ISSUE THREAD

**Issue by gilles1986** [mockoon/mockoon#1132]
Some Developers might want to support a Mockoon client for a specific version Range. Currently it's just possible to choose between one specific Version (like 4.0.1) and The "latest" Version. But sometimes you want to stick with one Major Version without any breaking changes and want manually to update to the next major version. So a Docker Image Tag would be nice like (4) which would always include the Tag of the latest 4.x.x Version. You see this better in this gif
https://stevelaskerblog.files.wordpress.com/2018/03/stabletagging.gif?w=1024&h=274

Article Reference: https://stevelasker.blog/2018/03/01/docker-tagging-best-practices-for-tagging-and-versioning-docker-images/

**Comment by 255kb** [comment]
📦 This is now available with [release v5.0.0](https://mockoon.com/releases/5.0.0/).
