### ISSUE TITLE
Option to enable or disable Non SSL Call for CLI, Docker 

### ISSUE THREAD

**Issue by Sadagopan88** [mockoon/mockoon#1134]
**Option to disable Non SSL for CLI, Docker .**

We need to have option to disable Non SSL in cli, Docker. like docker env variables. 
I have a hosting platform which supports SSL but the API response in both SSL and non SSL port.

**Comment by 255kb** [comment]
I'm not sure to understand what you are asking. If TLS is enabled Mockoon is only answering using the HTTPS protocol on the port you provided. 
Could you please give an example with steps to reproduce the behavior?
Thanks
