### ISSUE TITLE
Mockoon app does not reflect JSON file changes

### ISSUE THREAD

**Issue by victorzw895** [mockoon/mockoon#1141]
**Describe the bug**

Same issue mentioned here [Environment does not reflect JSON file's changes](https://github.com/mockoon/mockoon/issues/580)
Whenever there is a difference in the shared data.json and we change branches or merge from main. Mockoon app will not reflect those changes and instead will update the data.json to what the Mockoon app's current environment has.
Need to quit Mockoon and then merge or change branches to get updated environments on Mockoon app

**To Reproduce**

1. Create branch and Make changes to Mockoon environment that references data.json from a shared repo. Push changes.
2. Checkout to main. 

Expected Behaviour
- expected Mockoon app to update and reflect data.json from main

Current Behaviour
- data.json is updated reflecting Mockoon app's environment.

**Mockoon version:**

v4.1

**OS / OS version:**

Mac OS

**Comment by 255kb** [comment]
@victorzw895 This was [released in 1.18.0](https://mockoon.com/blog/file-monitoring-mock-api-samples/#file-monitoring). It's not enabled by default though and you need to go in the settings.

It's true that it's not in the documentation. I will update it.
