### ISSUE TITLE
Support for urlencoded form params

### ISSUE THREAD

**Issue by javikr** [mockoon/mockoon#116]
Hello,
It would be great if we could get 'queryParam' and 'bodyParam' in a POST type request.  At his moment it seems that Mockoon only supports 'bodyParam" for a POST type request, and any other query param type is ignored.

There are APIs that accept queryParams and bodyParams in a POST type.

¿Is this possible?

Thanks for your work,

**Comment by 255kb** [comment]
Normally this is already supported. 
The body is parsed as soon as data is detected whatever the request content-type or method are. And the `body` helper **(/!\ `body` not `bodyParam`)** tries to parse the JSON body and find a path (like `addresses.0.street`). If it's not JSON, or an invalid JSON it won't work. 

Concerning the `queryParam` helper it definitely works with any kind of request method (I just tested it). 

Could you please retest? If you still have problems you can post a screenshot or the data your are using so I can help you.

**Comment by javikr** [comment]
Hi,
Sorry. I have retested and the content-type of the request is "application/x-www-form-urlencoded".

How can I get the params value from this kind of request?

Thank you for your support,

<img width="676" alt="Captura de pantalla 2019-04-10 a las 17 44 09" src="https://user-images.githubusercontent.com/3273648/55893629-f8ee7d00-5bb8-11e9-94a2-3a9b2400096c.png">
<img width="515" alt="Captura de pantalla 2019-04-10 a las 17 44 39" src="https://user-images.githubusercontent.com/3273648/55893630-f9871380-5bb8-11e9-84cd-9816f8eeab27.png">

**Comment by 255kb** [comment]
ok, thank you for the explanation. This would need some development in order to parse the urlencoded form params and add a new helper.
