### ISSUE TITLE
Migration to 5.1.0 introduces breaking change

### ISSUE THREAD

**Issue by yohny** [mockoon/mockoon#1174]
**Describe the bug**
I recently upgraded my Mockoon from 5.0.0 to 5.1.0 and as specified in release docs my enviroments were migrated to new faker.js v8. However I found that one of those migration introduces a breaking change. 
Specifically `{{faker 'datatype.number'}}` was migrated to `{{faker 'number.int'}}` which produce very different value ranges. The old one produces values in range `0 - 99999`, but the new one produces range `0 - Number.MAX_SAFE_INTEGER`, which is 
2^53 – 1 according to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER).
Thats a problem - such values will be out of bounds of standard INT range (Int32) that has limits of (+/-)2^31. So attempts to parse such mocked response will fail in any language/framework/runtime using this standard int rage (.NET, Java, PHP)

dosc for old `datatype.number` https://fakerjs.dev/api/datatype.html#number
docs for new `number.int` https://fakerjs.dev/api/number.html#int

**To Reproduce**
Take any enviroment created in Mockoon 5.0.0 (or older) that uses `{{faker 'datatype.number'}}` and upgrade Mockoon to  5.1.0. Try to parse migrated responses in frameworks/runtimes that use standard Int32 range and it will fail.

**Mockoon version:**

5.1.0

**OS / OS version:**

Windows 10

**Comment by 255kb** [comment]
Thanks for reporting. Unfortunately, despite all the care we took during the release, this issue slipped through.

The majority of users have already migrated to the new version, so there is no point in releasing a hotfix. We will, however, make modifications to the migration script for the next release.

**Comment by 255kb** [comment]
📦 This is now released in [v6.0.0](https://mockoon.com/releases/6.0.0/).
