### ISSUE TITLE
Scenario feature for instantly testing

### ISSUE THREAD

**Issue by Samandar02** [mockoon/mockoon#1175]
Hello Mockoon team, I would like somethin like 'Scenario' features, this scenario not rely on any rules and it work with one environment, for instance, I will have few or more scenario on dashborad of Mockoon desktop, 
ex:
```
> Every response successfully scenario
--------------------------------------
> Every response unsuccessfully scenario
--------------------------------------
> Auth error scenario,
--------------------------------------
> Bad request on loading customers scenario,
--------------------------------------
> Bad request on deleting customer
--------------------------------------
```
then i will select one of them scenario, then i can test that scenario instantly with my project, instead setup every rule case for my request body or parameter, simply i will select one scenario for environment, then it will simply return for that scenario without any rules.

**Comment by 255kb** [comment]
I think this could be handled by enabling/disabling all the routes in a folder: https://github.com/mockoon/mockoon/issues/1188
I would like to avoid introducing a new complex interface.
