### ISSUE TITLE
Unable to understand the request reached upstream of proxy mock server sent response

### ISSUE THREAD

**Issue by manjeshpv** [mockoon/mockoon#1179]
i enabled proxy server and mocked a url

**Feature Request 1:**
now in logs i can see 50 requests served, but unable to understand which served by mock and which requests reached upstream

**Feature Request 2:**
- when i create too many routes, unable to categories
- feature like folders or tags will help

**Comment by 255kb** [comment]
Please, try to open one issue per problem, or better use discussions before opening issues. 
Both improvements you are describing already exist:

## Route folders: https://mockoon.com/docs/latest/api-endpoints/folders/

![image](https://github.com/mockoon/mockoon/assets/7489814/d524c013-af8b-4723-b90b-f4dc86c40dc7) 
![image](https://github.com/mockoon/mockoon/assets/7489814/31abeca4-8374-4441-b8bf-cb7961dbb711)

## Logs proxied or not: 

![image](https://github.com/mockoon/mockoon/assets/7489814/3d0610d3-026e-48a1-a5e9-c92992116cef)
