### ISSUE TITLE
Open multiple environments at once

### ISSUE THREAD

**Issue by captainweeaboo** [mockoon/mockoon#1187]
User has to manually add all environments one by one which can become really frustrating if you have multi-moduled project. I propose to add ability to select multiple environments and import them in bulk.

**Comment by akopchenov** [comment]
We have the same problem with our multi-module project. It will be good to make this feature.

**Comment by captainweeaboo** [comment]
Local environments at once

**Comment by 255kb** [comment]
📦 This was added in [v8.1.0](https://mockoon.com/releases/8.1.0/)
