### ISSUE TITLE
Toggle Folders with Routes

### ISSUE THREAD

**Issue by nvanderwaal** [mockoon/mockoon#1188]
### Overview

Mockoon is a great tool for developers, as it provides the capability to organize routes into folders. This feature request aims to enhance the user experience even further by allowing folders containing routes to be toggled on and off (enabled/disabled) with a single action. By including this feature, users will be able to quickly and easily manage the availability of a group of routes without manually toggling each route individually.

### Proposed Functionality

1. **Folder Toggle Icon**: Add a toggle icon inside the dropdown of a folder in the route list, which allows users to enable or disable all routes within that folder simultaneously.

2. **Folder Toggle State**: The folder should indicate the current state (enabled/disabled) of its associated routes by providing a clear visual cue for the user, such as a red line similar to the one used for routes. 

3. **Mixed State**: In case the folder contains a mix of enabled and disabled routes, the folder should show a mixed state (e.g., an orange line) to reflect this.

4. **Inheritance**: When adding a new route to a folder, the route should inherit the toggle state of the folder it's being added to by default.

5. **Bulk Toggling**: When the user toggles a folder on or off, all the routes within that folder should also be enabled or disabled accordingly, making it easy to manage groups of routes quickly.

Implementing this folder toggle feature will empower Mockoon users to work more effectively and efficiently with their route configurations. The ability to enable or disable multiple routes within a folder with a single action will save users time and contribute to an enhanced user experience overall.

**Comment by santiagocarod** [comment]
Hi

I would like to take a look into this.

Please let me know! 

Thanks

**Comment by 255kb** [comment]
@santiagocarod sure you can, I will assign the issue to you. 

My opinion on this proposed feature: 

I would like to avoid adding a new status on the folder in the data model. 
Each Route is listed as disabled in the desktop app settings. When running a mock with the CLI or serverless package, [a list of uuids or keywords/path can be provided](https://github.com/mockoon/mockoon/blob/main/packages/cli/README.md#start-command) to disable them at runtime. 

1. yes, that makes sense
2. why not, but only based on the route disabled status. It could be a red bar like for the route, eventually dashed, when only some route are disabled. 
![image](https://github.com/mockoon/mockoon/assets/7489814/1eaab855-c3f9-4f62-8542-d6927d393531)
3. See no. 2. I would prefer a dashed red line, as orange/yellow is rather used for information requiring the user attention. 
4. As we shouldn't introduce a folder toggle state, I'm not sure about the inheritance. Maybe if al children are disabled, the new route could be disabled too? It's the only useful case I see. 
5. As we shouldn't introduce a folder toggle state, that is redundant with no. 1.

Main tasks that would be required: 
- adding a new context menu entry on folders to toggle its routes. 
- adding a new toggle state (right red bar) on the folder, summarizing it's own routes states. 
- making the CLI and serverless "keyword" look both in the paths and folder names.

Questions: should all this be recursive? Meaning, toggling applies to all the children, recursively. Same for the red bar indicator. Should it take into account all the children toggle states recursively? I would say no, to simplify this PR.

Happy to discuss here or on [Discord](https://mockoon.com/discord/).

**Comment by santiagocarod** [comment]
@255kb 
Hi Guillaume!

Perfect, thanks

I'm checking it out right now as a first look.

I understand that you would like to avoid adding the status for the Folder data model, should I go with the same approach as the project currently has with disabledRoutes and collapsedFolders?

**Comment by 255kb** [comment]
@santiagocarod I think we could go without adding any new state. For example, disabling from the folder menu could disable all the children route one by one. Like that we keep the feature small enough. What do you think?

**Comment by santiagocarod** [comment]
Yes, agree!
 I think we can go step by step and keep things simple.
I think I got this functionality, let me make a PR with this

**Comment by 255kb** [comment]
[PR](https://github.com/mockoon/mockoon/pull/1323) was merged for the next release. It will only contain the new menu entry on folders to toggle all routes, for now. I also added the ability to toggle a folder's content at runtime using the CLI/serverless package. 
Let's see if there is more interest in the future for advanced features.

**Comment by 255kb** [comment]
📦 This was released with [v8.2.0](https://mockoon.com/releases/8.2.0/)
