### ISSUE TITLE
Special characters like parentheses should be replaced while recording or adding the route from the logs

### ISSUE THREAD

**Issue by neotrow** [mockoon/mockoon#1190]
**Describe the bug**

When recording or manually adding a route from the logs, special characters are not escaped. For example parentheses.

**To Reproduce**

1. start mockoon 
2. request a url that doesn't exist with parentheses in it. For example `/test(data)`
3. either add the route automatically by using the record feature or manually from the logs
4. visiting `/test(data)` won't work. 
5. manually modify the route to `/test\(data\)` and now it works.

**Mockoon version:**

5.1.0

**OS / OS version:**

Windows 11

Related issue: https://github.com/mockoon/mockoon/discussions/521

Open questions:

Are there are characters that also need escaping?

**Comment by 255kb** [comment]
📦 This is now released in [v6.0.0](https://mockoon.com/releases/6.0.0/).
