### ISSUE TITLE
Allow auto start for environments

### ISSUE THREAD

**Issue by alonbhaim** [mockoon/mockoon#121]
Hi,

We working with mockoon and we need the server to start automatically when we open the app, I think it need to be checkbox at environment settings.

Thanks!

**Comment by victornovy** [comment]
@255kb I would like to start contributing to the project and I want to know if this feature still on roadmap to be implemented

**Comment by 255kb** [comment]
All help is welcome :) 
I will assign the issue to you and put it on the roadmap. 

Here are my idea on how this should be implemented, but of course, I am opened to ideas. 

- There should be a new setting (a checkbox) in the settings modal. (like @alonbhaim said)
- In the `EnvironmentService`, after loading the environments, it should detect that the new setting is at true and exec the `toggleAllEnvironments` method.

Let me know if you need anything, or explanation with the code, etc. 
You can reach me on our [Discord channel](https://discord.com/invite/JmTBk59MTb).
