### ISSUE TITLE
incorrect Rules disabled notification when using a sequence rule

### ISSUE THREAD

**Issue by jessewriter** [mockoon/mockoon#1231]
**Describe the bug**

when I click the run in sesquence button i see a rules diabled yellow warning label.  but when I run my code indeed this rule is applied and I see response 1 on the first and third call.
**To Reproduce**
make sequential rules and apply the run in sequence button

**Mockoon version:**
6.0.1

**OS / OS version:**

win 11
<img width="788" alt="image" src="https://github.com/mockoon/mockoon/assets/16365134/0ffce05c-a072-435f-a468-295a0ad3fb5f">

**Comment by 255kb** [comment]
Could you share your setup, or at least a screenshot of your responses list? 
The sequential response mode is completely bypassing the rule, no even looking at them. But it does more or less what a "Request number" rule does. 
I suspect that you have 2 responses and that response 1 get indeed served the first and third time.

**Comment by jessewriter** [comment]
Response one is served the first and third time and then five more times only response two is displayed, so it is running as a rule is defined not just randomly

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by 255kb** [comment]
Could you please share your full configuration (right click on the environment, then "Copy JSON to clipboard")? Without a way to reproduce this I have no way to know if it's a bug or not.

**Comment by jessewriter** [comment]
So having sequence is same as a rule alternating.  I realized I need to restart the server every time I want to reset call1.  Thank you for responding I think this is my own misunderstanding as a new user

**Comment by jessewriter** [comment]
User error
