### ISSUE TITLE
Support response modification through "CRUD" endpoints

### ISSUE THREAD

**Issue by kamil-maslowski** [mockoon/mockoon#124]
**Is your feature request related to a problem? Please describe.**
So I'm currently working on a FE app that makes a lot of GET/*DELETE* request that returns lists. But I'm not really able to go through all the scenarios on FE cuz even after I sent a DELETE request for an array item, GET will still return the same.

**Describe the solution you'd like**
Make it possible to generate static request in _Body_ window, that will be modified by mockoon on DELETE (maybe also PATCH?) requests. So when I DELETE `/api/sth/1234` -> `sth` with id _1234_ will get deleted

**Describe alternatives you've considered**
None?

**Additional context**
This is supported e.g. in `mockapi.io`

**Comment by kalpeshhpatel** [comment]
Is there any suggestions, plan to implement this feature?

**Comment by 255kb** [comment]
@kalpeshhpatel It's high on our list. We recently worked on a persisting [data buckets](https://mockoon.com/docs/latest/data-buckets/overview/) system which will make this feature easier to develop. 
It is not the most upvoted feature but it is still a behavior that most people expect to see, like json-server. So, it's one of the next feature to come.

**Comment by kalpeshhpatel** [comment]
Hi @255kb , thank you so much for the update.

Somehow can we make use data buckets to store the POST call data and retrieve it from GET call?

Thanks

**Comment by 255kb** [comment]
No, data buckets are persisting but there is no link between routes. That was CRUD routes will be for.

**Comment by kalpeshhpatel** [comment]
Got it. Thanks for your reply @255kb . Tried out new data buckets feature, looks interesting. However, would be good if it supports JSON body too. Currently when I use the JSON content into data bucket, the route response throws following error: 

`Error while serving the content: You must pass a string or Handlebars AST to Handlebars.compile. You passed [object Object]`

The use-case of having the JSON format in the data buckets could be to store common piece of response for multiple routes.

Btw, great tool, and thank you so much for this 👍🏻 Can't wait to see the CRID routes feature, which I am sure would be most exiting feature.
