### ISSUE TITLE
RepoRater badge to README

### ISSUE THREAD

**Issue by eddiejaoude** [mockoon/mockoon#1242]
Benefits
- people can see how friendly the repo is
- makes it easier for people to click on the badge and add their own vote

Example
RepoRater Badge [![RepoRater](https://repo-rater.eddiehub.io/api/badge?owner=EddieHubCommunity&name=RepoRater)](https://repo-rater.eddiehub.io/rate?owner=EddieHubCommunity&name=RepoRater)

Mockoon badge [![RepoRater](https://repo-rater.eddiehub.io/api/badge?owner=mockoon&name=mockoon)](https://repo-rater.eddiehub.io/rate?owner=mockoon&name=mockoon)

Markdown for mockoon badge...
```
[![RepoRater](https://repo-rater.eddiehub.io/api/badge?owner=mockoon&name=v)](https://repo-rater.eddiehub.io/rate?owner=mockoon&name=mockoon)
```

**Comment by 255kb** [comment]
Added! https://github.com/mockoon/mockoon/commit/184a9f2b15b771569e59e3ac750fceab8824a2bd
