### ISSUE TITLE
Run "test:commons-server" will end up with "AssertionError: expected '2024' to equal '2023'"

### ISSUE THREAD

**Issue by elianre** [mockoon/mockoon#1248]
Seems we hard coded the expect result for UT:
      expect(parseResult).to.be.equal('2023');

Now it's 2024. :-)

Failed to run /usr/local/bin/npm run test:commons-server

@mockoon/commons-server:   537 passing (271ms)
@mockoon/commons-server:   2 failing
@mockoon/commons-server:   1) Template parser
@mockoon/commons-server:        Helper: date
@mockoon/commons-server:          should return a date when using queryParams:
@mockoon/commons-server:       AssertionError: expected '2024' to equal '2023'
@mockoon/commons-server:       + expected - actual
@mockoon/commons-server:       -2024
@mockoon/commons-server:       +2023
@mockoon/commons-server:       
@mockoon/commons-server:       at Context.<anonymous> (test/suites/templating-helpers/helpers.spec.ts:417:33)
@mockoon/commons-server:       at processImmediate (node:internal/timers:478:21)
@mockoon/commons-server: 
@mockoon/commons-server:   2) Template parser
@mockoon/commons-server:        Helper: dateFormat
@mockoon/commons-server:          should return a date using a given format, when a Date object is passed as a param:
@mockoon/commons-server:       AssertionError: expected '2024' to equal '2023'
@mockoon/commons-server:       + expected - actual
@mockoon/commons-server:       -2024
@mockoon/commons-server:       +2023
@mockoon/commons-server:       
@mockoon/commons-server:       at Context.<anonymous> (test/suites/templating-helpers/helpers.spec.ts:470:33)
@mockoon/commons-server:       at processImmediate (node:internal/timers:478:21)
@mockoon/commons-server: 

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  Lerna (powered by Nx)   Running target test for project @mockoon/commons-server failed

**Mockoon version:**

latest main

**OS / OS version:**

Mac OS

**Comment by 255kb** [comment]
Thanks for spotting this, it has been fixed. Forever! 👷
