### ISSUE TITLE
Error running installer

### ISSUE THREAD

**Issue by asdf23** [mockoon/mockoon#1249]
**Describe the bug**

**Steps to Reproduce**
Install lastest version see error:
---------------------------
Mockoon.exe - Entry Point Not Found
---------------------------
The procedure entry point DiscardVirtualMemory could not be located in the dynamic link library 
C:\Users\<user>\AppData\Local\Programs\mockoon\Mockoon.exe. 
---------------------------
OK   
---------------------------

**Mockoon version:**

Latest

**OS / OS version:**

OS Name:                   Microsoft Windows Server 2012 R2 Datacenter
OS Version:                6.3.9600 N/A Build 9600

**Comment by 255kb** [comment]
Mockoon does not support Windows 8 nor Windows server 12 as [Electron](https://github.com/electron/electron/issues/36909) does not support it anymore. 
If you need to run your mocks on a server, I suggest that you use the CLI. You will find a tutorial [here](https://mockoon.com/tutorials/run-mock-api-anywhere-cli/).
