### ISSUE TITLE
Proxying icon is not showed in the logs if a fallback route is hitting a proxy

### ISSUE THREAD

**Issue by dwat3r** [mockoon/mockoon#1267]
**Describe the bug**
The problem is that when there's a route, configured with a fallback option, and none of the rules match, then it hits the proxy. This behaviour is great, but in the logs, this proxy hitting response doesn't get the shield icon, but the checkmark. Which makes me believe that it was indeed mocked, and not proxied. But it was, because when I turn off the proxy, then the request produces a 404 response.

**Mockoon version:**
6.1.0

**OS / OS version:**
Mac OS Monterey, 12.7

**Comment by 255kb** [comment]
📦 This is now fixed in [v6.2.0](https://mockoon.com/releases/6.2.0/).
