### ISSUE TITLE
Changing global latency does not prompt to restart server

### ISSUE THREAD

**Issue by chrischain** [mockoon/mockoon#127]
**Describe the bug**
When you change the Global Environment Latency value, Mockoon does not prompt the user to restart the server.  The latency value is not applied until the server is stopped and restarted.

**To Reproduce**
Change the Global Environment Latency value.  Process a request.  You will notice that the request does not have any latency applied.

Stop and restart the server.  You will notice that the request now has the configured latency applied.

**Expected behavior**
Display the server restart yellow icon whenever the Global Environment Latency value is changed.

**Screenshots**
![Mockoon](https://user-images.githubusercontent.com/1153561/57253105-b6c32a80-7002-11e9-9426-f1c2cd74c5c3.png)

**Mockoon version:**
1.3.0

**OS / OS version:**
Windows 7 Professional

**Comment by 255kb** [comment]
Both environment and routes latencies never required a restart. I just tested again on 1.3.0 and 1.4.0 and changing the latencies is immediately reflected during next call. 
I will close this as non reproductible.
