### ISSUE TITLE
Add a custom helper for sorting array

### ISSUE THREAD

**Issue by louiskhchan** [mockoon/mockoon#1270]
Currently, Mockoon has array helpers like `filter` and `slice`. It would be ideal if a `sort` helper could be added.

Discussion: [https://github.com/mockoon/mockoon/discussions/1257](https://github.com/mockoon/mockoon/discussions/1257)

**Comment by ajatkj** [comment]
@255kb Please assign this to me.

**Comment by 255kb** [comment]
We discussed a bit with @ajatkj and propose the following implementation with two helpers: 
- `{{sort 'asc|desc'}}` for arrays of strings and numbers.
- `{{sortBy 'keyname' 'asc|desc'}}` for arrays of objects.

**Comment by 255kb** [comment]
📦 This was released in [v8.3.0](https://mockoon.com/releases/8.3.0/)
