### ISSUE TITLE
When renaming folders, incorrect folder names are shown

### ISSUE THREAD

**Issue by ruittenb** [mockoon/mockoon#1279]
**Describe the bug**

Folder names are not always correctly shown when clicking them.

**Steps to Reproduce**

1. Click a folder's name. Here I have clicked on "file" (note the cursor).

<img width="336" alt="Screenshot 2024-01-24 at 15 01 12" src="https://github.com/mockoon/mockoon/assets/4320070/66898a55-77ea-4cf9-863f-c84af19215fd">

2. Click a different folder's name. Here I have clicked on "options". Note that the folder with the name "file" is now shown as "options".

<img width="351" alt="Screenshot 2024-01-24 at 15 01 30" src="https://github.com/mockoon/mockoon/assets/4320070/505982c0-601d-4925-bf21-e71f2fd4e896">

3. Click a different folder name again. The previously focused folders are now all shown with the name "schedule".

<img width="334" alt="Screenshot 2024-01-24 at 15 01 50" src="https://github.com/mockoon/mockoon/assets/4320070/33b19a8e-97eb-42b0-942c-44019ca1053a">

**Mockoon version:**

6.1.0

**OS / OS version:**

Mac OS Ventura 13.5.1

**Comment by 255kb** [comment]
📦 This is now fixed in [v6.2.0](https://mockoon.com/releases/6.2.0/).
