### ISSUE TITLE
jsonpath-plus always return an empty array when no matching results are found

### ISSUE THREAD

**Issue by ajatkj** [mockoon/mockoon#1297]
**Describe the bug**

When utilizing jsonpath-plus, it has been observed, as reported by @255kb, that the library returns an array containing a single value instead of directly returning the value. This behavior is attributed to the `wrap` option, which is set to `true` by default. 
Read more [here](https://[jsonpath-plus](https://jsonpath-plus.github.io/JSONPath/docs/ts/).github.io/JSONPath/docs/ts/) about it.

This poses a significant challenge, especially when using helper functions with jsonpath, as the expected behaviour is to receive a default value in cases where the path is not found. However, due to the default setting, the functions return an empty array [] instead, preventing the intended default value from being returned.

To tackle this, a breaking change will need to be introduced to set `wrap: false` by default.

**Steps to Reproduce**

Case 1: Single value
Mockoon response
```json
{
  "value": {{body '$.data' '"Default"'}}
}
```

Request body
```json
{
    "data": "value"
}
```

Response body
```json
{
    "value": [
        "value"
    ]
}
```
Expectation
```json
{
    "value": "value"
}
```

Case 2: Invalid json path
```json
{
  "value": {{body '$.invalidData' '"Default"'}}
}
```

Request body
```json
{
    "data": "value"
}
```

Response body
```json
{
    "value": []
}
```
Expectation
```json
{
    "value": "Default"
}
```

**Mockoon version:**
Latest

**OS / OS version:**

Mac OS

**Comment by 255kb** [comment]
📦 This is now released in [v7.0.0](https://mockoon.com/releases/7.0.0/).
