### ISSUE TITLE
not available global var in callback

### ISSUE THREAD

**Issue by randll32** [mockoon/mockoon#1300]
**not available global var in callback**
variables are not available
in callback calls request parameters are not available in callback calls

**Steps to Reproduce**

I tried using SetGlobalVar

{{setGlobalVar 'test123' (int 0 99999999999)}}

in callback
test123={{getGlobalVar 'test123'}}

the variable is not available

**Mockoon version:**

6.0.1

**OS / OS version:**

Linux Ubuntu 22.04, etc  -->

**Comment by Javierdelared** [comment]
Hello, I'm experiencing the same issue. I want to parametrize some fields of the body of the callback based on the initial call, but it's not possible to do with global variables, I don't know if there is any other way.

Here's a minimal example of the problem: 
[testCallback.json](https://github.com/mockoon/mockoon/files/14523154/testCallback.json)

If I make one call to the mock, the return of the callback is empty. However, if I repeat the call a second time, the field is filled correctly with the global variable.

Mockoon version: 7.0.0  
OS / OS version: Windows 10

**Comment by 255kb** [comment]
Thanks for reporting. 
Indeed callbacks are executed just before sending the response but also before generating the response template. 
I will move the callbacks in-between response template generation and actual response sending.

**Comment by 255kb** [comment]
📦 This was fixed in [v8.0.0](https://mockoon.com/releases/8.0.0/)
