### ISSUE TITLE
the template is not parsed in Data when used in Callback

### ISSUE THREAD

**Issue by randll32** [mockoon/mockoon#1302]
**Describe the bug**

the template is not parsed in Data when used in Callback

**Steps to Reproduce**

create route with callback
in callback use Data with:
{{body 'test'}}

request callback => 

{"message":"http://*****/callback/cp?method=fail","context":{"uuid":"076dab47-098f-46c6-a8fa-6df6879a3301","type":"callback","time":0.206032,"memory":22528,"request":{"uri":"http://*******/callback/cp?method=fail","headers":"Accept:          application/json\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: *\r\nConnection:      keep-alive\r\nContent-Length:  15\r\nContent-Type:    application/x-www-form-urlencoded\r\nHost:            pay.av.local\r\nSec-Fetch-Mode:  cors\r\nUser-Agent:      undici\r\nX-Request-Id:    076dab47-098f-46c6-a8fa-6df6879a3301\r\n","body":"{{body 'test'}}","method":"POST","ip":"10.10.12.1"}}},"level":200,"level_name":"INFO","channel":"local","datetime":"2024-02-01T18:12:04.310125+03:00","extra":{}}

**Mockoon version:**

6.0.1

**OS / OS version:**
Linux Ubuntu 22.04

**Comment by isuru89** [comment]
I have provided a fix for this issue in #1305 pull request.

**Comment by 255kb** [comment]
📦 This is now fixed in [v7.0.0](https://mockoon.com/releases/7.0.0/).
