### ISSUE TITLE
someOf would generate array instead of string

### ISSUE THREAD

**Issue by julienchazal** [mockoon/mockoon#131]
**Is your feature request related to a problem? Please describe.**
`"someItems": "{{someOf (array 'item1' 'item2' 'item3') 1 2}}"`
gives
`someItems: "item2,item1"`

**Describe the solution you'd like**
`"someItems": "{{someOf (array 'item1' 'item2' 'item3') 1 2}}"`
would give
`someItems: ["item2", "item1"]`

Thanks !

**Comment by 255kb** [comment]
Handlebars helpers are supposed to return strings and automatically render arrays using `toString()`. So, I came up with a new implementation for v1.5.0 that will require a little bit of work on your side. 
It will be an option and won't break the current implementation:

First option, as a string, to be used in quotes (current implementation that stays the same): 

```
{
  "response": "{{someOf (array 'one' 'two' 'three' 'four' 'five') 1 2}}"
}
--> 
{
  "response": "four,five"
}
```

Second (new) option, as an array, to be used **without** quotes, in triple curly braces to avoid Handlebars escaping and with the last param set to true (which means asArray=true):
```
{
  "response": {{{someOf (array 'one' 'two' 'three' 'four' 'five') 1 2 true}}}
}
--> 
{
  "response": [
    "four",
    "five"
  ]
}
```

I hope this will work for you 😃
