### ISSUE TITLE
Getting data by name will return first data bucket CONTAINING (not just EQUAL) string param

### ISSUE THREAD

**Issue by R0M4N0F5K7** [mockoon/mockoon#1313]
**Describe the bug**
Seems like when referencing a data bucket by name it will return the data from the first one that includes/contains the name as a substring instead of only one of equal name.
E.g. if I get {{dataRaw 'applications'}} it will return the data bucket "applications software" or even "ABC_applications_XYZ", which can't possibly be the expected behavior...?

**Steps to Reproduce**

1) create two data buckets, the second one being name A, the first one having name A as a substring. E.g. first "substring123”, second "string" and fill them with any distinguishable data.
2) reference the shorter, contained string in your response. E.g. {{{stringify (dataRaw 'string')}}}
3) if you call that request you will get the data from the first data bucket in the data list that CONTAINS the string name, "substring123" in our example.

**Mockoon version:**
v6.2.0 on Windows

**Comment by 255kb** [comment]
This was done on purpose to allow users to reference a data bucket without having to write its exact name. 
If you want to get a specific bucket with 100% certainty, you either have to write the full name or use the unique ID visible at the bottom of the data bucket page, or by right-clicking "Copy ID to clipboard": 
<img width="364" alt="image" src="https://github.com/mockoon/mockoon/assets/7489814/f136ea36-8b29-4e94-b59d-363ba55ab962">
