### ISSUE TITLE
Callback with http Authorization header fails with exception

### ISSUE THREAD

**Issue by sgarouachi** [mockoon/mockoon#1328]
**Describe the bug**

As soon as I setup a callback and I add the http header `Authorization` and I run the file, and get below exception
```sh
uncaughtException: Cannot access 'reqHeaders' before initialization\nReferenceError: Cannot access 'reqHeaders' before initialization\n    at /home/vcap/deps/0/node_modules/@mockoon/commons-server/dist/cjs/libs/server/server.js:893:89\n    at Array.map (<anonymous>)\n    at /home/vcap/deps/0/node_modules/@mockoon/commons-server/dist/cjs/libs/server/server.js:893:60\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Steps to Reproduce**

1. create an endpoint
2. setup a callback on that endpoint and add a http header `Authorization`
3. run the file using the cli `mockoon-cli start --data ./data/data.json --port 8080` and you will see the exception in the app.log

**Mockoon version:**

- npm package `"@mockoon/cli": "6.2.0"`

**OS / OS version:**
Linux Ubuntu 22.04

**Comment by 255kb** [comment]
Thank you for reporting. 
Luckily enough, this was already fixed by commit 08847c8e5a92acfd2e63ce4e7c46dbbb9f6fe94a and will be released today.
