### ISSUE TITLE
Any plans for AppImageUpdate integration?

### ISSUE THREAD

**Issue by stereoplegic** [mockoon/mockoon#133]
**Is your feature request related to a problem? Please describe.**
Not a problem, just an enhancement (updating the AppImage according to AppImageUpdate specs).

**Describe the solution you'd like**
Include update information in the AppImage, and latest-linux.yml in Releases

**Describe alternatives you've considered**
The only alternative with AppImage is manually downloading new releases from the repo.

**Additional context**
[User howto](http://www.ubuntubuzz.com/2018/07/how-to-update-appimages-on-gnulinux.html)
From [AppImageUpdate repo](https://github.com/AppImage/AppImageUpdate):

> Update information overview
> 
> In order for AppImageUpdate to do its magic, Update information must be embedded inside the AppImage. Update information is what tells AppImageUpdate vital data such as:
> 
>     How can I find out the latest version (e.g., the URL that tells me the latest version)?
>     How can I find out the delta (the portions of the applications that have changed) between my local version and the latest version?
>     How can I download the delta between my local version and the latest version (e.g., the URL of the download server)?
> 
> While all of this information could simply be put inside the AppImage, this could be a bit inconvenient since that would mean changing the download server location would require the AppImage to be re-created. Hence, this information is not put into the file system inside the AppImage, but rather embedded into the AppImage in a way that makes it very easy to change this information should it be required, e.g., if you put the files onto a different download server. As you will probably know, an AppImage is both an ISO 9660 file (that you can mount and examine) and an ELF executable (that you can execute). We are using the ISO 9660 Volume Descriptor #1 field "Application Used" to store this information.
>

**Comment by 255kb** [comment]
This is apparently not supported by electron builder. But another auto-update feature has been implemented by them and could be used.
FWIW Mockoon is now available on Snap.
