### ISSUE TITLE
"ipv4" helper alias use faker 'internet.ip', should use faker 'internet.ipv4'

### ISSUE THREAD

**Issue by BKFlister** [mockoon/mockoon#1332]
**Describe the bug**
I am using the "ipv4" helper, I see it is an alias for faker 'internet.ip'
faker 'internet.ip' gives random ipv4 or ipv6

My "reading" is that the ipv4 alias should give only ipv4 adresses.
Consider changing the "ipv4" alias to use: faker 'internet.ipv4'

 
**Steps to Reproduce**

[
  {{#repeat 10}}
{
  "ipv4": "{{ipv4}}",
  "faker ipv4": "{{faker 'internet.ipv4'}}"
}
{{/repeat}}
]

**Mockoon version:**
7.0.0

**OS / OS version:**
Mac OS 14

Thanks

**Comment by ajatkj** [comment]
@255kb assign this to me please.

**Comment by ajatkj** [comment]
I understand documentation on website needs to be updated as well.

**Comment by 255kb** [comment]
@ajatkj I assigned it to you, thank you!

You are right regarding the doc. You can open the PR against the `release/next` branch on the mockoon.com repo.
