### ISSUE TITLE
Needed [Copy full url] button 

### ISSUE THREAD

**Issue by Samandar02** [mockoon/mockoon#1333]
It would be good if you could add a [Copy Full URL] button like image below

![image](https://github.com/mockoon/mockoon/assets/58464706/9ec0019c-e021-49b0-80b1-31c95c92af43)

**Comment by 255kb** [comment]
This already exists in the context menu: 
![image](https://github.com/mockoon/mockoon/assets/7489814/e932f072-fc12-4751-9cf8-af0adfb84815)
