### ISSUE TITLE
State purge admin endpoint

### ISSUE THREAD

**Issue by 255kb** [mockoon/mockoon#1334]
## Requirements
We need an admin endpoint to purge the state of a running API mock. Currently, the only solution is to restart the server. In a container/cloud deployment/serverless function, it often means kill the instance or redeploy.

This admin endpoint will be used later for other tasks like #629 or #632.

We specifically need to reset:
- the regenerate the data buckets
- reset the request counter (used in rules)

Everything should happen in the commons-server library.  

## Solution

Add an admin endpoint on running mocks. The path could be: `/mockoon-admin`.

Regarding resetting the state, ideally, the method should be `PURGE` at the root level of the admin endpoint: `PURGE /mockoon-admin`.

However, the PURGE method is often blocked by firewalls and would require extra configuration when running in the CLI. 

The endpoint could accept both the `PURGE` method and `POST` with a specific payload: `{"action": "purge"}`.

As an alternative, the endpoint could also be `POST /mockoon-admin/state/purge`, though, it's not very RESTy.

**Comment by ajatkj** [comment]
@255kb I would suggest going for the later endpoint name convention like `/mockoon-admin/state/purge` as I feel that is more extensible when you want to add other endpoints under admin - GET `/mockoon-admin/logs` etc. This way each endpoint will be responsible for doing one thing and one thing only.

**Comment by 255kb** [comment]
📦 This was added in [v8.0.0](https://mockoon.com/releases/8.0.0/)
