### ISSUE TITLE
Data buckets as response rule target

### ISSUE THREAD

**Issue by Jerantony** [mockoon/mockoon#1337]
**Discussed in #1335** 

- The data buckets of the respective folder are made available as targets of response rules
- A new option "Data bucket" is added to the dropdown list of rule targets
- The "property name or path"-field expects an object/JSON path which has to start with the name or id of a data bucket
- The other fields work as usual

<img width="992" alt="Screenshot-Rule-Target-Data-Bucket" src="https://github.com/mockoon/mockoon/assets/88666775/bf54ef55-bc68-4e2b-b48d-098799547945">

**Comment by 255kb** [comment]
Idea: instead of listing all the data buckets, why not using the [same approach as the global variables rule](https://mockoon.com/docs/latest/route-responses/dynamic-rules/#2-property-name-or-path), by adding the databucket id/name in the path `mybucket.path.to.property`. I know the generated data buckets object in the commons-server lib do not have the same shape than the global variables. 
But in the rules interpreter, it could be possible to create something with the same shape in the `extractTargets` method:

```
// with one databucket name "mybucket" and having id "abc1"

{
  mybucket: databucket.value,
  abc1: databucket.value
}
```

Like that it would be easier to do and you wouldn't have to list all the buckets, remove the rule when the bucket is deleted, etc.

**Comment by Jerantony** [comment]
> Idea: instead of listing all the data buckets, why not using the same approach as the global variables rule, by adding the databucket id/name in the path `mybucket.path.to.property`.
> Like that it would be easier to do and you wouldn't have to list all the buckets, remove the rule when the bucket is deleted, etc.

Great idea! Like that it will be much easire, indeed. I updated the description.

Do I have to worry about the bucket name containing spaces? 🤔 
And could you please tell me your node/npm versions as I have troubles getting the project running?

**Comment by 255kb** [comment]
I thought about spaces too! 
I just did a quick test and it seems to be working with both JSONPath and object-path (`$.my bucket.prop`). Nice and strange at the same time. 
You can test with the following env:
[sandbox.json](https://github.com/mockoon/mockoon/files/14584728/sandbox.json)

Regarding the version, the project runs with v18 at least. I currently use v20 or even v21 sometimes and it works. Do you get a specific error message?

**Comment by Jerantony** [comment]
Magic!

It seems like packages are not properly installed since I get errors like "Cannot find module "@angular/common" at the step "npm run build:desktop:dev" in the contribution guidelines.

**Comment by 255kb** [comment]
All the deps were update in v7.0.0
I recommend that you remove all the node_modules and reinstall. 
You can run `npx lerna clean && rm -rf node_modules` and then `npm run bootstrap`. Sometimes it's also safer to delete the Angular cache in `./packages/desktop/.angular`.

**Comment by Jerantony** [comment]
Thanks, I'll try that.

**Comment by 255kb** [comment]
@Jerantony Completely unrelated, but I couldn't find another way to reach out to you. We are conducting [short interviews](https://mockoon.com/blog/contributor-spotlight-harry-martland/) of our contributors for our blog and would love to have you too. If you are interested you can reach me on our [Discord](https://mockoon.com/discord/).
