### ISSUE TITLE
Allow data buckets to be reset to their original state via signal (CLI) or endpoint request

### ISSUE THREAD

**Issue by lkrms** [mockoon/mockoon#1339]
_Apologies if this is already being tracked; there is some overlap with #1098 and possibly with #665, but I think this feature has a narrower scope and may be simpler to implement._

I run PHPUnit tests against a Mockoon API and in an ideal world, the data buckets behind each endpoint would be identical at the start of each test. Stopping and restarting `mockoon-cli` dozens of times isn't feasible (the test suite would run slower by an order of magnitude), but there doesn't seem to be any other way of starting each test with a clean slate 😭

If `mockoon-cli` were to reset its data buckets to JSON-supplied values on, say, receiving a `SIGUSR2` signal, or perhaps when it receives a request for a `.well-known` endpoint like `http://localhost:3000/.well-known/mockoon/reset-bucket[?id=unique-id]`, I would be able to write these tests without concerning myself with the order in which they run and/or data changes that may have been made by a previous test.

Thank you for your hard work making Mockoon so useful 🙏🏻

**Comment by 255kb** [comment]
An [admin endpoint](https://github.com/mockoon/mockoon/issues/1334) was added yesterday and will be in the March release. You will be able to call `PURGE /mockoon-admin/state` or `POST /mockoon-admin/state/purge` on any running mock (desktop/cli/serverless) and it will regenerate the data buckets.

To ensure the buckets (or any body template) serves the same content every time, you can [seed Faker.js](https://mockoon.com/docs/latest/templating/fakerjs-helpers/#set-fakerjs-locale-and-seed) in the application settings. There is also a CLI flag. It's the common way to ensure the random data are not so random during the tests. 

Hope this will solve your use case!

**Comment by lkrms** [comment]
Amazing! Thank you!
