### ISSUE TITLE
Keyboard Shortcuts to Export All Environments

### ISSUE THREAD

**Issue by kohchihao** [mockoon/mockoon#134]
**Is your feature request related to a problem?**
Usually, at the end of the day, I would turn off my laptop and I would love to have a keyboard shortcut so that I can quickly export all the environments that I have added that day.

**Describe the solution you'd like**
I was hoping that there could be a keyboard shortcut like <kbd>Cmd</kbd><kbd>Alt</kbd><kbd>S</kbd> to quickly export the environments.

I wouldn't mind doing this small feature! Please suggest other possible keyboard mappings as well if the above isn't suitable.

PS: I've got something working already :)

**Comment by 255kb** [comment]
quick question, what behavior do you expect? 
Shortcut should open the "Save as" dialog, or automatically export to a default file somewhere?

**Comment by 255kb** [comment]
Will resolve this by adding keyboards shortcuts to the menu, for now.
