### ISSUE TITLE
Manipulating global env variables via the CLI or admin API

### ISSUE THREAD

**Issue by myftija** [mockoon/mockoon#1354]
Hi 👋

Great to see the admin API being introduced recently! A suggestion I have is to extend it further by enabling setting global env variables via the API. This would help in cases where one needs to change the mock server behavior at runtime, without restarting the server. Similarly, having an equivalent way to do this via the CLI would be useful too.

Is it something you would consider adding?

**Comment by 255kb** [comment]
That would make sense. And indeed, it's important to have more or less the same features in both the desktop app and the CLI. The admin API seems to be a good candidate for this, also considering that it will let you manipulate/update more things in the future. 
Can't say if and when this will be done though. But I'm always open to external contributions!

**Comment by sakshi4321** [comment]
Hi @255kb can I pick this up?

**Comment by 255kb** [comment]
@sakshi4321 Sure, I will assign this task to you. 
Let me know if you need help during the implementation, but it should be quite straightforward. Updating the [documentation ](https://github.com/mockoon/mockoon.com)too would be really appreciated! 
You can also join our [Discord server](https://discord.com/invite/JmTBk59MTb) if you want to discuss.

**Comment by sakshi4321** [comment]
Hi @255kb, I've encountered an issue with the Discord invite; it appears to be invalid. Could you provide a working link?

Regarding the server functionality, I'm thinking of modifying server.ts to directly manipulate the environment variables. I plan to introduce a public method like this:


```
public setGlobalVariables(key: string, value: any): void {
  this.globalVariables[key] = value;
}
```
This method would be integrated within the createAdminEndpoint like so:

```
createAdminEndpoint(app, {
  statePurgeCallback: () => {
    this.requestNumbers = this.requestNumbers.map(routeUUID => ({ [routeUUID]: 1 }));
    this.processedDatabuckets = [];
    this.generateDatabuckets(this.environment);
  }
}, this.setGlobalVariables);
```
Following this, I'll implement a standard Express endpoint to invoke the function above:

```
app.post('/admin/global-vars', (req, res) => {
  try {
    const { key, value } = req.body;
    this.setGlobalVariables(key, value);
    res.json({
      message: `Global variable '${key}' has been set to '${value}'.`
    });
  } catch (err) {
    console.error(err);
    res.status(400).json({ message: 'Invalid JSON' });
  }
});
```
I'm also using the this.helpers class which contains predefined methods for handling global variables. My question is whether I should update this.globalVariables directly, or should I interact with the variables through the this.helpers methods? is my thinking that this.globalVariables are the environment variables correct? if not please guide me.

**Comment by 255kb** [comment]
Sorry, here is the correct [discord invite](https://mockoon.com/discord/). 

Just to clarify, this ticket is about [global variables](https://mockoon.com/docs/latest/variables/global-variables/) which are different from the OS [environment variables](https://mockoon.com/docs/latest/variables/environment-variables/). We could also manipulate the latter through the admin API, but it should be in another issue/PR.

I agree with your implementation, just be sure to use the correct admin API prefix in the `admin-endpoint.ts` lib for your new POST endpoint. 
I also think that purging the state of the global variables should be in the scope of this PR (it'as already resetting the request counter, and regenerating the data buckets). 

Finally, yes, you are correct you don't need to use the helpers as the `globalVariables` state is stored in the server lib.

**Comment by 255kb** [comment]
📦 This was added in [v8.1.0](https://mockoon.com/releases/8.1.0/)
