### ISSUE TITLE
No logs written in docker container

### ISSUE THREAD

**Issue by johngrimsey** [mockoon/mockoon#1355]
**Describe the bug**

No logs output as per docs:
https://mockoon.com/tutorials/run-mock-api-anywhere-cli/#step-5-view-a-running-mocks-logs

**Steps to Reproduce**

* Use docker image
```
# compose.yml
...
    platform: linux/amd64
    image: mockoon/cli:latest
...
```

* Start a mock server
* Make a request
* Check `/home/mockoon/.mockoon-cli/logs`

Request is logged to STDOUT but no logfiles exist.

**Mockoon version:**

`@mockoon/cli/8.0.0 linux-x64 node-v18.20.0`

**Comment by 255kb** [comment]
Sorry, this is not clear in the tutorial, but file logging is [disabled in the Docker image](https://github.com/mockoon/mockoon/tree/main/packages/cli#docker-image) using the [`--disable-log-to-file` flag in the Dockerfile](https://github.com/mockoon/mockoon/blob/main/packages/cli/docker/Dockerfile).
If you want to enable file logging in a Docker container you will have to create your own Dockerfile.

**Comment by johngrimsey** [comment]
Thanks for the reply - yes wasn't clear in the docs 👍
