### ISSUE TITLE
404 page not adding custom headers

### ISSUE THREAD

**Issue by skunkworker** [mockoon/mockoon#136]
**Describe the bug**
When custom headers are present for a given environment, navigating to a undefined route will show a 404, but this won't include the custom headers that were set beforehand.

I ran into this issue when using https://github.com/axios/axios. I was getting a invalid CORS error for the mocked server, and hunting it down I was able to see that a 404 wasn't including the custom headers.

**To Reproduce**
Add custom headers to an environment.
Navigate to a route that isn't recognized, throwing a 404.

**Expected behavior**
All routes, including invalid ones should return the same custom headers.

**Mockoon version:**
1.4.0

**OS / OS version:**
Mac OS 10.13.6

**Comment by abiodunjames** [comment]
@255kb I would like to pick this. Is that fine for you?

**Comment by 255kb** [comment]
Sure @abiodunjames 
Solution shouldn't be very complicated I think.
Just be careful when handling 404 with ExpressJS, that the proxy mode (and other things) still works. There are tests but not everything is covered yet. So we still need to be careful and test a lot 🙂
And if you can add tests also it would be great (we only add automated tests for now, you can see examples in test folder)
Thank you!
