### ISSUE TITLE
Callback PATCH doesn't work

### ISSUE THREAD

**Issue by BanderasPRO** [mockoon/mockoon#1364]
**Describe the bug**
Callback with PATCH method doesn't work

**Steps to Reproduce**
1. Create a Callback with PATCH method
2. Create a Route 
3. Attach the callback to the route
4. Call the route 
5. Check  Logs

**Expected**
1. The callback invoked
2. Logs has a record with Request/Response the PATCH callback

**Now**
1. Callback is not invoked
2. Logs has no a record with PATCH callback

**Mockoon version:**
8.0.0

**OS / OS version:**
Windows 10

**Comment by BanderasPRO** [comment]
**Additional information**
The PATCH callback actually call CRUD method in same Mockoon. That's why it should appear in the Logs. Other methods PUT/POST/GET work correctly.

**Comment by 255kb** [comment]
Thanks for reporting. 
TIL: The PATCH method is the only method that **needs** uppercasing or it is just refused by Node.js (app logs were showing a status 400).
Will fix for the next release.

**Comment by 255kb** [comment]
📦 This was fixed in [v8.1.0](https://mockoon.com/releases/8.1.0/)
