### ISSUE TITLE
Json validation on beautify

### ISSUE THREAD

**Issue by avollmaier** [mockoon/mockoon#1365]
Currently there is no json validation when beautifying json responses - only a comment that beatification should not occur in the catch

  public formatBody() {
    const activeRouteResponse = this.store.getActiveRouteResponse();

    if (!activeRouteResponse.body) {
      return;
    }

    const contentType = GetRouteResponseContentType(
      this.store.getActiveEnvironment(),
      activeRouteResponse
    );

    if (stringIncludesArrayItems(ParsedJSONBodyMimeTypes, contentType)) {
      try {
        this.activeRouteResponseForm
          .get('body')
          .setValue(
            JSON.stringify(
              JSON.parse(activeRouteResponse.body),
              undefined,
              INDENT_SIZE
            )
          );
      } catch (e) {
        **// ignore any errors with parsing / stringifying the JSON**
      }
    }
  }

**Comment by 255kb** [comment]
Thanks for opening the issue, but I don't think the PR you opened is the right way to improve this. 
Most of the time the body will be invalid as a lot of people are using templating helpers (Handlebars). Having a popup most of the time someone is clicking on this link is not a good improvement. I will close it. 

I'm not sure what is the right way to improve the experience. But I would prefer a more "clever" solution like: 
- beautify the JSON if valid
- if not valid, only do basic indentation of the code 

I didn't find a Handlebars beautifier that could work.
