### ISSUE TITLE
Add search functionality in environment logs

### ISSUE THREAD

**Issue by peawyoyoyin** [mockoon/mockoon#137]
**Is your feature request related to a problem? Please describe.**
I'm using Mockoon to test an HTTP client that sends a large JSON payload in the request body. Sometimes I want to verify some data sent in the request using the environment log. Currently it is a little bit frustrating without a text search function (I have to manually read through the text).

**Describe the solution you'd like**
Provide a text search functionality on the request body in the environment logs.

**Comment by 255kb** [comment]
📦 This was done in [v8.1.0](https://mockoon.com/releases/8.1.0/)
