### ISSUE TITLE
Allow view proxy responses

### ISSUE THREAD

**Issue by gabrielperes97** [mockoon/mockoon#138]
It can be very helpful can view the proxy responses from the environment log. Today I need to look this in my application logs, if I can look this on the environment logs can be more fast and easier.

Add the headers and the body of the reponse in environment logs, where the request are showed, can be solve this.

**Comment by gabrielperes97** [comment]
I want to work with this.

**Comment by 255kb** [comment]
What do you mean by "proxy responses"? 
If I understand correctly, when you activate Mockoon proxy option in environment settings you want to see requests coming from the proxy URL? 
In this case I am not sure that the environment logs tab is the best place to show this. Environment logs are for all **entering** requests not for responses. 
But maybe we could have two tabs in the environment logs: "entering requests" / "proxied responses". 

Be sure to use the store when you add new data and update the reducer behavior for anything related to these new data (tab switching, etc).

**Comment by gabrielperes97** [comment]
You undertand correctly. 

I don't think detach the responses from the log it's the best. In this way we lose the requests "sequence vision", so by the response sequence can be different to request sequence, it be more hard to find the response for that request I need.
My idea is, where today we see the request data (General, Headers, Route Params, Body, etc) we have two tabs ("Request" and "Response"). The Request tab with the actual request data and the Response tab with the proxied response data or the mocked response sended to the client.

What you think?

**Comment by 255kb** [comment]
very good idea, I like it. As you said you would have everything in one place for debug purposes. Entering requests and outgoing responses. So you don't have to check your mocks config.
