### ISSUE TITLE
File serving with relative path not working

### ISSUE THREAD

**Issue by damian-rzeszot** [mockoon/mockoon#1403]
**Describe the bug**

Returning file as a response is not working for relative paths, but for absolute paths it works fine

**Steps to Reproduce**

<img width="1091" alt="Screenshot 2024-06-03 at 13 51 16" src="https://github.com/mockoon/mockoon/assets/1994895/f794a015-1670-4e30-a734-5b1a3a56bdef">

```
$ curl http://localhost:3999/images/GUEST1.png -v
* Host localhost:3999 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:3999...
* Connected to localhost (::1) port 3999
> GET /images/GUEST1.png HTTP/1.1
> Host: localhost:3999
> User-Agent: curl/8.6.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: text/plain; charset=utf-8
< Content-Length: 102
< Date: Mon, 03 Jun 2024 11:58:50 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< 
* Connection #0 to host localhost left intact
Error while serving the file content: ENOENT: no such file or directory, stat '/cdn/images/GUEST1.png'
```

**Mockoon version:**

8.1.1

**OS / OS version:**

macOS 14.5

**Comment by damian-rzeszot** [comment]
Case for absolute path

<img width="1089" alt="Screenshot 2024-06-03 at 13 51 21" src="https://github.com/mockoon/mockoon/assets/1994895/2521f537-53ef-4bf5-ab5f-c863e89dffdf">

```
➜  mockoon curl http://localhost:3999/images/GUEST1.png -v -o /dev/null 
* Host localhost:3999 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying [::1]:3999...
* Connected to localhost (::1) port 3999
> GET /images/GUEST1.png HTTP/1.1
> Host: localhost:3999
> User-Agent: curl/8.6.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: image/png
< Content-Length: 418779
< Date: Mon, 03 Jun 2024 11:49:57 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< 
{ [65536 bytes data]
100  408k  100  408k    0     0  3627k      0 --:--:-- --:--:-- --:--:-- 3619k
* Connection #0 to host localhost left intact
```

**Comment by 255kb** [comment]
I just re-tested relative paths with an image on all operating systems, and it worked as expected. I wasn't able to reproduce your issue, at least not with the information I have.
I added an image in the same folder as you, next to the environment file, and tried several variations with lower case, upper case, etc. 

Could you please double check filenames, location, etc. ? 
Thank you.
