### ISSUE TITLE
Last opened environment not saved if not selected by the user

### ISSUE THREAD

**Issue by 255kb** [mockoon/mockoon#1404]
**Describe the bug**

The last opened environment (see #1396) is not saved if it was not explicitely selected by the user.

**Steps to Reproduce**

Create a new local environment using the environment menu, and close the application.
Environment UUID is not saved in the settings. 

**Mockoon version:**

8.2.2

**OS / OS version:**

all

**Comment by impeas** [comment]
Hey @255kb, you can assign it to me if possible 🏃

**Comment by 255kb** [comment]
@impeas Here you go! :)

**Comment by 255kb** [comment]
📦 This was fixed in [v8.4.0](https://mockoon.com/releases/8.4.0/)
