### ISSUE TITLE
Implements custom URL protocol `mockoon://`

### ISSUE THREAD

**Issue by 255kb** [mockoon/mockoon#141]
In order to easily import data in Mockoon having a custom protocol would be great. 

https://electronjs.org/docs/api/protocol

**Comment by zalizko** [comment]
I didn't found more suitable issue maybe, but is there is possible to customize host?

**Comment by 255kb** [comment]
@zalizko Indeed, this question is not related to this issue, please use the [community chat](https://spectrum.chat/mockoon) for all general questions or help requests not directly related to a Github issue 👍 
Concerning your question, the host cannot be customized yet. Mockoon already listens to most local adapters so your mock server is available on localhost, 127.0.0.1, 192.168.x.x, etc
Concerning hosts modification, there was an issue opened several months ago. https://github.com/mockoon/mockoon/issues/67
However, Mockoon's goal is to stay simple, so I decided to not implement this request. I am not sure it should be Mockoon's responsibility to mess with OS' hosts file. But if there is more interest for this feature, I may consider it.
