### ISSUE TITLE
Responses based on rules depends on the order I add them

### ISSUE THREAD

**Issue by qiulang** [mockoon/mockoon#1420]
**Describe the bug**

I have the response A based on two rules, say rule 1 & rule 2 and the response B based on rule 1. When I send the request with both rules satisfied I will get either response A or B depends on the order I give to them.

**Steps to Reproduce**
I attach the configuration json at the end, here I just attach the rules in picture for easy illustration.

The response 2 has 2 rules, one for customer header and one for query string. The response 3 has one rule for customer header.

![response A](https://github.com/mockoon/mockoon/assets/516243/2e91f7ae-349c-4bdb-a9fd-31ec22d853e7)

The 2 rules
![2 rules](https://github.com/mockoon/mockoon/assets/516243/78e3a15b-b33c-4748-83f4-5d962c4d5a95)

When I send a request with the 2 rules satisfied, I will get the response 2 only if I put response 2 before response 3. 

But that apparently is not reasonable.

[bug.json](https://github.com/user-attachments/files/15879835/bug.json)

**Mockoon version:**

8.2

**OS / OS version:**

MacOS

**Comment by 255kb** [comment]
What you are describing is [how it should work](https://mockoon.com/docs/latest/route-responses/dynamic-rules/). The rules are evaluated in the order your responses are displayed. So, first set of rules to match, first response to be served. 

I see nothing wrong in your setup, only that you have the same rule in response 1 and 3.

**Comment by qiulang** [comment]
Thanks for the reply.
I had read the document you referred to when I open the issue. But the problem if I send I a request that can match 2 rules, in my case, one is customer header and the other is query string, the response A only sets for the customer header, while the response B sets for the customer header and the query string. I definitely want to get  the response B instead of the response A.

BTW the response 1 and 3 are not the same, 1 is 403 for the customer header **not** equal to xxx, while 3 is 200 for the customer header equal to xxx.

**Comment by 255kb** [comment]
I'm not sure which is response A and which is reponse B, but if you have a conflicting rule the first one in the list will will. 

If it's only a matter of customizing the response, I suggest that you use something like: 
```handlebars
{{if (eq (queryParam 'remote_address') '127.0.0.1')}}
...
{{/if}}
```

**Comment by qiulang** [comment]
As my json shows, the response A(response 2 in my picture) has 2 rules

```
          "rules": [
            {
              "target": "header",
              "modifier": "source",
              "value": "server.tcp",
              "invert": false,
              "operator": "equals"
            },
            {
              "target": "query",
              "modifier": "remote_address",
              "value": "127.0.0.1",
              "invert": false,
              "operator": "equals"
            }
          ],
          "rulesOperator": "AND",
          "disableTemplating": false,
          "fallbackTo404": false,
          "default": false,
          "crudKey": "id",
          "callbacks": []
```

The response B (response 3) has 1 one rule, the first rule in  response 2,

```
          "rules": [
            {
              "target": "header",
              "modifier": "source",
              "value": "server.tcp",
              "invert": false,
              "operator": "equals"
            }
          ],
```

When I send a request that can match 2 rules, I would like to get response 2. But now it depends on the order I add for response 2 and 3.

If you say this is by design, I think it is better to say it clearly in the document. The current document only says "By default, rules are interpreted in the order you added them. You can change their interpretation order by drag and dropping them", which is actually not about my problem here.

But I still hope I can get response 2 no matter it is put before or after response 3 when I send a request that can match 2 rules.

**Comment by 255kb** [comment]
We decided to evaluate the response/rules in the order they are displayed in the menu, so, it's predictable. I think this is perfectly clear from the documentation that you only partially copied: "At each request, Mockoon will assert each response's rules and serve the response which contains the first matching rule(s). The rules are interpreted in the order they are declared"

Also, the two sets of rules are not equivalent as the first one is an AND and not an OR. So, if you send the following request:

```text
GET /path
source: server.tcp
```

it will not match the response A's rules as they also expect a Query parameter rule `remote_address==127.0.0.1`.

There is no bug here, or nothing that we would like to change in a near future.
