### ISSUE TITLE
Add Locking To Routes During Recording

### ISSUE THREAD

**Issue by BenHesketh21** [mockoon/mockoon#1425]
The recording functionality is so close to being extremely useful. At the moment it seems that if an endpoint is called twice in a recording, it is overridden with the new response, so I think theres an argument to be made about making new responses instead but one thing I thought of; We have a login/account/register endpoint that I set certain rules to work, I thin it would be useful to be able to "lock" those routes so the aren't overridden while recording.

**Comment by 255kb** [comment]
It's already working like you describe. When the recording mode is enabled, it will create a new HTTP route if none exist yet (method + path). If it already exists, it does nothing. 

The manual "Create mock endpoint" action will create the route no matter what. 

![image](https://github.com/mockoon/mockoon/assets/7489814/a9529a70-efa2-42f7-a25d-8fdb406a6d01)
