### ISSUE TITLE
CRUD routes: Add support for dot notation in the CrudKey property

### ISSUE THREAD

**Issue by 255kb** [mockoon/mockoon#1433]
## Problem

Currently CRUD routes are manipulating items based on a `crudKey` (by default `id`) expected to be at the root level of an object:

```json
[
  {
    "id": "abcd"
  }
]
```

This does not allow complex data to be used in a data bucket, for example, something with a wrapper: 

```json
[
  {
    "data": {
      "id": "abcd"
    }
  }
]
```

## Solution 

Add support for the dot notation in the crudKey field: 

![image](https://github.com/mockoon/mockoon/assets/7489814/ab48b721-cda3-4f2e-9364-74044a64dca8)

This support should be added everywhere the crudKey is used to manipulate an array element: `GET /res/:id`, `PUT /res/:id`, etc.

**Comment by LukMas** [comment]
Super, thank you!
