### ISSUE TITLE
Support Javascript as a templating language

### ISSUE THREAD

**Issue by digicide** [mockoon/mockoon#1435]
In some cases producing dynamic responses with Handlebars is cumbersome. This can be especially true when creating JSON responses, where you are manually managing things like commas.

Javascript is better suited to this task. The full power of JS scripting is available to assemble an object, and then it can simply be stringified to produce the response.

Existing Handlebars helpers can be bridged so that they can be directly invoked from javascript, but maintained as a single collection as they are now, providing the full capability of Mockoon's templating to JS in addition to Handlebars.

The Handlebars templating library can also be exposed to Javascript, enabling custom helpers to be added, addressing #445 .

**Comment by 255kb** [comment]
Closing for now as probably a bit too risky, after exploring some possibilities in a PR. 
We will see if this gathers more interest and if more secure solutions are available.

**Comment by HQidea** [comment]
Both gpt-4o and deekseek tell me mockoon supports Javascript, util I found this issue.

**Comment by 255kb** [comment]
> Both gpt-4o and deekseek tell me mockoon supports Javascript, util I found this issue.

Key takeaway: never trust LLMs! 

![Image](https://github.com/user-attachments/assets/f8306a27-7359-4018-a128-905b00345e71)
