### ISSUE TITLE
Add an "array includes" rule

### ISSUE THREAD

**Issue by 255kb** [mockoon/mockoon#1444]
## Problem

It's currently not possible to check in rules that an array (in a bucket, or in the body) includes a specific value. 

## Solution

Add a new "Array includes" rule that will check if an array contains a specific value. It could revert to equals if the provided target is not an array.

**Comment by ajatkj** [comment]
I can look into this if it's alright.

**Comment by 255kb** [comment]
Sure, I assigned it to you. 
Please note that this feature needs a major release, which is planned around mid-August (it will also include websocket). After that, I'm not sure when the next major release will be.

**Comment by 255kb** [comment]
> I reckon changes are also required on the website to update documentation:

Yes indeed 👍

**Comment by 255kb** [comment]
📦This was released in [v9.0.0](https://mockoon.com/releases/9.0.0/)
