### ISSUE TITLE
Add the ability to create and edit an API itself within Mockoon

### ISSUE THREAD

**Issue by broomhandleus** [mockoon/mockoon#145]
Mockoon takes an API that is live and mocks out responses in a great way, but my current use case is mocking an API that doesn't exist yet. I get to define the API and having an interface in Mockoon to build an API would also be great! That way I could fulfill everything I need in just one application! The program I am using now is Apicurio, so you can go look at their site to see what I am referring to if my explanation was not descriptive enough. Thanks so much!

**Comment by 255kb** [comment]
There is currently no plan to transform Mockoon in a full API design tool like Apicurio or Stoplight are doing. It's a lot of work and I think goes in a very different direction (quick prototyping / mocking vs complete API design with models, etc).
However, it will soon be compatible with [OpenAPI format (import/export)](#86), so it will be a complementary tool with API design services.
