### ISSUE TITLE
How moockon identify changes in envirornment file.

### ISSUE THREAD

**Issue by dharma412** [mockoon/mockoon#1450]
### Discussed in https://github.com/mockoon/mockoon/discussions/1449

<div type='discussions-op-text'>

<sup>Originally posted by **dharma412** July 17, 2024</sup>
Scenario:

Step1:
I have imported Open API spec file and made chnages to one GET oprtation with custome response. On running via CLI i am able to get response .

Step2: while mockoon is running I have made one more change to same GET operation with new response , But mockoon is giving old response not the new response.

I observ one mockoon is not update new changes made in environment file.

Note: started mockoon via mockoon-cli starrt --data  file.json and hitting end point via Postman.</div>

**Comment by 255kb** [comment]
Please keep this repository clean and avoid opening discussions twice.
