### ISSUE TITLE
Request payload validation

### ISSUE THREAD

**Issue by sebastien-savalle** [mockoon/mockoon#1452]
### Discussed in https://github.com/mockoon/mockoon/discussions/1434

<div type='discussions-op-text'>

<sup>Originally posted by **sebastien-savalle** June 29, 2024</sup>
Hi,

Mockoon is a very useful tool for prototyping and to run tests when we don't have access to remote system.
Sometimes, we have integration issues because we are validating requests have been correctly sent to mockoon and the response is valid. But, we are validating the request payload sent to mockoon.

I would like to ensure that the request body is valid, and optionally return a bad request when this is not compliant with a given schema.
I would be nice to integrate AJV for example. https://ajv.js.org/

What do you think ?
Regards,
Sebastien</div>

**Comment by ajatkj** [comment]
Hi @255kb could you please assign this to me?

**Comment by 255kb** [comment]
Note: this will take the form of a new [response rule](https://mockoon.com/docs/latest/route-responses/dynamic-rules/) operator "Valid JSON schema", checking against a JSON schema stored in a data bucket. This allows us to reuse existing features.

**Comment by 255kb** [comment]
📦This was released in [v9.0.0](https://mockoon.com/releases/9.0.0/)

**Comment by 255kb** [comment]
> Request always returns the default response not the Bad Request with the rule. Am I missing something or is it just not working?

No you are not missing anything, but leaving the path empty doesn't work. It's not really a bug, rather an artifact from the past. It will be [fixed in v9.1.0](https://github.com/mockoon/mockoon/issues/1595). 
As a workaround you can use JSONPath `$`: 
![image](https://github.com/user-attachments/assets/33975671-1710-4bc8-a4bd-d3e01c336536)
