### ISSUE TITLE
Update oclif dependencies to patch lodash.template vulnerability

### ISSUE THREAD

**Issue by TCezarRod** [mockoon/mockoon#1469]
The `cli` package includes a vulnerable version of `lodash.template` (see https://github.com/advisories/GHSA-35jh-r3h4-6jhm)

The vulnerable version (`lodash.template@4.5.0`) is included via the `oclif` dependencies (`oclif`, `@oclif/plugin-help`, etc.). 

Both the `lodash` as well as the `oclif` packages have more recent versions that patched the vulnerability, but our `@mockoon/cli` have the oclif versions locked, and should be updated.

**Comment by TCezarRod** [comment]
I can work on that update, by the way, if that is okay.

**Comment by 255kb** [comment]
Thanks for reporting @TCezarRod and contributing! I've assigned the issue to you. 
I plan to do a small release in the coming days (next one will be end of September), the fix could be part of it.

**Comment by TCezarRod** [comment]
That's perfect @255kb , thanks a lot!

I've just opened the PR, then. Thanks for the quick response.

**Comment by 255kb** [comment]
📦 This was released in [v8.4.0](https://mockoon.com/releases/8.4.0/)
