### ISSUE TITLE
Support path parameters for websocket routes

### ISSUE THREAD

**Issue by isuru89** [mockoon/mockoon#1495]
Currently the WebSocket routes don't support named path parameters like in express routes. (e.g `/path/:var1/segment/:var2`). Because of this, only alternative is to use query parameters.

It is important to support these path parameters, so that it will make easier to use rules using those named variables and generate responses accordingly.

It should be possible to introduce same mechanism used in express.js to the Websockets using the same library.

**Comment by 255kb** [comment]
📦This was released in [v9.0.0](https://mockoon.com/releases/9.0.0/)
