### ISSUE TITLE
Import / Export / Replace environment

### ISSUE THREAD

**Issue by electerious** [mockoon/mockoon#151]
**Is your feature request related to a problem? Please describe.**
All our projects should contain an environment file that mocks the API of the back-end and allows us to develop the front-end while the back-end isn't ready.

**Describe the solution you'd like**
I would like to export / import / replace a single environment. It's currently only possible to import / export all environments at once.

**Comment by 255kb** [comment]
For the replace feature it does not exist yet, but you can definitely export / import one environment and even one route.  You can right click directly on each environment in the list and select "Copy to clipboard". 
Then "import from clipboard" in the app main menu. It's not optimal yet but I think it should do the trick and solve your problem.
Please note that file import / export is not compatible with clipboard import / export feature. But there is already a ticket to improve this #102
