### ISSUE TITLE
App crash in Ubuntu 22.04.5

### ISSUE THREAD

**Issue by ARiyou2000** [mockoon/mockoon#1526]
**Describe the bug**

Any interaction with the app that needs writing data to the JSON file of the environment will lead to an app crash. 
![Screenshot from 2024-09-27 16-25-15](https://github.com/user-attachments/assets/d54d78fe-d24d-4a2a-b161-a6ff74f8ea61)

**Steps to Reproduce**
Update mockoon using snap.
try creating a new environment or change anything of an existing environment.

**Mockoon version:**

8.4.0

**OS / OS version:**

Linux Ubuntu 22.04.5

**Comment by ARiyou2000** [comment]
After updating to Ubuntu 24.04 the problem resolved.

**Comment by 255kb** [comment]
> After updating to Ubuntu 24.04 the problem resolved.

Great! Honestly it's the first time this issue got reported and I couldn't replicate it in my Ubuntu install which is v22. I will close it for now and see if more people are affected.
