### ISSUE TITLE
Show the number of available response per route

### ISSUE THREAD

**Issue by ARiyou2000** [mockoon/mockoon#1528]
It would be awesome if the number of responses would be shown for each route since as of now there is no way you would know how many responses are there until you open the response list. a number indicator next to the open list button would suffice.

![reorder-responses3](https://github.com/user-attachments/assets/c8b2a025-27cb-4c4d-b613-2e8a9c579417)

**Comment by 255kb** [comment]
I like the idea, I think it makes sense considering there is already a lot of counters elsewhere. Also, it's a very quick thing to do. I will add it for the next release.

**Comment by 255kb** [comment]
📦This was released in [v9.0.0](https://mockoon.com/releases/9.0.0/)
