### ISSUE TITLE
Enable CRUD route ids auto increment

### ISSUE THREAD

**Issue by 255kb** [mockoon/mockoon#1542]
CRUD routes automatically add UUIDs when missing during a Create action (`POST /resources`). It could be convenient that it detects the presence of numeric ids in the data bucket and increment new ones automatically. 

This would enable the use of numeric ids without adding anything to the UI. The only constraint would be the presence of at least one object with a numeric id in the data bucket's (array).

**Comment by kaaapi** [comment]
This is a great feature add! Just a thought, can this feature be extended to use a templating expression (provided in CRUD Route > Data > ID UI) with a simple built-in helper like faker.js library? For e.g. `{{faker 'database.mongodbObjectId'}}`.

**Comment by 255kb** [comment]
> This is a great feature add! Just a thought, can this feature be extended to use a templating expression (provided in CRUD Route > Data > ID UI) with a simple built-in helper like faker.js library? For e.g. `{{faker 'database.mongodbObjectId'}}`.

The idea of this improvement was to avoid any UI addition to the UI. But I think your idea is good and could be done in the future. 
Maybe open a new issue to see if it gathers some interest?

**Comment by 255kb** [comment]
📦This was released in [v9.0.0](https://mockoon.com/releases/9.0.0/)
