### ISSUE TITLE
Introduce environment variables across request to be used as parameters

### ISSUE THREAD

**Issue by ascarnecchia** [mockoon/mockoon#158]
**Is your feature request related to a problem? Please describe.**
I need a change executed in a PUT/POST request to be reflected into an subsequent GET request. (e.g. setFlag to true via PUT, then getFlag via GET returns true)

**Describe the solution you'd like**
It would be awesome to define variables at environment scope to be used in request calls and that persist their current values between a request and the subsequent one. For example, i define the FLAG variable; the endpoint "setFlag" sets the FLAG variable to true, then the endpoint "getFlag" can use the FLAG parameter in templating (e.g. {{ envVariable 'FLAG' }} )

**Comment by 255kb** [comment]
This should be covered by the [CRUD routes](https://github.com/mockoon/mockoon/issues/124) I am currently working on. 
They will support CRUD operations, get, get by id, put, post, patch, delete and work for arrays, objects, and primitives. So, you will be able to set booleans through calls and access them everywhere templating is supported using the `{{data}}` helper.
