### ISSUE TITLE
Faker alias interferes with local variable name

### ISSUE THREAD

**Issue by WouterCypers** [mockoon/mockoon#1587]
**Describe the bug**

This problem occurs when accessing a local variable that has the same name as an alias for a Faker method using the shorthand `@` accessor. Instead of returning the local variable's value, the Faker method is invoked.

**Steps to Reproduce**

The following template does not output "John", but a random name:
```hbs
{{~setVar 'firstName' 'John'~}}
{{@firstName}}
```

Environment file: [issue-faker-alias-interference.json](https://github.com/user-attachments/files/17751641/issue-faker-alias-interference.json)

The issue can be circumvented by using `getVar` (or using a different variable name):
```hbs
{{~setVar 'firstName' 'John'~}}
{{getVar 'firstName'}}
```

**Mockoon version:**

9.0.0

**OS / OS version:**
macOS 15.1

**Comment by 255kb** [comment]
This is indeed an issue with all the helpers, not only the Faker aliases. 
I'm not sure this should be fixed, and the only solution would be to prefix all the existing helpers (`ip` -> `request.ip`, `firstName` -> `helper.firstName`, etc.). But this is a massive change and as you said, you can circumvent this by using `getVar`. 

I will close for now, but would be happy to revisit if there is more interest.
