### ISSUE TITLE
"zipcode" stalls data bucket content generation

### ISSUE THREAD

**Issue by WouterCypers** [mockoon/mockoon#1589]
**Describe the bug**

Using the Faker.js alias `zipcode` inside a data bucket will stall generation of content in that data bucket. The data bucket will only generate its contents when a route that uses the data bucket is called. This is especially problematic when using the admin API to retrieve the contents of a data bucket _**before**_ making requests to the mock's routes.

**Steps to Reproduce**

1. Create a data bucket with name `myDataBucket` and the following content:
```hbs
{
  "zipcode":"{{zipcode}}"
}
```

2. Retrieve the data bucket contents using the admin API:

```bash
curl --location 'http://localhost:3004/mockoon-admin/data-buckets/myDataBucket'
```

3. This results in the following output:
```json
{
    "name": "myDataBucket",
    "id": "4g39",
    "value": "{\n  \"zipcode\":\"{{zipcode}}\"\n}"
}
```

Environment file: [issue-zipcode-data-bucket.json](https://github.com/user-attachments/files/17773919/issue-zipcode-data-bucket.json)

**Mockoon version:**

9.0.0

**OS / OS version:**

macOS 15.1

**Comment by 255kb** [comment]
📦This is fixed in [v9.1.0](https://mockoon.com/releases/9.1.0/).
