### ISSUE TITLE
Allow syncing on environments using cloud services by changing data folder

### ISSUE THREAD

**Issue by bhagatparwinder** [mockoon/mockoon#16]
Having a sync feature similar to Postman would be nice. Two approaches:

- Google login and sync on Mockoon servers or
- Allow using Dropbox/Google Drive

**Comment by pflima92** [comment]
Also @255kb the Postman itself could be an amazing feature. For while I can't contribute, but I'll try in a near future. =)

**Comment by 255kb** [comment]
Syncing on Mockoon's own servers is part of a long term plan which goal is to offer paid services (app will stay free and open source, but things that incur a cost like online sync will be paid). But this won't happen before a long time. 

So, as a workaround, and also to offer more options, I suggest that I make sharing/syncing through Drive or Dropbox easier by allowing users to specify the folder where Mockoon stores the data.

**Comment by amjd** [comment]
@255kb I'm also very interested in this feature. I know it's in the roadmap, but is there any chance that you have planned any timelines around it?

**Comment by 255kb** [comment]
Sorry, no ETA for now. I am currently working on the CLI, and some changes may be required that directly impact this ticket or even solve it.

But I would said end of the year or early next year is reasonable.
