### ISSUE TITLE
WebSocket hanging when an API prefix is defined

### ISSUE THREAD

**Issue by 255kb** [mockoon/mockoon#1612]
**Describe the bug**

When an API prefix is defined, the connections to WebSocket endpoints hang indefinitely.
It seems to hang whenever there is no WS defined on the endpoint. And thus, the WS seem to be defined without API prefix.
(Tried with multiple clients)

**Steps to Reproduce**

- create a ws route
- add an API prefix
- try to connect

**Mockoon version:**

>=8

**OS / OS version:**
 
all

**Comment by BenediktBeigang** [comment]
@255kb I observed the same behaviour on version 9, for the environment prefix and the route prefix.

**Comment by 255kb** [comment]
📦This is fixed in [v9.1.0](https://mockoon.com/releases/9.1.0/).
