### ISSUE TITLE
Mockoon Data file as YAML

### ISSUE THREAD

**Issue by alexbaeza** [mockoon/mockoon#1616]
I'd lke to propose that the mockoon data file has the ability to be exported as a YAML format
So that we can have more readable and editable files, and feed these files via the mockoon cli.

The current data file get's exported as a JSON file, while most developers will be familiar with escaped JSON strings I think it can make it difficult to read and easier to make mistakes if updating the file directly.

Examples:
This is a reduced version of the mockoon data file.

`JSON`

```
{
  "uuid": "97575d5d-fc20-4f65-923c-813e4980ce3d",
  "lastMigration": 33,
  "name": "Book Test Api",
  "endpointPrefix": "api",
  "latency": 0,
  "port": 3000,
  "hostname": "",
  "routes": [
    {
      "uuid": "6ec28b67-b10a-4171-bb47-ea0cd6ebd421",
      "type": "http",
      "documentation": "",
      "method": "post",
      "endpoint": "books",
      "responses": [
        {
          "uuid": "d97dfc23-96ed-4634-b5be-66327f57e8c2",
          "label": "Invalid book id",
          "latency": 0,
          "statusCode": 400,
          "rulesOperator": "OR",
          "rules": [
            {
              "target": "body",
              "modifier": "id",
              "value": "invalid-book-id",
              "invert": false,
              "operator": "equals"
            }
          ],
          "headers": [],
          "bodyType": "INLINE",
          "body": "{\n  \"timestamp\": \"2024-11-22T13:02:52.311+00:00\",\n  \"status\": 400,\n  \"error\": \"Bad Request\",\n  \"path\": \"/books\"\n}"
        },
        {
          "uuid": "256c3958-1a31-4dae-baad-8e63b68bdf74",
          "label": "Successful book response",
          "latency": 0,
          "statusCode": 201,
          "rulesOperator": "OR",
          "rules": [],
          "headers": [
            {
              "key": "content-type",
              "value": "application/json"
            }
          ],
          "bodyType": "INLINE",
          "body": "{\n  \"id\": \"{{body 'id'}}\",\n  \"name\": \"{{body 'name'}}\",\n  \"title\": \"{{body 'title'}}\",\n  \"_links\": {\n    \"self\": {\n      \"href\": \"http://mockoon:3001/books/{{body 'id'}}\"\n    }\n  }\n}"
        }
      ]
    }
  ]
}

```

`YAML`
```
uuid: 97575d5d-fc20-4f65-923c-813e4980ce3d
lastMigration: 33
name: Book Test Api
endpointPrefix: api
latency: 0
port: 3000
hostname: ''
routes:
  - uuid: 6ec28b67-b10a-4171-bb47-ea0cd6ebd421
    type: http
    documentation: ''
    method: post
    endpoint: books
    responses:
      - uuid: d97dfc23-96ed-4634-b5be-66327f57e8c2
        label: Invalid book id
        latency: 0
        statusCode: 400
        rulesOperator: OR
        rules:
          - target: body
            modifier: id
            value: invalid-book-id
            invert: false
            operator: equals
        headers: []
        bodyType: INLINE
        body: |-
          {
            "timestamp": "2024-11-22T13:02:52.311+00:00",
            "status": 400,
            "error": "Bad Request",
            "path": "/book"
          }

      - uuid: 256c3958-1a31-4dae-baad-8e63b68bdf74
        label: Successful book response
        latency: 0
        statusCode: 201
        rulesOperator: OR
        rules: [ ]
        headers:
          - key: content-type
            value: application/json
        bodyType: INLINE
        body: |-
          {
            "id": "{{body 'id'}}",
            "name": "{{body 'name'}}",
            "title": "{{body 'title'}}",
            "_links": {
              "self": {
                "href": "http://mockoon:3001/books/{{body 'id'}}"
              }
            }
          }
```

Furthermore, this may be for another request but I'd also like to suggest the ability to  be able to configure a mock api with very minimal YAML configuration, so that we can quickly produce data files without having to configure them via the GUI. 
If it does require extra configuration to be able to configure the new mock API I think we could default all the missing configuration.

Example:

`POST /books` minimal API
```
name: Book Test Api
endpointPrefix: api
port: 3000
routes:
  - type: http
    method: post
    endpoint: books
    responses:
      - label: Successful book response
        statusCode: 201
        headers:
          - key: content-type
            value: application/json
        bodyType: INLINE
        body: |-
          {
            "id": "{{body 'id'}}",
            "name": "{{body 'name'}}",
            "title": "{{body 'title'}}",
            "_links": {
              "self": {
                "href": "http://mockoon:3001/books/{{body 'id'}}"
              }
            }
          }
```

Thank you <3 Love Mockoon

**Comment by 255kb** [comment]
> Thank you <3 Love Mockoon
<3

Thank you for the proposition but I think I will politely decline for multiple reasons: 
- I'm not very fond of the users tampering with the JSON files. There are some strict rules in the data and some dependencies. While it's possible (but this was never something that I did on purpose), it generates more support requests, and it's not something that is documented. It would require more documentation and more safeguards when loading the files. 
- I don't think YAML solves anything aside from the multiline body part. It's an aweful format IMO, but it's probably a personal preference.
- It's tempting to add each and every feature requests, but the more features we add, the more maintenance it is for me (because Mockoon is still mostly me) and the more interactions there are between all the features. 

I usually let issues open, to see if they gather interest, but I don't want to send the wrong signal, so I will be closing it for now. 
I would be happy to reconsider in the future if there is some interest.

Side note: you can already create a partial JSON file and load it. It should be "repaired" and the missing part added.
