### ISSUE TITLE
queryParam with dot property Status & Body and File

### ISSUE THREAD

**Issue by christophebouchard** [mockoon/mockoon#1623]
**Describe the bug**
When I request an API with queryParam and dots in the properties names I can't get the response. The replacement of {{queryParam 'prop1\.prop2\.prop3'}} does not work. I get the response below:
Error while serving the file content: ENOENT: no such file or directory, open '/Users/..../data/reponse_.json'

**Steps to Reproduce**
Unzip data.zip in order to get files to serve
Put testPropertyWithDots.json at the same level of the folder "data"
Start the mock
curl -X GET "http://localhost:3000/test?prop1.prop2.prop3=123"
Response
Error while serving the file content: ENOENT: no such file or directory, open '/Users/..../data/reponse_.json'% 

**Mockoon version:** 8.4.0

**OS / OS version:** Mac OS 15.1.1

[testPropertyWithDots.json](https://github.com/user-attachments/files/18012065/testPropertyWithDots.json)

[data.zip](https://github.com/user-attachments/files/18012088/data.zip)

**Comment by 255kb** [comment]
📦This is fixed in [v9.1.0](https://mockoon.com/releases/9.1.0/).
