### ISSUE TITLE
Offer more Linux distribution options

### ISSUE THREAD

**Issue by 255kb** [mockoon/mockoon#163]
**Is your feature request related to a problem? Please describe.**
Currently only offering AppImages

**Describe the solution you'd like**
Electron builder latest versions offer more options for Linux, need to investigate which one should be offered to users

**Additional context**
This is blocked by #162

**Comment by Giancarlos** [comment]
Is Electron Builder a reasonable option for this?

https://github.com/electron-userland/electron-builder

**Comment by 255kb** [comment]
Yes, indeed we are already using electron builder. But it needs to be update to the latest version which offers more distribution options for Linux. Like Snap which is the default build format now. 
Fact is I am not very familiar with the Linux ecosystem I didn't even know that such an app store existed. 
So first step is to update to electron builder latest version in #162, but keep binaries as is. 
Then investigate and gather feedback on which binaries would be useful for Linux aside from AppImage. 
If you have any idea feedback is welcome :)

**Comment by Giancarlos** [comment]
Oh I had no idea, I'm only just now using this project after keeping my eye on it. I use Ubuntu, and while individual packages are great the AppImage works just fine for me, but I wanted to look into it and provide any meaningful feedback I could add. I think the major packages I usually see are .deb and .rpm usually. I am always ok with AppImage as an option, it's very trivial to use usually.

I can't speak for users of other Linux Distros though. I'll be sure to try any Debian packages produced and report any issues though.

**Comment by 255kb** [comment]
I saw that adding the app to the Snap app store seems really easy. So I will probably support it very soon especially if Electron Builder does most of the work. 
Concerning `deb` and `rpm` Electron Builder can create the binaries too but I am not sure how to add them to a repository (is this even needed?)

**Comment by Giancarlos** [comment]
You dont need to necessarily have them in a repository with a deb or rpm file you can manually install it once you download each file.


Snap isnt too bad though and wouldnt hurt as an option but I know some people will still prefer to just use DEB or RPM files.

**Comment by 255kb** [comment]
Ok good to know.
Apparently it's just a matter of adding two binaries types in the configuration.
I will do it for the next release and also try to add Snap.
Thank you for the feedback!
