### ISSUE TITLE
Add possibility to collapse environment menu

### ISSUE THREAD

**Issue by 255kb** [mockoon/mockoon#173]
**Is your feature request related to a problem? Please describe.**
Environment menu may not be used as frequently as the rest of the interface. Majority of users only have 1 environment.

**Describe the solution you'd like**
Allow users to collapse the environment menu

**Comment by JoshMLeslie** [comment]
Hey would it be alright if I took this one on?

For some reference of my work you can [check out my portfolio site](https://github.com/JoshMLeslie/portfolio)

**Comment by 255kb** [comment]
Hi @JoshMLeslie , of course it's alright. Thank you :) 
A little help is always appreciated! 

Concerning the implementation itself, I didn't write any specification in this issue. 
So, to clarify, and be sure we are talking about the same thing: environment menu is the first column on the left with the list of environments (which is taking full viewport height).  
Also, I think we should:
- update the collapsed state of the environment menu through the store / reducer (it's already the case for `activeTab` or `activeView` so you can easily replicate, but this variable should be in the `settings` property of the store)
- save the collapsed state in the settings file. It's not the case for other UI states (like `activeTab` or `activeView`) but I think this one is more important, and the users should be able to have this state back when they reload the app. It should be as simple as calling the reducer UPDATE_SETTINGS action with a new param. Saving to the settings file is already automatic and implemented.
- avoid basic implementation like animating `width` which will make the content move weirdly while resizing.

Concerning the code itself, please do not forget to type everything (don't use any `any` :) ). 
Bonus: if you can cover with a new test, at least to test if it's collapsing/opening after a click that would be great. No need to test that it's saved in the settings file (except if you really want, which would require the use of https://github.com/chaijs/chai-fs I think).

Thank you for contributing!

**Comment by JoshMLeslie** [comment]
That all sounds good! I do have a question though, how would you feel about extracting the Environment menu into its own component / module?

**Comment by JoshMLeslie** [comment]
Alright I'll bite @255kb. I've racked my brain for awhile on this one - How should I be changing the css / html without modifying the width property?

**Comment by 255kb** [comment]
@JoshMLeslie I thought about it also. Honestly I don't know. Probably transitioning the width is good enough. However, I would like to avoid a too slow transition which would make the text wrapping progressively (and visibly). So maybe a short transition, or first fade out the content before collapsing the width.
What do you think?

**Comment by JoshMLeslie** [comment]
I came to the same conclusion @255kb :+1:

**Comment by 255kb** [comment]
Good idea, a sliding menu could be better actually. 
Routes menu + main content would take the full width, minus some padding left on the route menu to acknowledge for the clickable sliding menu border / button. 
And sliding menu would be absolute and translateX when class is applied (or with angular animations). That would ensure great performances. 
For the "button" used to collapse/show the menu I would prefer a full vertical "gap" + a button maybe, like Jira does: 
https://confluence.atlassian.com/jirasoftwarecloud/files/937886040/961270695/1/1542151836578/NavigationFlyout.gif
Not that I like Jira 😅 but I think the result is nice.

**Comment by JoshMLeslie** [comment]
@255kb 
Sorry this has taken so long! Work and life, you know.

This is what I have so far. What do you think about the right-edge inset shadow when the menu is open to break the edge? it's `$gray-400`

### Open
![image](https://user-images.githubusercontent.com/30437767/68054968-f3c45d00-fcc5-11e9-963f-f70ae8d38e5f.png)

### Closed
![image](https://user-images.githubusercontent.com/30437767/68054976-faeb6b00-fcc5-11e9-87b2-48c6cb5c53f9.png)

**Comment by 255kb** [comment]
Thank you @JoshMLeslie for your hard work! It looks nice 😃 
I am sorry, I don't have much time in the coming days to review (taking a new job) but I will. Feel free to open a PR as soon as you are ready, or even if it's WIP. 
From what I saw on your branch, I have 3 remarks: 
- Couldn't we store the `environmentsMenuState` in the settings property of the store only? It has the same behavior anyway. Having this as a root property of the store and as a settings' property feels redundant to me. What do you think?
- When the menu is open, I have the sentiment that the "spreading" box shadow does not match the style of the rest of the application. For example, the "active" state of a menu item is an inset box shadow with 0 spread and something like 2-3 pixel. I would have thought more of a similar greyish inset box shadow with no spread. 
- Please rebase on master branch as I had to correct the layout after the update to Electron 6. Commit explains a little bit more what happened but in short, Chrome version 73 fixed a bug with flex columns. Apparently the bug was causing the layout to work well (😄) so I had to correct it with some `min-height: 0` fix and `h-100` classes, after the bug was fixed. How to test: add a lot of envs, routes, route rules, route headers, env headers, env logs, etc and see if each scroll well. Bug was causing elements to overflow and pushing the footer with no scroll at all. (Don't worry I will also test)

Thank you again!
