### ISSUE TITLE
Duplicated route shares file with origin route

### ISSUE THREAD

**Issue by sven-kanoshin** [mockoon/mockoon#177]
**Describe the bug**
When duplicating a route, which responds with a file (raw file or as body, does not matter), the duplicate route and the origin route share the same  file reference. This means, changing the file in either of the routes, also changes the file in the other route.

The duplication scales, this means, any duplication inherits the file reference.

This behaviour seems like a bug to me. There is also a chance that I am misunderstanding the intent of the "Duplicate route" action. 

(As a side note, as much as I tested, no other field is shared in a reference way)

**To Reproduce**
Steps to reproduce the behavior.
* Create new environment
* Add Route -> GET /test1
* Add file -> test1.response.json
* Duplicate route -> Right click on route "/test1"  -> "Duplicate route"
* Modify the copy -> GET /test2
* Modify the copy, change file -> test2.response.json

**Expected behavior**
* Route "/test1" has a response as a file "test1.response.json"
* Route "/test2" has a response as a file "test2.response.json"

**Current Behavior**
* Route "/test1" has a response as a file "test**2**.response.json"
* Route "/test2" has a response as a file "test**2**.response.json"

**Mockoon version:**
1.5.0

**OS / OS version:**
Windows 7

**Comment by 255kb** [comment]
Nice catch. I missed this when adding the multi route responses feature. When duplicating a route, responses are not cloned. 
I will try to push a fix rapidly. In the meanwhile, I am afraid that there is no workaround.

**Comment by sven-kanoshin** [comment]
The workaround is to just build new route from scratch :) Though it might be a tad annoying, when you already have an elaborate configuration that needs to be duplicated.

My use-case is simple enough I can build from scratch, I just found this behaviour accidentally.

**Comment by 255kb** [comment]
sure you can still do this :)

I will try to correct this in the coming days

**Comment by 255kb** [comment]
New version 1.5.1 has been published :)
