### ISSUE TITLE
Routes with params make those without params unreachable

### ISSUE THREAD

**Issue by KennanChan** [mockoon/mockoon#178]
**Describe the bug**
Routes with params make those without params unreachable

**To Reproduce**
Set two routes:
1, /foo/:id
2. /foo/bar

Call /foo/bar, mockoon routes the request to /foo/:id, it treat 'bar' as an id.

**Expected behavior**
When calling /foo/bar, mockoon routes the request to /foo/bar correctly

**Mockoon version:**
1.5.0

**OS / OS version:**
Windows 10

**Comment by KennanChan** [comment]
Well, the trick is to move the /foo/bar route right before the /foo/:id route.

**Comment by 255kb** [comment]
Yes that's the idea. Route declaration are based on ExpressJS, so order is important especially if you have a catch-all `/*`.
