### ISSUE TITLE
[Feedback] UI improvements ideas

### ISSUE THREAD

**Issue by 255kb** [mockoon/mockoon#191]
/!\ This issue is only here to gather feedback. Ideas will be translated into real issues. /!\

I would like to improve the interface a bit. So, I am opening this ticket for a while to gather ideas. 
Please add one idea per comment (with a markdown title "## idea number - title") and vote on ideas with 👍 only. 

---

Idea 5: This is done and will be in v1.7.0, see #213 @aantoniv

**Comment by 255kb** [comment]
## Idea 1 - remove the top bar
Remove the top bar which contains the "start" button, the environment name, the port, prefix, latency, logs and settings button. 
This bar is scoped to the environment. All these things that are rarely modified could be moved in the environment settings page (the cog button) along with https and proxy settings. 
Environment logs and settings are already accessible from right click menu on the environment entry. 
Start button could be in the same menu, or directly in the environment menu entry.

**Comment by JoshMLeslie** [comment]
## Idea 2 - collapsible route list
Inline with idea 1, moving the start button and environment name editing input.
Related:  #173 / #104

**Comment by JoshMLeslie** [comment]
## Idea 3 - Better button to return from route log
Starts to feel cramped once request come in.
![image](https://user-images.githubusercontent.com/30437767/68595222-0594c580-0467-11ea-9ff2-b27e391eb6a3.png)

**Comment by jadenrogers** [comment]
Allow multiple lines on the "Add notes or documentation"

Currently hitting "Enter" does nothing. It would be great to be able to put enters where required for easier reading / improved formatting. 

![image](https://user-images.githubusercontent.com/8000621/69502679-c68e6600-0f76-11ea-99d0-033a36e91162.png)

**Comment by aantoniv** [comment]
## Idea 5 - Add "Notes or Description" to each response in route ##

Currently each response contains only Status Code and Incremented number(1,2,3,4...) in list per each response. I would like to have a possibility to define different notes per each response and be able to see it in that list (near status code and default response flag)

![image](https://user-images.githubusercontent.com/21062077/69638711-8228c600-105b-11ea-92d9-89a5d6606cb3.png)

IMO, maybe it is good place to add such field here:
![image](https://user-images.githubusercontent.com/21062077/69640202-43483f80-105e-11ea-9a30-e8bbf58fab69.png)

**Comment by davifo** [comment]
> ## Idea 5 - Add "Response description" to each response in route
> Currently each response contains only Status Code and Incremented number(1,2,3,4...) in list per each response. I would like to have a possibility to define different notes per each response and be able to see it in that list (near status code and default response flag)
> 
> ![image](https://user-images.githubusercontent.com/21062077/69638711-8228c600-105b-11ea-92d9-89a5d6606cb3.png)
> 
> IMO, maybe it is good place to add such field:
> ![image](https://user-images.githubusercontent.com/21062077/69640202-43483f80-105e-11ea-9a30-e8bbf58fab69.png)

Signed!

**Comment by jufis** [comment]
Resize Route and Env Panes?

**Comment by 255kb** [comment]
@jufis an issue already exists for route pane resize #104 
Env pane resize / collapse is already under development #204

**Comment by aantoniv** [comment]
![image](https://user-images.githubusercontent.com/21062077/70853789-311a2e00-1eb3-11ea-8742-cc9decfc9825.png)

It is awesome to have a possibility to add Notes per each response (Thanks!) , but is it possible to make dropdown list(spinner) wider, or make it wider by default? Then it will be possible to see longer note(description) before user selects it. Thanks!

**Comment by aantoniv** [comment]
And one more improvement which I find useful is to create a possibility to duplicate response 
![image](https://user-images.githubusercontent.com/21062077/70854008-447ac880-1eb6-11ea-89f8-f9c3295ea070.png)
, same way as existing "Duplicate route" works. 
![image](https://user-images.githubusercontent.com/21062077/70853992-10070c80-1eb6-11ea-9d8f-3a1cfed55437.png)
At least in my projects I see it useful as I have a lot of similar responses, with small differences only

**Comment by aantoniv** [comment]
## IMPORT/EXPORT selected environment ONLY 
I know there is possibility, to  "copy to clipboard" environment, but it would be nice to have an import/export menu option for only selected environment (or environments) ![image](https://user-images.githubusercontent.com/21062077/70854140-e7801200-1eb7-11ea-8291-784f41438a3b.png)

**Comment by aantoniv** [comment]
##Idea 9 -  "Ignore rules and default response, return selected response instead"
Currently there is a possibility to set response as a default (by dragging item in the responses list), but I see very useful option to "Ignore rules and default response", and return currently selected response from requested route. 

Usage example:
I have a lot of different responses from one route, but each response have the same rules. From my perspective, I want to be able to simply choose which response should be currently returned by route (IMO, the best option is currently selected response, not default). 

Currently to achieve this, I have to change default response each time. It would be awesome to have it simpler.


Thx for a great tool I use almost each day!

**Comment by zskamljic** [comment]
## Idea 10 - Show errors in body if applicable
Currently it's possible that you edit the body of the response which is for example JSON, forgetting a comma when adding a property will not immediately make it obvious that the body is not valid and when making a request to the endpoint it will instead return empty body, showing a small banner that's easily missed, resulting in some lost time, since I didn't notice it at first.

I propose we add a more persistent indication that something went wrong, or indicator that the object in body is not valid before the request being made.

**Comment by morgen-peschke** [comment]
## Idea 11 - Send out bad JSON

Currently, if the JSON is bad, it's replaced by some placeholder text and a notification, but not much visibility into the broken JSON.

If this were instead sent out in the response body, it could be shown in the endpoint logs, which would greatly help debugging (particularly where templates are involved).

As a bonus, sometimes it's actually useful to send your endpoint a garbage response, so it'd be awesome if mockoon could support this usecase as well.

**Comment by easydo247** [comment]
## Idea 12 - Change the way import from file works

If I import an API from JSON and then I modify it in Mockoon the imported file doesn't change. This makes versioning tedious and error prone.

**Comment by Kraloz** [comment]
Idea 13: Resizable columns in layout
![imagen](https://user-images.githubusercontent.com/20146634/73658044-4b31ea80-4672-11ea-842f-b1090a9f24ec.png)

**Comment by Kraloz** [comment]
## Idea 14: Make upload file button more visible

I would move to the right of the path input, it isn't clear what the button does (add a label maybe?)
![imagen](https://user-images.githubusercontent.com/20146634/73661281-918a4800-4678-11ea-962d-ca34b7548067.png)

**Comment by faebeee** [comment]
# Idea 15: Make Settings exportable
It would be great to export the settings for an API. So these settings can be added to a project/repo and shared with the team. So everyone can have the same mock API

**Comment by 255kb** [comment]
I am now closing this issue. Thank you for all your suggestions! While not all of them where UI I noted everything or answer below: 

Idea 1 -> #246 
Idea 2 -> #104
Idea 3 -> #247
Idea 4 -> #248
Idea 5 -> done in v1.7.0
Idea 6 -> #249
Idea 7 -> #250
Idea 8 -> #251
Idea 9 -> #252
Ideas 10 and 11 -> regrouped in #253 (this is a bigger problem and requires some work)
Idea 12: This won't be done. Imported file will stay the same, like in any other software. Mockoon saves the imported data in its own file. 
Idea 13 -> Environments menu will be collapsible in v1.8.0 (it's done #204), routes menu resize is tracked in #104 
Idea 14: #254
Idea 15: Not sure to understand. All Mockoon's data can already be exported and shared among developers (top menu "Import/export"). System has been improved a lot in v1.7.0 to easier sharing (more stable, imported data is migrated to new version, export is done without uuids, etc).
