### ISSUE TITLE
Field "Body (raw)" in "Environment logs" will be more convenient if has the default condition

### ISSUE THREAD

**Issue by Bulkinss** [mockoon/mockoon#200]
Field "Body (raw)" in "Environment logs" will be more convenient if has the possibility to change "closed"/"disclosed" condition as default.

**Comment by 255kb** [comment]
If I understand well, body content could be opened/shown by default?

**Comment by Bulkinss** [comment]
Yes, opened by default.

ср, 15 янв. 2020 г., 14:21 Guillaume <notifications@github.com>:
