### ISSUE TITLE
Add "AND" relations in route responses rules

### ISSUE THREAD

**Issue by neil-liao-dragon** [mockoon/mockoon#201]
Currently I saw user can add multiple rules for a response. But these rule check condition is "OR", for example if I have 2 rules for this response, then if rule1=true or rule2=ture, then this response will match and returned. Whether I want the AND relation, which means only when rule1=true AND rule2=true, this response will return. Do we have this feature? if not, when?

**Comment by 255kb** [comment]
Not yet and it's currently not planned. Rules are for now very simple: a response is served as soon as a rule is matched. On a "first come first serve" basis, I would say.

**Comment by WSTurner** [comment]
I would love this enhancement.

**Comment by jamescch** [comment]
Same for me. It would be much greater with this feature.

**Comment by ninjaneer164** [comment]
hi @255kb , one of our teams needed this feature recently, so i've made some changes. i would love to be able to create a PR for it. let me know!

**Comment by 255kb** [comment]
@ninjaneer164 This would be great. I will assign the issue to you. Feel free to open the PR as early as possible so we can start discussing the implementation if needed. And remember, DRY, KISS, etc 😸

**Comment by jotitajc** [comment]
It would be good if this improvement closes, which makes the tool more powerful.

**Comment by krishnaSpotnana** [comment]
This is an important feature.It would be great if its fixed soon.

**Comment by kriefsacha** [comment]
This is a very big issue.. I actually don't understand when you will need a OR condition on URL parameters ..

Need it as soon as possible please

**Comment by JanithaR** [comment]
[Here](https://mockoon.com/docs/latest/multiple-responses/) in the documentation, it is mentioned that there's a button to the left of the rules but I do not see it on my installation. I'm using Mockoon v1.9.0 on Mac.

**Comment by 255kb** [comment]
@JanithaR It has been added 2 days ago in v1.10.0! You should do an update :)

**Comment by JanithaR** [comment]
> @JanithaR It has been added 2 days ago in v1.10.0! You should do an update :)

Excellent! Thanks.
