### ISSUE TITLE
Add support for Dynamic XML Responses and Rules

### ISSUE THREAD

**Issue by Mavbraz** [mockoon/mockoon#208]
## Is your feature request related to a problem? Please describe.
Currently, you can make soap requests using the POST method with Content-Type "text/xml" or "application/soap+xml", but you cannot create dynamic replies and rules.

## Describe the solution you'd like
I found a good solution to this problem: convert the XML request to JSON. For this, I recommend the library "xml-js" with compress = true.
The biggest concern regarding this possible solution is the need for documentation, because the library will create a specific JSON.

**Changes**
All changes that I'm suggesting now, I've already implemented and I've already tested in a local repository.
Link for my fork: [Repository](https://github.com/Mavbraz/mockoon/tree/feature/dynamic-xml-response-and-rules)
See my changes below:
- route.type.ts
  - Added the headerValue "application/soap+xml"
  - Added the headerValue "text/xml"
- package.json
  - Added the library "xml-js"
- response-rules-interpreter.ts
  - Added lines to convert XML to JSON if the request is XML
- dummy-helpers.lib.ts
  - Added lines to convert XML to JSON if the request is XML

## Additional context
I'd also like to suggest including the "text/xml" and "application/soap+xml" content-types in the header value suggestions.

**Comment by 255kb** [comment]
That's a clever way to solve the problem. It feels like a "hack", wouldn't it be more "correct" to use an XML parser and look into the JS object? (Just asking, I am open to hacks 😄)

What do you mean by: 

> The biggest concern regarding this possible solution is the need for documentation, because the library will create a specific JSON.

**Comment by Mavbraz** [comment]
Realistically, this is like a "hack", but I thought about it from the beginning.

There is a problem if you use the "correct" way (XML parser) that is maintaining this implementation, because Mockoon implements the "Dummy JSON" lib to create a dynamic response.

If this feature is implemented in this way, an equivalent lib with the same features as Dummy JSON is required and any changes to one lib must be made on the other. Because of this, i've suggested to convert the XML in JSON for compatibility.

-------

About the quote:
> The biggest concern regarding this possible solution is the need for documentation, because the library will create a specific JSON.

I mean this implementation should be well documented, because lib "xml-js" converts XML into your JSON template.
Being more detailed, it creates the following special attributes during  the conversion:
- "_text"
- "_attributes"
- "_declaration"
- "_instruction"
- "_declaration"
- "_comment"
- "_cdata"

All special attributes should be cited in the [Documentation](https://mockoon.com/tutorial/dynamic-response-with-templating/)
More about the conversion can be found here: [xml-js](https://www.npmjs.com/package/xml-js)

**Comment by 255kb** [comment]
Fact is, Dummy JSON is just a helper system based on handlebars and you can generate any content with it. I think you can also generate XML without any major problem (I will test). 
I think the problem rather come from the entering request from which you need to parse XML body. 
Helpers need to be able to find data in XML "path". Anyway, XML needs to be parsed to JS or JSON so we are able to find things in it. 

So, I would say let's go for XML conversion to JSON. If you want you can create a pull request. 
I noticed something I did which is not good at all. In dummy-json helpers, body is parsed each time the helper is used. It should be parsed in the ExpressJS body parser directly https://github.com/mockoon/mockoon/blob/master/src/app/libs/express-middlewares.lib.ts#L20 and added to a new `request.jsonBody` property.

**Comment by travishao** [comment]
Can XPath  be introduced to solve this problem?

**Comment by mohdwaseem** [comment]
@Mavbraz , I need one help, I want to get the Name of the property key, is it possible to get the property name itself rather than value of property.
For Ex: `"user": {
    "_attributes": {
      "userID": "123"
    },
    "first": {
      "_text": "John"
    },
    "lastname": {
      "_text": "Doe"
    }
  }`
I need to compare the property value itself like "user"

**Comment by 255kb** [comment]
@mohdwaseem Next time, please use the Discussions forum for support requests: https://github.com/mockoon/mockoon/discussions
Concerning your question, it depends on what you are trying to achieve. If you want to check if the property exists in the body templating or with rules. 
With templating you can do it like this: 
```
{{#if (bodyRaw 'user')}}
user
{{/if }}
{{#if (bodyRaw 'admin')}}
admin
{{/if }}
```

With rules, there is currently no direct way to assess if a property exists. However, you can create multiple responses and create one rule each time verifying if a specific body path is not empty: 
![image](https://user-images.githubusercontent.com/7489814/136216423-abdd15a7-71f0-494a-9169-3c75ead6c6a1.png)
