### ISSUE TITLE
Add reverse proxy per route as well as static files server

### ISSUE THREAD

**Issue by ghost** [mockoon/mockoon#211]
**Is your feature request related to a problem? Please describe.**

I am trying to use mockoon as a server to host my static files server as well as being able to reverse proxy per route.  for example when developing locally I'd like to be able to reverse proxy to one or more of the microservices running locally but also reverse proxy to the dev api layer which hosts the bulk of the services

**Describe the solution you'd like**
I have about 120 microservices running and to be able to the run the application as a whole I would like to be able to point my services that I modified locally and test with the rest of the microservices on the dev env

**Describe alternatives you've considered**
I considered caddy webserver but I like mockoon GUI.

**Comment by gabrielperes97** [comment]
I like the proxy per route idea. I work with microservices with an API Gateway and I think this is missing on mockoon.

I think [fast-proxy](https://www.npmjs.com/package/fast-proxy) can help us on this feature, but I not test it with express yet.

**Comment by 255kb** [comment]
I don't see this proxy per route feature being implemented any time soon, I will close for now. 

Regarding the static files serving, this is already possible by creating a route with a parameter and using a relative path with the param in the body "file". 
![image](https://github.com/mockoon/mockoon/assets/7489814/8d377120-7761-492b-b122-1b4d7222fe59)

Here is an example API with two rules: 
[static-file-example.json](https://github.com/mockoon/mockoon/files/15456844/static-file-example.json)
