### ISSUE TITLE
Play migrations when importing

### ISSUE THREAD

**Issue by 255kb** [mockoon/mockoon#212]
**Is your feature request related to a problem? Please describe.**
Exported data is linked to app version. One export generated on one version cannot be imported on another.

**Describe the solution you'd like**
Any export should be importable in any more recent release. Stop relying on version check, and add migrations to data import.

**Comment by LukaszGrela** [comment]
Relates to https://github.com/mockoon/mockoon/issues/222 

I would say that it is a bug fix not an enhancement as it literally breaks the app usage.

**Comment by 255kb** [comment]
This system was done like this on purpose (obviously it was a mistake...) so it's not a bug it's a feature :cry: 
I will still change the label :+1:
