### ISSUE TITLE
Export data without UUIDs

### ISSUE THREAD

**Issue by rogeriocsilva** [mockoon/mockoon#216]
**Describe the bug**
Everytime someone makes changes on the environment, the endpoints uuid change. This results in unnecessary merge conflicts on the environment json. And with these merge conflits, comes the "file content has an incorrect format and cannot be imported" error.

**Screenshots**
![image](https://user-images.githubusercontent.com/10121694/69720317-426ce780-110a-11ea-81d3-890e199b2ec6.png)

**Mockoon version:**
v1.5.1

**OS / OS version:**
Mac OS, Linux Ubuntu 16.04

**Comment by 255kb** [comment]
I realize now that exporting with UUIDs doesn't make sense. They need to be unique on one installation, otherwise UI will behave inconsistently. But it's enough to generate them on import, and export without them. I will include this in v1.7.0 as it is a small change.
