### ISSUE TITLE
Terminal client

### ISSUE THREAD

**Issue by djlawhead** [mockoon/mockoon#220]
When developing and debugging my software inside a Docker container, it would be nice to be able to include Mockoon in the Dockerfile. That way I can have my debugger automatically launch Mockoon, import environment JSON file(s), and run the server.

A terminal client would be ideal, built without any dependencies on graphical UI libraries. That way I can have Mockoon be part of my dev container.

Right now I have to run Mockoon on my host machine, and include instructions on how to download, install, configure, and run Mockoon for any contributors. This is not a big deal, but the goal is to have as few external dependencies (for the host environment) as possible.

`mockoon start --environment ../my-api.json`
`mockoon restart`
`mockoon stop`

All other configuration could be done through a REST API, if need be, such as the one in WireMock. Being able to configure endpoints within the terminal might wind up with users issuing long commands.

**Comment by 255kb** [comment]
This has been requested before #62. I like the idea, a lot, but it would need to be a completely separated project, different distribution through NPM, build pipelines, etc. It's a lot of work and right now I just have enough time to improve Mockoon GUI. 
I will reopen #62 to track people's interest, but it won't be on the roadmap any time soon.
