### ISSUE TITLE
Allow scrolling in routes pane with arrow keys

### ISSUE THREAD

**Issue by jufis** [mockoon/mockoon#225]
We cannot resize routes pane, so we cannot see from a quick look where is a specific route to make changes and we have to go through each one.

UP/DOWN keys are not working when you try to scroll down routes as well.

MAC OS v1.6.0

![image](https://user-images.githubusercontent.com/8059283/70626944-feabcf00-1c2d-11ea-94d8-123adf76592b.png)

**Comment by 255kb** [comment]
Route pane resize is already covered in an existing issue #104, so I will rename the current issue to only talk about arrow navigation.

**Comment by 255kb** [comment]
After thinking about it a little bit more I won't add scrolling through routes with arrow keys as many things could be scrollable at the same time: environments menu, routes menu, body, headers, rules, etc. 
Route column resize (#104) will be available in v1.9.0 and the is a option in the settings that allows users to choose between truncation or word wraping for the route menu. 
This should solve your issue.
