### ISSUE TITLE
Add setting "Truncate route name in list".  When true, the current truncated route display will be used, but when false, the full route will be displayed as wrapped text

### ISSUE THREAD

**Issue by johnwest80** [mockoon/mockoon#226]
Add setting "Truncate route name in list".  When true, the current truncated route display will be used, but when false, the full route will be displayed as wrapped text.

Current
![image](https://user-images.githubusercontent.com/1585088/70627748-c340de80-1bf4-11ea-9ffc-067453cfeedc.png)

Proposed via setting
![image](https://user-images.githubusercontent.com/1585088/70627775-cdfb7380-1bf4-11ea-9bac-b48a025f03bf.png)

**Comment by johnwest80** [comment]
I'd be glad to work on it.

**Comment by johnwest80** [comment]
actually, i already have it done :).  can i pr it?

![image](https://user-images.githubusercontent.com/1585088/70630005-d81f7100-1bf8-11ea-9c79-56e04702af53.png)

**Comment by johnwest80** [comment]
Went ahead and created the pr :)

https://github.com/mockoon/mockoon/pull/227

**Comment by 255kb** [comment]
I saw ;) Thank you for the contribution
This is a good idea. 
I won't be able to review your PR soon as I need to finish v1.7.0 and work on other PR first. But don't worry I will have a look at it as soon as possible.
