### ISSUE TITLE
add api to get environment logs

### ISSUE THREAD

**Issue by iandian** [mockoon/mockoon#230]
When I used api with dynamic response, I want to get the environment logs of current environment by api, so i can get the api response of last api call and use it to dynamic verify in my UT.

**Comment by 255kb** [comment]
Could you please elaborate a little bit? What do you mean "by API"? 
If I follow well: you have tests sending requests to Mockoon mocked APIs. And you want to verify the content of the responses sent by Mockoon.
Why don't you save the response during your test? 
I am doing this in the IT tests here. You can see an example there: https://github.com/mockoon/mockoon/blob/master/test/basic-calls.spec.ts
