### ISSUE TITLE
Add cookie to dummy helpers

### ISSUE THREAD

**Issue by sleepypikachu** [mockoon/mockoon#235]
**Is your feature request related to a problem? Please describe.**
I wanted to use a value from a cookie in my response but the cookie header is formatted and may contain multiple cookies so I can't trivially pull the value of a given cookie key.

**Describe the solution you'd like**
I'm proposing to add `cookie key default` to the dummy helpers

**Comment by sleepypikachu** [comment]
I'd like to work on this issue please.

**Comment by 255kb** [comment]
Hi @sleepypikachu 
Good idea. You can definitely work on this, any help is really appreciated :) 
This should be a small addition and I have no specific advice to give you. You can probably base your helper on `header` helper or something like this.

**Comment by sleepypikachu** [comment]
Thanks, @255kb.

There don't seem to be any tests which cover the helpers. Do you think it's worth adding tests to cover them? Where would those tests live?

**Comment by 255kb** [comment]
Yes for now there are no unit tests, only functional tests (automated UI tests with Spectron). I will probably add a test suite for templating helpers soon. So it's ok if you don't add them. 
Thank you for the PR, I will review ASAP 👍

**Comment by sleepypikachu** [comment]
I'll fix the linting tomorrow :-)
