### ISSUE TITLE
Add option to prevent API prefix to be forwarded to proxied server

### ISSUE THREAD

**Issue by 255kb** [mockoon/mockoon#237]
**Is your feature request related to a problem? Please describe.**
When setting up an API prefix, it is forwarded as is to the proxied route. 
It can make sense that requests are proxied without the API prefix. 

Example: 
1. `localhost:3000/myprefix` is declared in Mockoon, with no route, and proxy mode active (set to `http://localhost: 3010/`)
2. when calling `localhost:3000/myprefix/foo` it is forwarded to `http://localhost: 3010/myprefix/foo`

**Describe the solution you'd like**
It could be useful to have it forwarded to `http://localhost: 3010/foo`, ignoring the prefix declared in Mockoon. 
This should be store in the settings.

**Comment by barefootdeveloper** [comment]
I'd be willing to do this if you'd like to assign it to me.

**Comment by 255kb** [comment]
@barefootdeveloper sure you can :)
