### ISSUE TITLE
Environment logs entries icons are hidden when path is too long

### ISSUE THREAD

**Issue by 255kb** [mockoon/mockoon#238]
**Describe the bug**
Environment logs entries icons are hidden when path is too long

**To Reproduce**
Make requests on long paths.

**Expected behavior**
Icons shouldn't be hidden, text should be truncated

**Screenshots**
![Capture](https://user-images.githubusercontent.com/7489814/71896706-cd52f000-3154-11ea-8c5a-0679358413c6.PNG)

**Mockoon version:**
latest

**OS / OS version:**
all

**Comment by sotcha** [comment]
Hei @255kb , can I submit a PR for this issue? I can see that is already assigned, but I have already a fix.

**Comment by 255kb** [comment]
Hi @sotcha Sure you can!
