### ISSUE TITLE
Duplicated route located after the original

### ISSUE THREAD

**Issue by feraguiba** [mockoon/mockoon#239]
When you duplicate a route, it should be good to have the cloned one right after the original, not at the end of the list.

I use to organize the routes with the same path together, but when I duplicate a route I have to go down to the bottom of the list of routes and move it. It is tedious.

**Comment by sleepypikachu** [comment]
@255kb happy for me to pick this one up?

**Comment by 255kb** [comment]
@sleepypikachu Sure :)

**Comment by sleepypikachu** [comment]
@255kb do you think the behaviour should be the same for duplicating environments or keep the old "add to the end of the list" behaviour?

**Comment by 255kb** [comment]
@sleepypikachu Good question, this would make sense. Go for it! :+1:
