### ISSUE TITLE
Can you import mockjs rules?

### ISSUE THREAD

**Issue by 403605209** [mockoon/mockoon#241]
link => [Mockjs](http://mockjs.com/examples.html)

I would like some chinese text name .etc

**Comment by 255kb** [comment]
Mockoon is currently using https://github.com/webroo/dummy-json and I am not sure integrating another JSON/JS mocking library is a good long term solution. Maybe one day I will migrate Mockoon to some more robust JSON mocking library but this is not at the top priority now.
Also internationalizing the mock JSON is a huge work that I won't be able to do.
You can still open some specific issues and pull requests to add specific helpers that could benefit to the whole community.
