### ISSUE TITLE
Domain replacement/removal for Set-Cookie header

### ISSUE THREAD

**Issue by usrbowe** [mockoon/mockoon#245]
**Is your feature request related to a problem? Please describe.**
When I run a proxy mode in Mockoon, I'm facing issue with Cookies. In the original response, they have specific domain to be set on, so when my app connects via localhost, the domain will be different.

**Describe the solution you'd like**
I would like to have and option to `replace domain` for cookies, when running reverse proxy. Similar to what nginx have: http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cookie_domain
But since Mockoon by default runs on `localhost, 127.0.0.1`, so we can't set a cookie (unless running local DNS server to resolve this issue). I think solution here might just to omit `domain` from all `Set-cookies`.

**Describe alternatives you've considered**
Maybe use recently added `cookie` helper to overrride specific cookies.

**Additional context**
Header from request:
```
Set-Cookie: __Secure-ID=123; Secure; Domain=example.com
```
Should be replace to:
```
Set-Cookie: __Secure-ID=123; Secure
```

**Comment by ishamf** [comment]
For removing domains, seems it's already a feature in the proxy library https://github.com/chimurai/http-proxy-middleware as `cookieDomainRewrite`. But to fully support this cookie I think the `Secure` option need to be removed too, otherwise it won't be sent to the (usually HTTP) proxy.

**Comment by Saucistophe** [comment]
> For removing domains, seems it's already a feature in the proxy library https://github.com/chimurai/http-proxy-middleware as `cookieDomainRewrite`. But to fully support this cookie I think the `Secure` option need to be removed too, otherwise it won't be sent to the (usually HTTP) proxy.

Removing the secure flag seems doable https://github.com/chimurai/http-proxy-middleware/issues/237

**Comment by 255kb** [comment]
Thank you for contributing @Saucistophe I will try to review asap and integrate your change in the next release

**Comment by Saucistophe** [comment]
Thank you for the quick release and your thanks in the changelog :hugs: 
Sadly, it doesn't fix my problem; but I guess I'll have to investigate further...

**Comment by 255kb** [comment]
@Saucistophe oh really? I'm not used to cookie forwarding, and after testing/exploring a bit it seemed to be the required change. 
Let me know if I can help.

**Comment by Saucistophe** [comment]
I use an application developped in my company; What I receive when login through Mockoon is:

`Set-cookie: access_token=<REDACTED>; Max-Age=35999; Expires=Sat, 04-Dec-2021 01:56:09 GMT; Path=/; Secure; HttpOnly`
And that cookie never got sent back with subsequent requests.

I thought that what was bothering the application was the `Secure` part, so when I saw this issue, I felt confident enough that what was happening was that our client saw the "secure" coming from a HTTP proxy, and bailed out.

After testing again on 1.17, I still have the problem, so I guess I have some investigation to make on the client side before touching Mockoon's code again :)
