### ISSUE TITLE
Bigger button to return from environment logs

### ISSUE THREAD

**Issue by 255kb** [mockoon/mockoon#247]
Button to come back from environment logs could be more visible.

Starts to feel cramped once requests come in.
![image](https://user-images.githubusercontent.com/30437767/68595222-0594c580-0467-11ea-9ff2-b27e391eb6a3.png)

_Originally posted by @JoshMLeslie in https://github.com/mockoon/mockoon/issues/191#issuecomment-552471138_

**Comment by izerozlu** [comment]
I might look into that. Is it available

**Comment by 255kb** [comment]
Sorry but I would like to do this myself. Some big work on the UI is planned (moving all the header part somewhere else to declutter the application) and this is part of it. I still don't know how navigation will look and I will have to try multiple possibilities. 

However, any suggestion is welcome. 
Long story short, the top header are info related to the environment itself that does not change frequently. I would like to remove the name completely (and allows modification directly in the left menu), put the port, prefix and latency configuration in the environment settings. Only remains the start/stop button and the two icons on the right: logs from which we want to go back and settings. Both are already available in the environment context menu (by right clicking on an environment name). Maybe adding some tabs (routes/logs/settings) at the top would be good, I don't know. Using tabs would make this issue useless.

**Comment by izerozlu** [comment]
Decluttering is a good way to think but removing the port, prefix and latency sections might confuse newbie users.

But on the other hand it might prove to be useful removing them out of sight.

About the tabs, in my opinion those are one of the most aggressive way to clutter the application. Less the better.

**Comment by 255kb** [comment]
I understand what you are saying. On the other hand, there are already 3 "pages", sort of. The main one with the routes list and all the route details, the environment settings, and environment logs. 
I had the impression that three tabs instead of the top bar would be clearer. Also, it seems that a lot of people don't see the logs icon which hides a very interesting feature.
I will think about this :)

**Comment by 255kb** [comment]
Closing this issue as this button will probably disappear when redesigning the top bar (env settings/params)
