### ISSUE TITLE
Allow duplication of route responses

### ISSUE THREAD

**Issue by 255kb** [mockoon/mockoon#250]
And one more improvement which I find useful is to create a possibility to duplicate response 
![image](https://user-images.githubusercontent.com/21062077/70854008-447ac880-1eb6-11ea-89f8-f9c3295ea070.png)
, same way as existing "Duplicate route" works. 
![image](https://user-images.githubusercontent.com/21062077/70853992-10070c80-1eb6-11ea-9d8f-3a1cfed55437.png)
At least in my projects I see it useful as I have a lot of similar responses, with small differences only

_Originally posted by @aantoniv in https://github.com/mockoon/mockoon/issues/191#issuecomment-565749413_

**Comment by izerozlu** [comment]
I would like to look into that. I see that no is assigned yet. Is it available?

**Comment by 255kb** [comment]
Hi @izerozlu Sure, you can work on this. 
Here are some guidances, as I already thought about this feature a little bit. 
- I think the same icon as route duplication should be used. 
- it could be place next to the trash used to remove a route response
- duplication behavior should be the same than environments and routes: new duplicated route response should be inserted next to its source (and not at the end of the list). 
- "(copy)" could be appended at the end of the route response's label

This will require creation of a new Action for the reducer. 
You can take inspiration from the environment duplication methods: https://github.com/mockoon/mockoon/blob/master/src/app/services/environments.service.ts#L137

Please confirm me if you want to work on this so I can assign this issue to you. 

Thank you!

**Comment by izerozlu** [comment]
@255kb You've given everything required for the further development. Thanks for that :).
Please see this reply as the confirmation.

**Comment by 255kb** [comment]
No problem! Do not hesitate if you have any question.

**Comment by 255kb** [comment]
@izerozlu I just pushed a big refactoring on master, please star your work from there, it will easier the review/merge. Thank you!

**Comment by izerozlu** [comment]
Thanks for the heads up. I've not began working on the issue yet so no worries.

**Comment by izerozlu** [comment]
Hey @255kb, I've began working on this issue. Mostly finished actually. Btw sorry for starting so late on the issue.

I'm curious about where to add testing for the functionality. Can you point me to some testing scenarios I could inspire from?

**Comment by 255kb** [comment]
No problem, there is no deadline :) 
For now there are only UI functional tests done with Spectron (Electron testing framework based on Webdriver). 
You can have a look in the [test folder](https://github.com/mockoon/mockoon/tree/master/test/suites). A good example would be https://github.com/mockoon/mockoon/blob/master/test/suites/responses-rules.spec.ts which is focused on routes response rules but actually create new route responses. 
I think you can create a new file for your tests. It could be based on https://github.com/mockoon/mockoon/blob/master/test/suites/routes-duplicate.spec.ts but should ideally test more things (after duplicate, test that the new response has the same status code, same body, same headers, and rules). 
Do not hesitate if you have any question or even need help for something. 
Thank you for working on this.
