### ISSUE TITLE
Import/export selected environment only

### ISSUE THREAD

**Issue by 255kb** [mockoon/mockoon#251]
I know there is possibility, to  "copy to clipboard" environment, but it would be nice to have an import/export menu option for only selected environment (or environments) ![image](https://user-images.githubusercontent.com/21062077/70854140-e7801200-1eb7-11ea-8291-784f41438a3b.png)

_Originally posted by @aantoniv in https://github.com/mockoon/mockoon/issues/191#issuecomment-565750491_

**Comment by 255kb** [comment]
Regarding the implementation, idea would be to add a new menu entry "Export current environment". This would be equivalent to right clicking on the environment menu entry and select copy to clipboard. It would export only the current environment.

**Comment by gVirtu** [comment]
Ah, I started using Mockoon recently and was looking for this feature. 
If it's okay, I'd be down to implementing it. :)

**Comment by 255kb** [comment]
hi @gVirtu you're welcome to contribute :) I assigned the task to you. 

Concerning the naming I think it's good like you did, it's clear enough. Do not forget then to update the test helper `sendWebContentsAction`.
