### ISSUE TITLE
Improve JSON errors feedback

### ISSUE THREAD

**Issue by 255kb** [mockoon/mockoon#253]
**Is your feature request related to a problem? Please describe.**
When there is an error in the JSON body, there is only a small alert displayed when route is getting called. There is no information on the line which is erroneous. 
Editor should be able to highlight the erroneous light, which is the case. But it does not play well with the templating which can break the JSON, especially helpers like `{{#repeat}}`.

**Describe the solution you'd like**
Editor should be able to always highlights errors. For this, we might need to switch to a different templating engine which keeps JSON valid.

**Comment by morgen-peschke** [comment]
An additional ask would be to, if possible, allow bad JSON as the response.

This is useful on two fronts: 
1. It makes it so that there's always a way to see what the templating produced (even if it ends up breaking the JSON)
2. It provides an easy way to test if a flow can handle a broken response mid-way through a flow.

**Comment by taranvohra** [comment]
I just spent good amount of time figuring out why my JSON is incorrect. At last I used a JSON linter. Can we add something like [https://www.npmjs.com/package/jsonlint-mod](url) It can be used to lint when `Format body` is clicked?

**Comment by 255kb** [comment]
@taranvohra body editor already includes a JSON linter. But it's deactivated for now as some templating helpers (`{{#repeat ...}}`) may not result in valid JSON.
That's the reason why I would like to switch to another templating system which has a JSON valid syntax. Something like: 

```
{
  "#repeat 1": {
    "name": "{{firstname}}"
 }
}
```

Anyway, I am open to any suggestion to improve the current system. Also, I prefer to rewrite the whole system so it's working well, rather than adding options to deactivate the templating/deactivate the linting, etc

**Comment by 255kb** [comment]
After reviewing a lot of templating engines it appears that none of them offer the simpleness and flexibility of Handlebars (which we use through Dummy JSON). Some of them are written in other languages and does not play well with JS/Electron out of the box. Also, they would introduce a big breaking change for the next version which I would try to avoid. 
So I think that after all I will do some changes that give users more options and feedback about what went wrong:
- Serve the JSON body even if it's invalid as @morgen-peschke suggested
- add an option to disable templating on each route response (see #129 )
- maybe add a "postview" tab, with the linter enabled, where you would see the body that has been served and immediately see what was wrong. I call it a "postview" and not a preview as you can create quite complex JSON bodies with the templating system. Even more in the next release where you will be able to reuse objects or arrays from the request's body. So, it would need to have access to a real request in order to build the body with all the helpers.

**Comment by morgen-peschke** [comment]
Thanks for taking these on, I think these will really help debugging our templates :)
