### ISSUE TITLE
Add, in "Rules" configuration, a way for testing against empty arrays or absent fields in a JSON payload

### ISSUE THREAD

**Issue by makareth** [mockoon/mockoon#255]
Currently (1.6.0), the "Rules" configuration allows for testing equalities but doesn't allow to test empty arrays or absent fields in a given JSON object.

I wish I could for example send an HTTP 200 instead of a HTTP 201 created in a POST coming with an empty array, hence having nothing to be created.

A first discussion with @255kb here for implementors :
"Question is more : how to represent an array in the rule input field (string) . I would like to avoid using eval() of course. A solution would be to create a DSL with very basic syntax"

Thank you !

**Comment by mariantirlea** [comment]
+1

**Comment by evjwm** [comment]
+1

**Comment by jwmxyz** [comment]
+1

**Comment by roybarber** [comment]
+1 would be very useful

**Comment by gamedevtutorials** [comment]
i started to implement this. It works so far, but is also a Draft.
I added another Checkbox in the rule section (see screenshot).
When you check the field the value is checked against null or undefined and returns true if it matches. 
Additionally you can add the value "array" into the value field which will also add a check for an empty Array. It may not be too pretty but it works :)
![image](https://user-images.githubusercontent.com/17945179/131332487-714ec600-48ae-4197-bc52-552f7a185788.png)

**Comment by gamedevtutorials** [comment]
@255kb Any chance you assign this ticket to me? And can someone help me how to push my branch? I made one in the main project, commons and commons-server

**Comment by 255kb** [comment]
We had a small discussion with @gamedevtutorials and came up with the following solution: 
The equal operator could be transformed in a dropdown showing the following options: 
- equals
- regex (and we can get rid of the regex checkbox)
- null
- empty array

Quick mockup: 

![image](https://user-images.githubusercontent.com/7489814/131352073-19dd5541-c55d-4d58-92e2-0c5404206473.png)

This would make the interface a bit easier to use.

**Comment by ramkumar-sacumen** [comment]
Hi Team,

How to pass the input in the Rules when my Json looks like this

"Authentication: = {"username": "Test","password": "Test"}

**Comment by 255kb** [comment]
@ramkumar-sacumen Could you please elaborate on what you are trying to do? I am not sure to understand. Also, I would kindly ask you to open a new [discussion](https://github.com/mockoon/mockoon/discussions/new), instead of posting in an old issue. It's not the best place to ask for support. 
Thank you!
