### ISSUE TITLE
bind environment with files

### ISSUE THREAD

**Issue by DophinL** [mockoon/mockoon#256]
**Is your feature request related to a problem? Please describe.**
I want to share environment with colleague.
Now, I just can export environment to others.
But when a new api added, I need to export again.

**Describe the solution you'd like**
Can you bind environment with local files, and sync them.
If so, I could store environment data in git to share with others.

**Describe alternatives you've considered**

**Additional context**

**Comment by 255kb** [comment]
This will be dealt with soon with this issue: #16
Idea is to let users configure the data storage folder so they can easily use a git repository in order to share the APIs.
