### ISSUE TITLE
add api search feature

### ISSUE THREAD

**Issue by DophinL** [mockoon/mockoon#257]
**Is your feature request related to a problem? Please describe.**
if I have over 100 api, find one is difficult.

**Describe the solution you'd like**
can you add search feature to search apis?

**Describe alternatives you've considered**

**Additional context**

**Comment by deciomontanhani** [comment]
I'm facing this issue as well. Some tags to categorize by features would be nice.

**Comment by sotcha** [comment]
Hi @255kb Can I help with this? Seems a really nice feature.

**Comment by 255kb** [comment]
@sotcha Sure you can. If possible, I would prefer to finish #264 with you as I also have some WIP on my side. I would like to avoid having too many things dealt with at once, as my time is quite limited :) 

Concerning the implementation of this, I was thinking about a small search box (input) on the right of the + button that adds a route. Simply entering text in it would filter what is shown in the menu with a simple RxJS filter on the routes list, searching in the paths, methods, or documentation. And then a small **X** to reset the filter. I think it could be quite straightforward.
What do you guys think?

**Comment by monobasic** [comment]
> @sotcha Sure you can. If possible, I would prefer to finish #264 with you as I also have some WIP on my side. I would like to avoid having too many things dealt with at once, as my time is quite limited :)
> 
> Concerning the implementation of this, I was thinking about a small search box (input) on the right of the + button that adds a route. Simply entering text in it would filter what is shown in the menu with a simple RxJS filter on the routes list, searching in the paths, methods, or documentation. And then a small **X** to reset the filter. I think it could be quite straightforward.
> What do you guys think?

Would be great! This is the only feature I am missing currently.

**Comment by sotcha** [comment]
Hi guys, I have been developed this feature for personal usage since I found this useful. But unfortunately, I didn't manage to create a pull request.

The solution is similar to @255kb proposal.

#### The functionality is: 

1. A button opens filtering input filed 
2. The filtering is applied while typing in the routes paths
3. Close button or _escape_ key will reset and close the filter


![recording-search-routes2](https://user-images.githubusercontent.com/1183265/103162472-cad02700-47f9-11eb-9501-1677aad17084.gif)


If you like it I have ready a branch for this and I can create a pull request.

**Comment by 255kb** [comment]
hi @sotcha Thank you for the suggestion and proposal. But I already have something working on a branch. Same behavior, but different UI. I am glad we are aligned on this 😄 
I just didn't have time to finish it since we were really busy on the mockoon/cli.

It will be in the next release.

**Comment by Luckey-Elijah** [comment]
Is this feature in the current release(v1.12.0)? And if so how do I use it?

**Comment by 255kb** [comment]
@Luckey-Elijah this has been merged and will be available in the next release (next Tuesday if everything goes right 🙂)

**Comment by Luckey-Elijah** [comment]
@255kb okay, great! Thanks 😊
