### ISSUE TITLE
Extend environment log to x entries, it is too small! Add option to export environment log to file for inspection.

### ISSUE THREAD

**Issue by Royscw** [mockoon/mockoon#267]
I'm having an asynchronous process call back to the Mockoon service. Inspecting these messages is time consuming from the server logs on the service calling Mockoon. 

Ideally we would have a configurable environment log size so optionally a large number of entries is retained. i.e. default 60, max 1028 entries in the environment log.

I'm looking to have these exported to file for inspection at a later time and for test audit purposes as well. This is linked to the need to have a larger environment log. If the environment log was written to file by default, this requirement would be superseded by this. 

If only 60 entries were in the UI, but all entries were pushed out to file then there wouldn't be a need for a larger log in the app or an export function.

Thanks for your time. Great tool.

**Comment by 255kb** [comment]
@barefootdeveloper could you please comment here so I can assign the issue to you?

**Comment by barefootdeveloper** [comment]
Sure thing @255kb , sorry I didn’t comment first. I knew you were away from the other PR and I’ve been trying to do OSS commits in the morning while I’m waiting to start work.

**Comment by 255kb** [comment]
No problem It's great you are contributing :) 
Let's discuss on the Discord server.
