### ISSUE TITLE
Response list - change default response

### ISSUE THREAD

**Issue by LukaszGrela** [mockoon/mockoon#268]
**Is your feature request related to a problem? Please describe.**
I need a response 200 and error with different bodies. I can create 2 separate ones but first is always default. I can add a rule to switch to another response but I would like to just switch manually which is default as there is no rule I could use to turn it on automatically.

**Describe the solution you'd like**
Checkbox that will indicate which rule is default

**Describe alternatives you've considered**
In my case there is no alternative. I could try to add a rule but most of the times for my need I can't do it. It would be simpler to just decide which on the list is default.

**Comment by 255kb** [comment]
You can drag and drop responses in the dropdown to make one or another the first (default) one. It's not really straightforward and will probably be replaced in the future by a checkbox. Tracked by this issue #252

**Comment by LukaszGrela** [comment]
I've just discovered this, it wasnt clear though:) at least to me.

**Comment by 255kb** [comment]
Apparently it's not clear for many people so it will definitely change :)
