### ISSUE TITLE
Rule to match entire body (When body is not an object)

### ISSUE THREAD

**Issue by LukaszGrela** [mockoon/mockoon#271]
**Describe the bug**
Rules for Body path (JSON / form data) doesnt work when body is just a string (not the object)

**To Reproduce**
request which body is just a string, try to apply rule that will match that string

**Expected behavior**
Option

**Screenshots**

![image](https://user-images.githubusercontent.com/7643591/77090500-249bf900-69ff-11ea-9294-5b64fdccfaa1.png)
![image](https://user-images.githubusercontent.com/7643591/77090547-35e50580-69ff-11ea-8b0f-edff7ce212cc.png)

**Mockoon version:**
1.7.0

**OS / OS version:**
Windows 10

**Comment by bykof** [comment]
I created a pull request regarding this issue: https://github.com/mockoon/commons/pull/14
