### ISSUE TITLE
 when i put the following rule object.object = null never response the data i have set for this rule

### ISSUE THREAD

**Issue by jotitajc** [mockoon/mockoon#284]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.
/!\ Please include the environment / route configuration you are using if you can (route, response type, headers, body, etc)

**Expected behavior**

**Screenshots**

**Mockoon version:**
1.1.0, 1.0.0, etc

**OS / OS version:**
Windows 10, Mac OS, Linux Ubuntu 18.xx, etc

**Comment by 255kb** [comment]
If I understand correctly, it seems you are trying to assess if a parameter is not present or empty. If present but empty you should be able to use the following regex for simple cases `^$|\s+`. However, there is currently no way to test if a parameter is completely missing. This will be done in issue #255 .
I am closing this one as a duplicate.
