### ISSUE TITLE
Open mock server in browser

### ISSUE THREAD

**Issue by Natetronn** [mockoon/mockoon#287]
**Is your feature request related to a problem? Please describe.**
Please save us some typing by providing a link to the current mock server's url.

**Describe the solution you'd like**
 - For the main url perhaps put an icon to the left of the env log and env settings icons that opens its url in default browser when clicked. And or, in the right click menu for each environment a link to open it.
 - For each route add an icon that links to the route and main url. Either via icon or right click menu or both.
 
As an optional bonus for specific routes, popup a window so we can fill in the value of any detected variables. For example, input a number for a user ID, which then opens in a browser with the url and said ID populated.

**Describe alternatives you've considered**
For the main url, perhaps clicking next to the url/port, where there is a plug icon and 0.0.0.0, maybe that itself could be a button that opens the url in default browser.

**Additional context**
"Opens in new window icon" example:
https://cdn1.iconfinder.com/data/icons/media-icons-23/100/new_window-512.png

**Comment by Natetronn** [comment]
Wow, crazy! I'm now seeing the open in new window icon on the right side of the route to open it in the browser. Either I'm blind (I looked over that whole area and even mentioned the exact two icons above it so, not sure how I could have missed it) or you just added this feature and updated a few minutes after I posted? Either way, that's awesome, thank you!

**Comment by 255kb** [comment]
This icon was there on GET routes since the beginning 😄 I wish it was that simple to publish a new version 😭 
I think you are right, having it greyed out when not available (environment not running or method != GET) would be better. 
However, adding the same icon on "global" level does not make really sense to me. It's only a secondary feature that make sense on GET methods.

**Comment by Natetronn** [comment]
Thanks for the reply!

> However, adding the same icon on "global" level does not make really sense to me. It's only a secondary feature that make sense on GET methods.

Now that I've spent more time thinking about it, I see what you're saying. Had there been a way to display some form of code directly at 0.0.0.0:3000 then it would have made sense but, since that's not the case it wouldn't be useful, you're right.

**Comment by 255kb** [comment]
You can still, but you need to declare a route with no path, then it's available at localhost:3000/, but like this having two buttons is redundant too.

**Comment by Natetronn** [comment]
> You can still, but you need to declare a route with no path, then it's available at localhost:3000/, but like this having two buttons is redundant too.

That makes sense, thank you!
