### ISSUE TITLE
Internal error on bad parsing of a request

### ISSUE THREAD

**Issue by sotcha** [mockoon/mockoon#298]
**Describe the bug**
An internal error occurs when we use **application/json** as **Content type** and the body is not a valid json.

**To Reproduce**
- Start mockoon server to 3000 port
- Create a request 
`curl -H 'Content-Type: application/json' -X POST http://localhost:3000/testpath --data  'test-data'`

**Expected behavior**
We should see the request into _Envirnoment logs_ section but nothing is happening. 

An exception can be found on **~/.config/mockoon/logs/renderer.log**

**Mockoon version:**
1.8.0 - master branch (last commit b8832ca)

**OS / OS version:**
Linux Debian

----
Seems that the error occurs from 

https://github.com/mockoon/mockoon/blob/b8832ca03c66cb49531cd82ac2ccf193307ae474/src/app/libs/express-middlewares.lib.ts#L51

**Comment by 255kb** [comment]
Apparently bug does not exists on 1.8.0 only on master. 
Thank you for catching this early!
