### ISSUE TITLE
Add route headers and rules count in tab

### ISSUE THREAD

**Issue by 255kb** [mockoon/mockoon#299]
**Is your feature request related to a problem? Please describe.**
Without going to route response's headers and rules tabs it's not possible to know how much of them are setup. 

**Describe the solution you'd like**
Add the counts `Rules (X)` in both tabs

**Comment by TheDartCode** [comment]
Hey there!
I find Mockoon really awesome and helpful and would like to offer a hand whenever I am able to😄 
May I start with this one?

**Comment by 255kb** [comment]
Thank you for the kind words 😃 Sure you can help! I will assign the task to you and put it in progress in the roadmap.
Concerning the implementation, you will see that all the data comes from the store and leverage Observables as much as possible. 
Go for the simplest and most straightforward implementation :)
However, as simple this improvement is, me must try to cover everything with UI automated tests. You will find them in `./test/suites`. You can add them in the `ui-interactions.spec.ts` as it is quite small. 
You will see that there are already some helpers to create rules and headers. Use them as much as possible. 
If you have any question do not hesitate, I am available in the chat: https://spectrum.chat/mockoon.

**Comment by TheDartCode** [comment]
Great!
Thanks for the thorough guidelines. Talk to you in spectrum :)
