### ISSUE TITLE
Cannot scroll in response drop down list

### ISSUE THREAD

**Issue by JihanGao** [mockoon/mockoon#305]
I cannot scroll down the response drop down list if I add more than 14 mocked responses. How can I fix this problem
![image (1)](https://user-images.githubusercontent.com/12092464/83804509-41e67800-a67c-11ea-96a4-9e46138c303e.png)

**Comment by 255kb** [comment]
Apparently you cannot! You just found a bug. 
This will be fixed for the next version.

**Comment by JihanGao** [comment]
Thanks for the reply. I am wondering how soon your team will give a new release.

**Comment by 255kb** [comment]
Not before several weeks. There are still some things that are not ready for the next release.

**Comment by JihanGao** [comment]
Okay. Thanks
