### ISSUE TITLE
Support for moving an api from one environment to another environment

### ISSUE THREAD

**Issue by xiongxiong** [mockoon/mockoon#308]
**Is your feature request related to a problem? Please describe.**
I can't drag or move an api from one environment to another environment.

**Describe the solution you'd like**
Support for dragging api item.

**Describe alternatives you've considered**
Add a menu to api item for moving api item to another environment.

**Additional context**
Best API mock util I've ever used, good work.

**Comment by izerozlu** [comment]
@255kb do you think this would be a good addition? If so I would want to look into this.

**Comment by 255kb** [comment]
@izerozlu Sure that would be great. Would you mind joining the chat so we can discuss the implementation before you start? 
https://spectrum.chat/mockoon

**Comment by izerozlu** [comment]
Highlights with my conversation with @255kb are:
- A new context menu entry will be used instead of drag & drop.
- Route will be "duplicated" not "moved".
- A dialog will help user to select desired environment for the duplication.

**Comment by izerozlu** [comment]
@255kb I know that it's been quiet a while since I've picked up this issue. Just wanted to inform that I'm still interested in implementing it.

**Comment by 255kb** [comment]
@izerozlu No problem, take your time! 😃
