### ISSUE TITLE
Check for property existence in Rules

### ISSUE THREAD

**Issue by SebastianPfliegel** [mockoon/mockoon#314]
**Is your feature request related to a problem? Please describe.**
The requests which I want to mock sometimes include certain properties and in some cases different properties (same route though). I need different rules when this property exists. Haven't found a solution for this, hope I'm not just stupid.

**Describe the solution you'd like**
Solution could be to leave value empty to only check for existance. Also viable would be to check the datatype and if doesn't match or exist don't apply the rule.

**Describe alternatives you've considered**
No alternative found.

**Additional context**
Different requests could look like:
```json
{
  "register": {}
}
```
```json
{
  "cancel": {}
}
```
They need different rules.

**Comment by 255kb** [comment]
This issue is already tracking the problem of checking if a property simply exists or not, is empty or not: https://github.com/mockoon/mockoon/issues/255
For now, it seems that checking your `cancel` property against the following regex does the trick: `^$|\s+` (Do not forget to check the "regex" checkbox).

**Comment by SebastianPfliegel** [comment]
Hah! Thought there might be a workaround (which did the trick!). Also searched for existing issues, but havent found them.

**Comment by 255kb** [comment]
Actually, it's a weird side effect of the code 😄 
Checking for emptiness on an object shouldn't be true IMO... But this is among the other things that need to be improved for responses rules!
At least it works for you in the meantime.
