### ISSUE TITLE
Allow List of Mocked Services to be Expanded Beyond 1st 2 Letters

### ISSUE THREAD

**Issue by muya** [mockoon/mockoon#316]
**Is your feature request related to a problem? Please describe.**
With the new UI having a collapsed list of mocked services, it's not always clear which service you're working with, given that one can only see the first 2 letters of the service Name

**Describe the solution you'd like**
It would be great if there was an option to keep the list permanently open, and not have to keep clicking the "hamburger" menu.

**Describe alternatives you've considered**
- Have a setting to keep the list of services expanded

**Additional context**

It's not straight-forward which service one is working with without clicking on the menu
<img width="75" alt="Mockoon" src="https://user-images.githubusercontent.com/1861055/86799075-2fe06680-c07a-11ea-86b7-424b50fbd404.png">

![2020-07-07 17 51 52](https://user-images.githubusercontent.com/1861055/86799532-b7c67080-c07a-11ea-9026-d0f32af2173c.gif)

**Comment by muya** [comment]
Something similar to the resizing feature introduced here (#104 ) could also alleviate this

**Comment by 255kb** [comment]
This will surely be covered by #386 in a way or another.
