### ISSUE TITLE
queryParam inside switch not working

### ISSUE THREAD

**Issue by mufiio** [mockoon/mockoon#325]
**Describe the bug**
Since mockoon version 1.9.0 there seems to be problem with using queryParam inside switch. For header and for example urlParam everything seems to be working fine, but for queryParam no matter of the query value provided in call, it always returns default json response. Outside switch queryParam is working as expected.

**To Reproduce**
Call for example: **GET /test?number=1**

JSON Body:
```
{{#switch (queryParam 'number')}}
{{#case '1'}}
{
    "number": "one"
}
{{/case}}
{{#case '2'}}
{
    "number": "two"
}
{{/case}}
{{#default}}
{
    "default": {{queryParam 'number'}}
}
{{/default}}
{{/switch}}
```

**Expected behavior**
Response json should be returned based on proper queryParam value provided in the call.

**Mockoon version:**
1.9.0

**OS / OS version:**
Linux Ubuntu 20.04

**Comment by 255kb** [comment]
Apparently this is also the case for `queryParam` and `body` helpers. This will be solved. Also, it will be possible to request with either strings or numbers in a `case`: `{{# case '1'}}` or `{{# case 1}}`.
