### ISSUE TITLE
Save json responses in separate file structure or folders to help in PR reviews of mockoon json

### ISSUE THREAD

**Issue by deepesh-vasthimal-cko** [mockoon/mockoon#329]
**Is your feature request related to a problem? Please describe.**
we are currently storing the entire mockoon json in a git hub repo and when we change something and create a PR its difficult to review the exact change especially if this related to a json response as it all shows in in one line and difficult / impossible to review the PR. 

**Describe the solution you'd like**
Is there a way to format the json responses to better review the PRs or store the json responses as separate file in a folder structure ?. 

**Describe alternatives you've considered**
No alternatives found yet. 

**Additional context**
N/A

**Comment by deepesh-vasthimal-cko** [comment]
file path supports this in v1.9.0.

**Comment by 255kb** [comment]
Indeed the file serving is a good candidate for this 👍
