### ISSUE TITLE
Can't select all routes

### ISSUE THREAD

**Issue by yaruna-chan** [mockoon/mockoon#330]
**Describe the bug**
When clicking around in mockoon, I cannot select all routes for all environments. The first environment's routes works fine,but for all the others, I can only select the very first route unless I press "add route" and then I can click on all routes, until I delete the new route or select a new environment

**To Reproduce**
Steps to reproduce the behavior.
Not sure
I have 9 environments, with 5 routes in the first, 8 routes in the second, 1 in the third, and then 5 in the 4th, and 1 in the rest. Maybe it's enough with only 2 environments and multiple routes, but I guess if more people had it it would have been reported already?

**Expected behavior**
It should be possible to select all routes for all environments

**Mockoon version:**
I first saw it in 1.8.0, then upgraded to 1.9.0 hoping it had been fixed, but no such luck

**OS / OS version:**
Windows 10

**Comment by 255kb** [comment]
This is quite odd. Did you create the routes normally, or did you modify the data file? 
Also, if you could share the data file here (or anonymously support@mockoon.com) it would help a lot.
You can find it by clicking the Help menu -> Show app data folder. Navigate to ./storage/environments.json

**Comment by yaruna-chan** [comment]
All routes have been added via the UI, though I don't know in which version I started adding them. I've been using mockoon for about a year I think.
Attaching enviroments file:
[environments.json.txt](https://github.com/mockoon/mockoon/files/5101039/environments.json.txt)

I also noticed now that when I move between some of the environments with only one route, it still displays the route that I previously had selected

![image](https://user-images.githubusercontent.com/33289143/90724124-4ce59780-e2be-11ea-8a40-c2707cfbb34d.png)

**Comment by 255kb** [comment]
It seems that some routes does not have an uuid, this is a bug I never encountered. Maybe something went wrong during a migration, but I cannot see what. 
I fixed the file: 
[environments_fixed.json.txt](https://github.com/mockoon/mockoon/files/5101130/environments_fixed.json.txt)
You need to copy paste the content or replace the environments.json file in your storage folder (first close the app) and it should work. 
Let me know if not.

**Comment by yaruna-chan** [comment]
You've saved me so much pain. Thank you, it helped :)
