### ISSUE TITLE
Remove API prefix when auto-mocking

### ISSUE THREAD

**Issue by 255kb** [mockoon/mockoon#333]
**Is your feature request related to a problem? Please describe.**
When auto mocking, the newly created route contains the API prefix.
If a call is made to `/api/non-existing-route`, the route will be created with `/api/non-existing-route` as path, even if `/api` is already defined as the prefix.

**Describe the solution you'd like**
Detect that a prefix is already set and create the route without it.

**Comment by sleepypikachu** [comment]
Can I pick this up @255kb?

**Comment by 255kb** [comment]
@sleepypikachu Sure you can! Be sure to add the corresponding tests :)

**Comment by sleepypikachu** [comment]
Sorry for delay, picking this up now. What is auto mock mode/How do I enable it? Cannot see a mention of it in the docs or UI 🙈

**Comment by 255kb** [comment]
No problem 😄 
Yes it may not be obvious. In the environment logs page https://mockoon.com/docs/latest/requests-logging/ there is a small "+" icon which automatically creates a route. When a global prefix is here, it will create the route with the prefix. 
The fix should be quite "easy", checking if an env prefix is present, and removing it from the newly created route's path.
Don't forget to add an automated test there: https://github.com/mockoon/mockoon/blob/master/test/suites/environment-logs.spec.ts#L221 (probably the best place). 
And if you have any question or want to chat: https://spectrum.chat/mockoon
