### ISSUE TITLE
MongoDB's ObjectId support on templating

### ISSUE THREAD

**Issue by lukefx** [mockoon/mockoon#342]
When using MongoDB, ObjectIds are used as Id, I use them in an API and this templating feature will save me a lot of time.

**Describe the solution you'd like**
I added a template function to generate random [ObjectId](https://docs.mongodb.com/manual/reference/method/ObjectId/#description), they look like: 507f1f77bcf86cd799439011

https://github.com/mockoon/mockoon/compare/master...lukefx:templating_objectid

**Describe alternatives you've considered**
There is a GUID and faker UUID function but they are not exactly the same.

**Additional context**
I already created the function, but I need some time to understand how you text the templating, right now for me tests fail because the window takes a lot of time to start and load the test environment json file.

**Comment by 255kb** [comment]
Thank you for opening this issue @lukefx 
Feel free to open a PR so I can review this properly. 
Concerning the tests I can add them if you want, it will probably take way less time for me as I wrote them 😃 .

**Comment by lukefx** [comment]
Thank you @255kb, I would love to understand a bit how you test the app to maybe contribute more in the future but the templating tests are based on some json, how do you test functions that return random values?

**Comment by 255kb** [comment]
Would you mind joining the chat? https://spectrum.chat/mockoon?tab=posts
It will be easier :)
