### ISSUE TITLE
Response colors

### ISSUE THREAD

**Issue by feraguiba** [mockoon/mockoon#345]
When you add a response to a route, the content-type is not set and therefore the response is not colored according to the content-type.

**Comment by 255kb** [comment]
Hi @feraguiba, could you please elaborate a bit, I am not sure I understand what the issue is? 
Also, it would be great if you could modify your issue to follow the issue template. Thank you

**Comment by feraguiba** [comment]
I was capturing screenshots and I realized I hadn't set the response content-type.
When I set the content-type the response was correctly syntax highlighted, so I close the bug. I had in mind that in previous versions the response was being automatically syntax highlighted???

**Comment by 255kb** [comment]
There is no default content-type on routes. However, you can set global environments headers (click on the "cog" icon in the upper right corner). The route content-type (and thus the syntax highlighting) is either taken from the global content-type header, or the route's content-type header if provided.
