### ISSUE TITLE
Support multipart/form-data values in targets in rules

### ISSUE THREAD

**Issue by paulsavoie** [mockoon/mockoon#347]
**Is your feature request related to a problem? Please describe.**
I cannot return different responses depending on values in the request body if the request is in a multipart/form-data encoding.

**Describe the solution you'd like**
Support selecting values from multipart/form-data request bodies when defining rules for response selection.

Describe alternatives you've considered
Haven't found any. Will not change our API just to be in line with features of Mockoon.

Additional context
Nothing. Great tool!

**Comment by 255kb** [comment]
Hi @paulsavoie it's true that Mockoon does no support yet `multipart/form-data`, only `application/json` and `application/x-www-form-urlencoded`.
Could you please edit your issue and follow the feature template? Thank you

**Comment by 973782523** [comment]
![image](https://user-images.githubusercontent.com/34543652/104549553-15f98f00-566e-11eb-93b2-1be4604b669d.png)
I found that the form-data is available, but I can't manipulate it

**Comment by 255kb** [comment]
@973782523 as stated above, `multipart/form-data` is not yet supported. 
If implemented it should work like this `{{body 'A'}}`. The `body` helper without parameter returns the full body "as is".

**Comment by 973782523** [comment]
Can I support this function in the later stage?I think that would be perfect
![image](https://user-images.githubusercontent.com/34543652/104978793-a7d21500-5a3d-11eb-9c1d-d9009900ae7d.png)

**Comment by roybarber** [comment]
Any traction on this @255kb ? Or is there a way to just accept the data and return a 200 by default. Currently, it just falls over.

**Comment by 255kb** [comment]
@roybarber It's not planned yet. Also, there is no alternative. 
I will add it to the roadmap, I will investigate but it shouldn't be a huge change 🤞

**Comment by Kaedeko** [comment]
Echoing a need for this, form-data is a reasonably common use case, being unable to use dynamic rules is a bit of a pain.

**Comment by iamike** [comment]
Is this problem has been solved?

**Comment by 255kb** [comment]
@iamike Not planned yet, issue is still opened.

**Comment by roybarber** [comment]
@255kb awesome progress. Thank you 🥰

**Comment by 255kb** [comment]
> @255kb awesome progress. Thank you 🥰

You're welcome 😄 
Better late than never!

**Comment by iamike** [comment]
thank you
