### ISSUE TITLE
Question: Repeat up to X minute

### ISSUE THREAD

**Issue by guilhermecgs** [mockoon/mockoon#351]
Hi folks,

Is there a way to repeat an array x times, where X is the number of minutes in current timestamp?

Example: now = 18h 25m -> repeat 25 times

What I want is to simulate an array increasing its size over time.

**Comment by guilhermecgs** [comment]
`{{# repeat {{now 'mm'}}) }}`


did not work

**Comment by 255kb** [comment]
hi @guilhermecgs 
It should work like this:

```
{{#repeat (now 'mm')}}
something
{{/repeat}}
```

You cannot have multiple nested `{{ }}` but you can use multiple helpers inside, and use the parenthesis to define the precedence.
