### ISSUE TITLE
Need add couple functions for getting shifted date and time

### ISSUE THREAD

**Issue by zelenovas** [mockoon/mockoon#355]
**Is your feature request related to a problem? Please describe.**
Need add couple functions for getting shifted date and time (e.g. 1 hour before now OR yesterday date but 1 year ago).

**Describe the solution you'd like**
for time: 
```
{{ timeShift 'format' hours minutes seconds }}
{{ timeShift 'HH:mm:ss' -1 }}  
```
for date: 
```
{{ dateShift 'format' days months years }}
{{ dateShift 'yyyy-MM-dd' -1 0 -1 }}
```

**Describe alternatives you've considered**
Haven't found any alternatives.

**Additional context**
No.

**Comment by sotcha** [comment]
This is a really nice feature but I don't get why should be a **timeShift** and a **dateShift** and not a **dateTimeShift**.

I mean the **dateTimeShift** covers the case where I want to shift 1 day and 2 hours.

**Comment by 255kb** [comment]
I agree with @sotcha 
We should have one helper doing all the shifts we wants (from years to ms).

**Comment by SimonPStevens** [comment]
@zelenovas I'm happy to take what you've done and combine it into a single datetimeshift, unless you want to do it?

**Comment by zelenovas** [comment]
@SimonPStevens 
Awesome! Thanks!
I agree, one combined function is better.
