### ISSUE TITLE
Pass-through

### ISSUE THREAD

**Issue by strarsis** [mockoon/mockoon#359]
**Is your feature request related to a problem? Please describe.**
It would be nice to allow Mockoon to pass-through all non-matching HTTP requests, e.g. to a sandbox/production API server.

**Describe the solution you'd like**
A passthrough rule (that can be also applied globally) for a HTTP API server to which all non-matching requests should be passed to.
Alternatively, a feature to "clone"/record the API requests and responses and then being able to play them back later.

**Comment by 255kb** [comment]
You can already achieve this with the [proxy mode](https://mockoon.com/tutorials/partial-mocking-proxy/) 😃 
Do not hesitate to join us on the [chat ](https://spectrum.chat/mockoon) if you have any question!
