### ISSUE TITLE
In the logs, the jsons are not prettyfied

### ISSUE THREAD

**Issue by avifatal** [mockoon/mockoon#368]
continuing from: https://github.com/mockoon/mockoon/discussions/367
Hi,
When I'm looking at the logs. I try to view the JSON body.
The colors are working, but it appears to be in one row, which is impossible to read.
Is this a bug?
Images attached below.
![image](https://user-images.githubusercontent.com/12430740/99351799-1235d000-28aa-11eb-88d4-0bbc887ca265.png)

![image](https://user-images.githubusercontent.com/12430740/99351808-15c95700-28aa-11eb-9df4-1797e8bddf44.png)

Thanks

**Comment by 255kb** [comment]
@avifatal Thank you for opening this issue. Could you please edit it so it follows the issue template? https://github.com/mockoon/mockoon/issues/new?template=Feature_request.md
Thank you 👍

**Comment by barefootdeveloper** [comment]
I know this doesn't quite fit the request issue format, but I'd like to take a shot at this.

I'm thinking something like this:

![Snag_1bbc6403](https://user-images.githubusercontent.com/3580448/118638878-4b8dc080-b7a5-11eb-86eb-feba171f94e0.png)

The formatted would only show up whenever it's a supported content-type (application/json to start, other formats to follow)
We could later expand this to support more advanced formatting such as color-coded and expanding and collapsing JSON content.

**Comment by 255kb** [comment]
The main reason we are currently showing the raw content as text is because the size of this content can be huge and it's truncated (limit is set in the app settings). Displaying everything and/or formatting the JSON could slow down the UI. That's why you can click on "View full body in editor". Still, opening this modal can be a really intensive task depending on the content. I think it would be better to keep this behavior and only format when the editor is opened.

**Comment by 255kb** [comment]
Then, I think having the tab + the modal is redundant. I would prefer to regroup editor and formatting at one place, maybe in the modal to reduce the amount of work. Then it's just a matter of stringifying JSON with the correct indentation and showing it in the editor.
Also, I would prefer to avoid a warning which basically translates to "UI perfs are bad, are you sure you want to use it?". I think we can safely ignore cases where the entering body is huge for now. Also, the only real solution to perfs issues I see is something like loading the editor in it's own browser window, so we get to work in a new thread. But this is overkill for a "debug" view in my opinion.

**Comment by 255kb** [comment]
📦 This was improved in [v8.1.0](https://mockoon.com/releases/8.1.0/)
