### ISSUE TITLE
Mocks added by clicking the add mock button will be added to the end of the list 

### ISSUE THREAD

**Issue by volkerrichert** [mockoon/mockoon#377]
If a new mock is added by click in env log

![image](https://user-images.githubusercontent.com/640914/100746212-b2c6dc80-33e0-11eb-89a8-1ccf42ee38a0.png)

 it will be added to the end of the mock list. After starting the mock server this mock will not be used if it's based on a mock with a route parameter.

![image](https://user-images.githubusercontent.com/640914/100746403-f0c40080-33e0-11eb-8fde-bbc49d961c17.png)

This one will match fist.

I'd like to have the new mock above the mock with route parameter to make it more "important".

**Comment by mauriceackel** [comment]
Hey @volkerrichert, is this issue still present with the most recent version of Mockoon? I was trying to reproduce this but were not able to. Please note that in version 1.12.0 you can definitely drag & drop routes to change their precedence. Routes that are higher up will be served first on a match.

Let me know if this solves this issue 🎉

**Comment by volkerrichert** [comment]
This is just a usage issue. I can rearrange them, sure. But a rule like

"/test/special" should be inserted befor the general rule "/test/:param".

**Comment by 255kb** [comment]
While I understand your concern, I am wondering: how do we know that `special` in `/test/special` is a special route, and not a value for the `:param`? I don't think we can distinguish both cases reliably. Thus, implementing this would probably result in something odd most of the time.

**Comment by volkerrichert** [comment]
`special` was meant to be a value of `:param`. ;-) So this is a kind of rule, but hey.... To be honest, adding it as a `real` rule would be much nicer, with a simple popup "Add this as a rule to `/test/:param`? yes/no" But a bit more complicate, thats why i ask to put it above the rule.

**Comment by 255kb** [comment]
Yes, this is indeed a bit more complex feature. 
But in this case I don't see the value of adding the route `/path/special` above `/path/:param` if it shouldn't exists in the first place.

**Comment by volkerrichert** [comment]
ok, no problem

**Comment by 255kb** [comment]
@volkerrichert Don't get me wrong, I am genuinely asking 😃 
Your idea of creating a new response + rule from a mock is a nice one, though it would require a new issue with a little more details. And maybe it wouldn't be in a high priority on the roadmap. 
But then I don't see how adding a new route above the parameterized route solve your issue. I think it does quite the opposite which make me think that we shouldn't implement it.

**Comment by volkerrichert** [comment]
That's totally fine... :-)

Adding as a rule is much more elegant... I'll and an issue
