### ISSUE TITLE
Allow a setting option to keep environment panel expanded at all times

### ISSUE THREAD

**Issue by bhagatparwinder** [mockoon/mockoon#386]
**Is your feature request related to a problem? Please describe.**
Currently, the environment panel stays collapsed by default. There is no option to keep it expanded. 

![image](https://user-images.githubusercontent.com/6809087/102402429-59e37080-3faa-11eb-8f85-30dad445ed7d.png)

**Describe the solution you'd like**
A settings option will be great

**Comment by izerozlu** [comment]
@255kb is this a valid request by your side? If so where would the option to pin the environments be?

**Comment by 255kb** [comment]
@izerozlu Yes definitely. I can imagine that the UI I chose for the collapsed menu may not be good for everyone, so there is room for improvements. 
I would keep it collapsed by default and add a new checkbox in the settings modal. 
It will require a lot of testing to see if everything plays well, especially when resizing the routes and logs columns, the main window, etc
We could also make it resizable like the other columns. 

As it is a major UI change I don't want to rush this out. We can discuss on the [Discord server](https://discord.gg/JmTBk59MTb) if you want to work on this.

**Comment by codeability-ab** [comment]
Good idea. Also add an option to not float the environments panel on top of the list of routes. I want to be able to click through my environments and see the environment names and routes at the same time.

Thanks for a great tool! 

/johan

**Comment by 255kb** [comment]
@codeability-ab thanks for your feedback! This is definitely on the roadmap. However, it's kind of a headache as many users have different opinions. After recent discussions with some members of the community I came to the conclusion that we should get rid of this left menu in favor of a dropdown at the top (and also get rid of the environment specific options at the top (prefix, port, etc) that could migrate in the settings panel https://github.com/mockoon/mockoon/issues/246). This could help declutter the UI a bit and also, a vast majority of users have only one or two environments. 

Here is a quick mockup of how it could look: 
![image](https://user-images.githubusercontent.com/7489814/116220062-9a1ee080-a74c-11eb-8b7f-d85a54ffc24a.png)

Another idea could be having tabs at the top for each environment. With the ability to open and close them at will (like VSCode or Gitkraken). 
![image](https://user-images.githubusercontent.com/7489814/116220973-74dea200-a74d-11eb-84d2-156535e84058.png)
 This could also play well with a planned refactoring of the storage engine #16 which aims to make environments more independent from each others. 

Now that I think about it, I guess the second idea could be interesting to explore, solve most of the "problems" (cluttered UI, mostly useless top bar, left menu taking too much space, 2 letters in the left menu being not enough), and is more in line with other apps on the market. 

Let me know what you think, I am definitely open to feedback and suggestions 😃

**Comment by codeability-ab** [comment]
I would prefer to have a resizable panel to the left that is visible without covering the routes list. Like it was in a previous version of Mockoon.

But the dropdown menu is definitely a lot better than the collapsed panel in the current version. The selected environment name is readable!

I have an obsession with prefixing everything so my collapsed list of environments reads Ec, Ec, Ec, Ec, Ec,... not very useful :-)
best regards Johan

**Comment by 255kb** [comment]
After discussing this with more people it seems we are heading toward something like this:
![Untitled4](https://user-images.githubusercontent.com/7489814/116849865-d12f3f00-abef-11eb-8d29-0dc9f66c0944.png)
(with resizable environments menu)
I think it's a great tradeoff between not loosing too much information and having a clearer interface regarding the data hierarchy.

**Comment by codeability-ab** [comment]
Oh.. look at that! You would end up with a collapsed list reading FT, FT, FT :-)

Looks like a great way to go!

/Johan

**Comment by 255kb** [comment]
@codeability-ab ahah true :) 
But that was just a quick mockup, idea is to make the menu resizable, while also getting rid of the 2 characters limit, which seems to be a pain for a lot of people 😅

**Comment by 255kb** [comment]
This UI improvement is needed by #16 as we add more info / UI elements for each environment. 
The scope of this issue will be limited to the environment menu collapse/size and the rest of the proposed redesign will be part of another issue #509.
