### ISSUE TITLE
Add concat templating helper

### ISSUE THREAD

**Issue by suvhsmnt** [mockoon/mockoon#391]
`**Is your feature request related to a problem? Please describe.**

my request body is 
```
{
  "A" : [
    {   "test" : "1" },
    {   "test" : "2" }
  ]
}
```

and i want my response body to be 

```
[
  {   "test" : "1", "status": "true"  },
  {   "test" : "2" , "status": "false"}
]

```
I have done 

```
[
  {{#repeat (body 'A.length')}}
    {
        "fatId": "{{body ('A.' @index '.test') }}", //here i am not getting the proper indexed value 
      "status": true,  //whatever i am not concerned with this field
    }
   {{/ repeat }}
]
```

**Describe the solution you'd like**
Create a `concat` Handlebars helper to be able to use `@index` inside any other helper parameters

**Comment by 255kb** [comment]
The syntax you are using is invalid. You cannot have imbricated `{{ }}`. And `faker` is actually for using helpers from [Faker.js](https://github.com/Marak/faker.js).
Also, I am afraid you cannot get "any" index you want in the array. You need to actually provide it to the `body` helper: 
`body 'A.0.test'`
The only way to achieve what you want to do would be to concatenate the `@index` variable available in the `#repeat` inside the `body` helper. But we don't have a `concat` helper yet. 
I will rename this issue so we create one.

The implementation would allow to do something like this:
```
[
  {{#repeat (body 'A.length')}}
  {
    "test": "EMAIL_{{body (concat 'A.' @index '.fatId') }}", 
    "status": true,
  }
  {{/ repeat }}
]
```

**Comment by suvhsmnt** [comment]
> The syntax you are using is invalid. You cannot have imbricated `{{ }}`. And `faker` is actually for using helpers from [Faker.js](https://github.com/Marak/faker.js).
> Also, I am afraid you cannot get "any" index you want in the array. You need to actually provide it to the `body` helper:
> `body 'A.0.test'`
> The only way to achieve what you want to do would be to concatenate the `@index` variable available in the `#repeat` inside the `body` helper. But we don't have a `concat` helper yet.
> I will rename this issue so we create one.
> 
> The implementation would allow to do something like this:
> 
> ```
> [
>   {{#repeat (body 'A.length')}}
>   {
>     "test": "EMAIL_{{body (concat 'A.' @index '.fatId') }}", 
>     "status": true,
>   }
>   {{/ repeat }}
> ]
> ```

thanks for replying can you please tell me till when should i expect the **helper concat**  ?? thanks in advance

**Comment by 255kb** [comment]
Don't expect something before end of January at least.
