### ISSUE TITLE
When I use faker random.alphaNumeric, mockoon cannot response anymore

### ISSUE THREAD

**Issue by eliseubamaral** [mockoon/mockoon#400]
**Describe the bug**
When I use {{faker 'random.alphaNumeric' 999999999}} on body, the app start loading and not return any response. I think the app is crashing because I need to shutdown the app to use again.

**To Reproduce**
Just use use that expression on body {{faker 'random.alphaNumeric' 999999999}}

**Expected behavior**
I expected an alpha numeric return on response

**Screenshots**

**Mockoon version:**
1.11.0

**OS / OS version:**
Mac OS

**Comment by 255kb** [comment]
This is not related to this helper specifically. By doing this you are generating a massive amount of data (1 billion random characters). It's currently taking a lot of time and in the meanwhile, blocking the main thread. Eventually, if you wait long enough you should get the result you expect. 
I will track the fact that the UI is blocked/unresponsive in a separated issue. But concerning the time it takes to generate this amount of data, I won't be able to improve it. We are here dependent on NodeJS and the libs we are using.
