### ISSUE TITLE
Rule not working

### ISSUE THREAD

**Issue by PeterSt78** [mockoon/mockoon#402]
**Describe the bug**
Hi
I am a newbie in mockoon. 
I wanted to make multiple responses with rules. if status ok then send the 2nd response, otherwise (nok or default) the 1st one 

**To Reproduce**
{
    "source": "mockoon:1.11.0",
    "data": [
        {
            "type": "environment",
            "item": {
                "uuid": "",
                "lastMigration": 13,
                "name": "A8000 API",
                "endpointPrefix": "",
                "latency": 0,
                "port": 3000,
                "routes": [
                    {
                        "uuid": "",
                        "documentation": "A8000 API",
                        "method": "post",
                        "endpoint": "cgi-api",
                        "responses": [
                            {
                                "uuid": "",
                                "body": "{\n  \"sessionId\": \"\"\n}",
                                "latency": 100,
                                "statusCode": 200,
                                "label": "NOK",
                                "headers": [],
                                "filePath": "",
                                "sendFileAsBody": false,
                                "rules": [
                                    {
                                        "target": "body",
                                        "modifier": "status",
                                        "value": "nok",
                                        "isRegex": false
                                    }
                                ],
                                "rulesOperator": "OR",
                                "disableTemplating": false
                            },
                            {
                                "uuid": "",
                                "body": "{\n  \"sessionId\": \"newSessionId\"\n}",
                                "latency": 0,
                                "statusCode": 200,
                                "label": "OK",
                                "headers": [],
                                "filePath": "",
                                "sendFileAsBody": false,
                                "rules": [
                                    {
                                        "target": "body",
                                        "modifier": "status",
                                        "value": "ok",
                                        "isRegex": false
                                    }
                                ],
                                "rulesOperator": "OR",
                                "disableTemplating": false
                            }
                        ],
                        "enabled": true,
                        "randomResponse": false
                    }
                ],
                "proxyMode": false,
                "proxyHost": "",
                "https": false,
                "cors": true,
                "headers": [
                    {
                        "key": "Content-Type",
                        "value": "application/json"
                    },
                    {
                        "key": "Access-Control-Allow-Origin",
                        "value": "*"
                    },
                    {
                        "key": "Access-Control-Allow-Methods",
                        "value": "GET,POST,PUT,PATCH,DELETE,HEAD,OPTIONS"
                    },
                    {
                        "key": "Access-Control-Allow-Headers",
                        "value": "Content-Type, Origin, Accept, Authorization, Content-Length, X-Requested-With"
                    }
                ],
                "proxyReqHeaders": [
                    {
                        "key": "",
                        "value": ""
                    }
                ],
                "proxyResHeaders": [
                    {
                        "key": "",
                        "value": ""
                    }
                ]
            }
        }
    ]
}

**Expected behavior**
if status = ok then 2nd response
**Screenshots**
![image](https://user-images.githubusercontent.com/60769589/104636376-8f5fa480-56a3-11eb-9a97-0fd0a2ad40e5.png)
![image](https://user-images.githubusercontent.com/60769589/104636413-9e465700-56a3-11eb-8ccf-5ec1822e4c15.png)
![image](https://user-images.githubusercontent.com/60769589/104636450-abfbdc80-56a3-11eb-85ab-2e83eaa287a5.png)
![image](https://user-images.githubusercontent.com/60769589/104636486-b74f0800-56a3-11eb-848e-bc651785a44a.png)
![image](https://user-images.githubusercontent.com/60769589/104636574-d8175d80-56a3-11eb-8483-39798a5c779b.png)
![image](https://user-images.githubusercontent.com/60769589/104636592-e1082f00-56a3-11eb-9537-6104166e2bca.png)

**Mockoon version:**
1.11.0
**OS / OS version:**
Windows 10

**Comment by 255kb** [comment]
I see where the problem is coming from. The entering request has a `application/x-www-form-urlencoded` Content-Type. You need to send an explicit `application/json` Content-Type for Mockoon to parse the body as JSON (you can also "query" `x-www-form-urlencoded` content, but here it's JSON being sent with the wrong Content-Type).
Hope this help!

**Comment by PeterSt78** [comment]
GREAT - It works
Thank you very much

**Comment by 255kb** [comment]
You're welcome 🎉
