### ISSUE TITLE
Can't scroll pane

### ISSUE THREAD

**Issue by thiagofloriano** [mockoon/mockoon#410]
**Describe the bug**
Can't access some content because there's no way to to scroll the panes.

**To Reproduce**
Just use the app with Ubuntu.

**Expected behavior**
I've expected a single scroll bar or scrolling with arrow keys.

**Mockoon version:**
1.11.0

**OS / OS version:**
Linux Ubuntu 20.04 lts

**Comment by 255kb** [comment]
@thiagofloriano I tested with both Ubuntu 18 and 20 and noticed nothing odd. I am able to scroll in all the lists (envs, routes, logs, etc) Could you please provide screenshots, and/or a way to reproduce this?
