### ISSUE TITLE
Importing environment breaks environment settings

### ISSUE THREAD

**Issue by TillThomas** [mockoon/mockoon#415]
**Describe the bug**
The environment settings are shared/ are being overwritten between different environments in the app.
**To Reproduce**
WHEN: multiple environments are open
AND: a new environment is imported (mockoon.json or swagger.json)
THEN: changes to port/proxy etc. apply to all environments

imported json:
```json
{
    "source": "mockoon:1.11.0",
    "data": [
        {
            "type": "environment",
            "item": {
                "uuid": "",
                "lastMigration": 13,
                "name": "Report API Documentation",
                "latency": 0,
                "port": 5557,
                "routes": [],
                "proxyMode": false,
                "proxyHost": "",
                "https": false,
                "cors": true,
                "headers": [],
                "proxyReqHeaders": [
                    {
                        "key": "",
                        "value": ""
                    }
                ],
                "proxyResHeaders": [
                    {
                        "key": "",
                        "value": ""
                    }
                ]
            }
        }
    ]
}
```

This environment import works as expected:
```json
{
    "source": "mockoon:1.11.0",
    "data": [
        {
            "type": "environment",
            "item": {
                "uuid": "",
                "lastMigration": 13,
                "name": "ProcedureSearch API",
                "endpointPrefix": "",
                "latency": 0,
                "port": 5556,
                "routes": [],
                "proxyMode": true,
                "proxyHost": "https://myHost/",
                "https": false,
                "cors": true,
                "headers": [
                    {
                        "key": "Content-Type",
                        "value": "application/json"
                    },
                    {
                        "key": "Access-Control-Allow-Origin",
                        "value": "*"
                    },
                    {
                        "key": "Access-Control-Allow-Methods",
                        "value": "GET,POST,PUT,PATCH,DELETE,HEAD,OPTIONS"
                    },
                    {
                        "key": "Access-Control-Allow-Headers",
                        "value": "Content-Type, Origin, Accept, Authorization, Content-Length, X-Requested-With"
                    }
                ],
                "proxyReqHeaders": [
                    {
                        "key": "",
                        "value": ""
                    }
                ],
                "proxyResHeaders": [
                    {
                        "key": "",
                        "value": ""
                    }
                ]
            }
        }
    ]
}
```

After deleting the imported environment and restarting the app everything works as expected. 

**Expected behavior**
Changes to environment settings can be made to each environment independently.

**Screenshots**

**Mockoon version:**
1.11.0

**OS / OS version:**
Windows 10

I appreciate your help. I love your app!
I will look for a workaround with the cli.

**Comment by TillThomas** [comment]
When importing a swagger definition and exporting a mockoon environment the property `"endpointPrefix"` is missing from the exported myMockoonEnv.json, importing the file with the missing property seems to lead to the bug.

**Comment by 255kb** [comment]
Hi @TillThomas Thanks for reporting this. 
I tested your import data and there is indeed a bug, but it does not seem related to the endpointPrefix, but rather the fact that there is no route in the `routes` array. Surprisingly, I never accounted for that case 😱 
Could you please check in your logs to see if you had the same error and copy past it here? (Help menu --> "Show app data folder", then navigate to the bottom of  `./mockoon/logs/renderer.log`

**Comment by TillThomas** [comment]
Sorry I removed the routes. I should have said.
I will give you the log.

**Comment by TillThomas** [comment]
[renderer.log](https://github.com/mockoon/mockoon/files/5944061/renderer.log)
[swaggerDefinition.zip](https://github.com/mockoon/mockoon/files/5944062/swaggerDefinition.zip)



This is the error log and the swaggerDefinition that leads to the error. I also attached the export of the environment in the mockoon format.

**Comment by 255kb** [comment]
Thank you, I will investigate and fix for the next release. It's indeed different from the empty route array bug. I will open a second issue.

**Comment by TillThomas** [comment]
Thank you so much.
It's working with manually adding the property `"endpointPrefix": ""` to the json.

**Comment by 255kb** [comment]
Good to know, at least there is a workaround!
Next version should be out soon, definitely this month (🤞)
