### ISSUE TITLE
Rules are not executed in order of priority

### ISSUE THREAD

**Issue by Maritims** [mockoon/mockoon#419]
**Describe the bug**
Given 3 different responses with 3 rules all operating on the same query parameter one would expect that rules are executed in order of priority. This does not appear to be the case. By order of priority I mean the order in which I sort my responses in the response dropdown when looking at a route.

**To Reproduce**

1. Decide on a query parameter to operate on. For this example I will use the query parameter foo. Foo can occur multiple times in the query string with various values. These values should in a production scenario dictate the criteria for the response from the production API.
2. Create three responses. Let's name them "Foo with 1 value", "Foo with 2 values" and "Foo with 3 values".
3. Add a rule to "Foo with 1 value". Set the rule to be based on the query string. Set the criteria to foo=bar.
4. Add two rules to "Foo with 2 values". Set the rule criteria to be foo=bar and foo=baz.
5. Add three rules to "Foo with 3 values". Set the rule criteria to be foo=bar, foo=baz and foo=helloworld.
6. Set the response body to whatever for these three responses.

You will notice that as long as foo=bar you will never reach the rules described in step 4 and 5. You will always hit rule 3 because priority is not taken into account. Responses can be ordered in the response dropdown, but this seems to only give a visual effect in the program GUI. I would expect this to actually mean priority of execution.

I've tried to make a workaround with some negative lookaround regular expressions, but without any luck.

**Expected behavior**
I expect that the order in which I order my responses is the order in which the rules are executed.

**Mockoon version:**
1.11.0

**OS / OS version:**
Windows 10

**Comment by mauriceackel** [comment]
@Maritimsn Can you check whether this is still the case in version 1.12? I'm currently trying to reproduce this behavior but for me it works fine and the order chosen in the GUI is respected. Maybe you can add a Mockoon export of your environment and the exact URL you are querying.

**Comment by 255kb** [comment]
As @mauriceackel explained, rules are always executed in the order the responses are defined, then in the order rules are defined. First come first served.
That being said, when the rules "engine" encounters a query params arrays (either `foo[]=bar&foo[]=baz` or `foo=bar&foo=baz`), it will use `array.includes` method to find value in it. 
So with two rules: 
1. foo = bar
2. foo = bar AND foo = baz

The rule 1 will act like a catch-all and `['bar', 'baz'].includes('bar')` will always be true.

The solution is to actually reverse the order of the responses so the one with the most specific rules is checked first. 
Try with the following setup: 
1. 500 - no rules (default response)
2. foo = bar AND foo = baz
3. foo = bar

Call with `foo[]=baz&foo[]=bar` --> response 2
Call with `foo[]=test&foo[]=bar` --> response 3
Call with `foo[]=test&foo[]=baz` --> response 1

In this regards the feature is working well. The idea is to mimic how endpoint are being interpreted (`/path/:id` should be after `/path/action`) and keep the rules feature as simple as possible.
