### ISSUE TITLE
Adding a trailing slash to the API prefix leads to a duplicated slash in route declaration and a 404

### ISSUE THREAD

**Issue by 255kb** [mockoon/mockoon#422]
**Describe the bug**
When setting up an API prefix with a trailing slash `myprefix/`, server endpoint is declared with two consecutive slashes:
`/myprefix//path`

**To Reproduce**
Add a trailing slash to the prefix

**Expected behavior**
Should not return 404. 
Should deduplicate the slash in the Commons lib and prevent entering a trailing slash in the UI

**Comment by uday060** [comment]
Shall I work and fix this issue?

**Comment by 255kb** [comment]
Sure @uday060 you can. 
Two modifications are required: 
- update the mockoon/commons library so it trims the trailing slash from the `endpointPrefix`
- update the valid-path directive in this app (maybe add an `@Input` option "trailingSlash: boolean") to trim the trailing slash + add one more case to the ui-interaction test

Let me know if you are in and do not hesitate to join the [Discord server](https://discord.gg/MutRpsY5gE) to discuss further.
