### ISSUE TITLE
Installation is failed using latest Homebrew in macOS

### ISSUE THREAD

**Issue by kawarimidoll** [mockoon/mockoon#424]
**Describe the bug**

The command `brew cask install` in `README.md` doesn't work now because of update of Homebrew.
This is not a bug of this app, but the document needs to be fixed.

homebrew discussions: [Error: Calling brew cask install is disabled! · Discussion #340 · Homebrew/discussions](https://github.com/Homebrew/discussions/discussions/340#discussioncomment-232364)

> `brew cask <command>` was deprecated in favor of `brew <command> --cask` in Homebrew 2.6.0. Now that 2.7.0 has been released, they have been disabled.

homebrew blog: [2.6.0 — Homebrew](https://brew.sh/2020/12/01/homebrew-2.6.0/)

> All brew cask commands have been deprecated in favour of brew commands (with --cask) when necessary

**To Reproduce**
Run `brew cask install mockoon`.

**Expected behavior**
Installation is success.

**Screenshots**
![Unknown command: cask](https://user-images.githubusercontent.com/8146876/110070729-f1907800-7dbd-11eb-84b3-5b70fa7bfaf6.png)

**Mockoon version:**
Not relevant.

**OS / OS version:**
macOS 11.2.1
Homebrew 3.0.4

**Comment by 255kb** [comment]
Thanks for spotting this @kawarimidoll !
