### ISSUE TITLE
Enviroment name/port prefix etc. will not be updatenetg

### ISSUE THREAD

**Issue by volkerrichert** [mockoon/mockoon#428]
**Describe the bug**
If you change the env the top en data will no updated (name, port etc.) when changing env

**To Reproduce**
- start mockoon an switch between multiple env. This work fine.
- click inside the result `body` of the currently displayed route
- change env
- the env data will not be updated anymore

**Expected behavior**
Always update the env data

**Mockoon version:**
seen in 1.11.0 + 1.12.0

**OS / OS version:**
Windows 10

**Comment by 255kb** [comment]
This is quite a serious bug that I cannot reproduce (and never had since a long time). 
Could you please export and share your data so I can see if it's related to them?

**Comment by volkerrichert** [comment]
I try to break it down. There are some NDA related data in my setup.
maybe some screen sharing?

**Comment by volkerrichert** [comment]
But it seems to be one specific collection.

i looked into my data folder and found

```
[2021-03-05 12:54:55.396] [error] [APPLICATION]Unexpected error: Must supply a value for form control with name: 'endpointPrefix'. - Error: Must supply a value for form control with name: 'endpointPrefix'.
    at file:///C:/Users/Volker/AppData/Local/Programs/mockoon/resources/app.asar/main.d661a3fc2ba17d1ca8e6.js:1:4835630
    at file:///C:/Users/Volker/AppData/Local/Programs/mockoon/resources/app.asar/main.d661a3fc2ba17d1ca8e6.js:1:4834914
    at Array.forEach (<anonymous>)
    at Hr._forEachChild (file:///C:/Users/Volker/AppData/Local/Programs/mockoon/resources/app.asar/main.d661a3fc2ba17d1ca8e6.js:1:4834874)
    at Hr._checkAllValuesPresent (file:///C:/Users/Volker/AppData/Local/Programs/mockoon/resources/app.asar/main.d661a3fc2ba17d1ca8e6.js:1:4835585)
    at Hr.setValue (file:///C:/Users/Volker/AppData/Local/Programs/mockoon/resources/app.asar/main.d661a3fc2ba17d1ca8e6.js:1:4833723)
    at u._next (file:///C:/Users/Volker/AppData/Local/Programs/mockoon/resources/app.asar/main.d661a3fc2ba17d1ca8e6.js:1:5195179)
    at u.__tryOrUnsub (file:///C:/Users/Volker/AppData/Local/Programs/mockoon/resources/app.asar/main.d661a3fc2ba17d1ca8e6.js:1:1427614)
    at u.next (file:///C:/Users/Volker/AppData/Local/Programs/mockoon/resources/app.asar/main.d661a3fc2ba17d1ca8e6.js:1:1426835)
    at l._next (file:///C:/Users/Volker/AppData/Local/Programs/mockoon/resources/app.asar/main.d661a3fc2ba17d1ca8e6.js:1:1426006)
```

After that error pops up, the env UI-fields will not updated anymore

**Comment by 255kb** [comment]
@volkerrichert if you could share just the beginning of your `~/{app_data_folder}/mockoon/storage/environment.json` so I can see what is in the `endpointPrefix` that would be great. You can also join me on [Discord](https://discord.com/invite/JmTBk59MTb) to share it privately.

**Comment by volkerrichert** [comment]
it's simply missing in that env.

**Comment by 255kb** [comment]
really? that is strange. There is currently no data validation when the app loads. This is planned in a near future. 
Did you modify the data manually?

**Comment by volkerrichert** [comment]
No, i haved. After adding it it works fine.

**Comment by volkerrichert** [comment]
THX for that hint

**Comment by 255kb** [comment]
ok, did you imported it from an openapi spec file?

**Comment by volkerrichert** [comment]
yes, it was imported form an openAPI v3 Sepc

**Comment by 255kb** [comment]
Could you share these specs? at least the beginning where `servers` and other root things are defined.

**Comment by volkerrichert** [comment]
Stop... I was an mockoon export from a customer. It's missing in that mockoon.json.

**Comment by volkerrichert** [comment]
```

    "source": "mockoon:1.11.0",
    "data": [
        {
            "type": "environment",
            "item": {
                "uuid": "",
                "lastMigration": 13,
                "name": "ntas-mock",
                "latency": 0,
                "port": 3000,
                "routes": [.....
```

**Comment by 255kb** [comment]
Still, I wonder how endpointPrefix disappeared. Is it a bug somehow or a manual mistake 🤔 
Please, if you encounter this again, try to come up with a reproductible example and reopen the issue. That would help a lot! 👍

**Comment by volkerrichert** [comment]
ok!

**Comment by volkerrichert** [comment]
The customer promives not to have manually edit the json.

**Comment by 255kb** [comment]
@volkerrichert thanks for the feedback. If by any chance you can get your hand on the original OpenAPI spec, let me know, that would be great.

**Comment by volkerrichert** [comment]
I'll try

**Comment by volkerrichert** [comment]
Ok, i can share the origilan openAPI spec, but i tried to import it 3 times.. Works as expected. Sorry. I Think we can close it as "not repoducable"

**Comment by 255kb** [comment]
I tried to alter some OpenAPI spec files in various ways in order to reproduce it and couldn't either... 
It reminded me of something I encountered when developing this feature, so maybe it will reappear in the future. Wait and see. 
Thank you again for your help!

**Comment by volkerrichert** [comment]
THX for the best mock tool in universe!

**Comment by 255kb** [comment]
and beyond 🚀 
You're welcome😄

**Comment by 255kb** [comment]
and thank you for the donation @volkerrichert, it means a lot! 😄

**Comment by volkerrichert** [comment]
your welcome, too!
