### ISSUE TITLE
OSX: Cannot listen on ports < 1024

### ISSUE THREAD

**Issue by naegelin** [mockoon/mockoon#43]
Even when running the app in privileged mode , it will not allow you to specify ports less than 1024 as the listening port.  Being able to use 443 or 80 are pretty important for us as we can't always easily change our clients to test on different ports.

**Comment by 255kb** [comment]
I need to investigation how and if this can be fixed. Mockoon being an Electron app I can run Nodejs elevated sub processes but I am not sure how I can do that with npm libs (I use ExpressJS to create the server)

**Comment by naegelin** [comment]
Netcat I do not believe is native to OSX but you can use the built in 'pf' to redirect ports as followS:
From 443 to 4443
```
echo "
rdr pass inet proto tcp from any to any port 4443 -> 127.0.0.1 port 443
" | sudo pfctl -ef -
```

**Comment by 255kb** [comment]
@naegelin thank you. I think this would be a good compromise. Apparently running a Node sub process elevated is not a big deal, but not sure how I would do this with an npm package while maintaining the connection with the Electron app... (to update the UI). 
So it could be one option per environment saying something like "Forward from " with an input to speciy the port, then the command would be run elevated so the OS would prompt you. 
What do you think ?

**Comment by srmamidi** [comment]
I wanted to run the Environments in Mockoon GUI automatically upon startup in Windows 7 server.. is there a way for this?

**Comment by 255kb** [comment]
This won't be implemented for now. While it would be an interesting addition it didn't gather enough attention. Also, I don't want to mess up with users system files or configs. 
If this gather more attention in the future (through votes) I will reconsider.
