### ISSUE TITLE
Portable version Mockoon for Windows

### ISSUE THREAD

**Issue by jghaanstra** [mockoon/mockoon#430]
**Describe the solution you'd like**
A portable version of Mockoon that doesnt require an install and save any data within it's own folder.

**Comment by 255kb** [comment]
I guess we are talking Windows only here?

**Comment by 255kb** [comment]
Notes: 
- auto update should be disabled (new version link should open the browser)
- app data folder should be next to the executable (see https://www.electron.build/configuration/nsis#portable)
