### ISSUE TITLE
Add route folders

### ISSUE THREAD

**Issue by impe93** [mockoon/mockoon#431]
**Is your feature request related to a problem? Please describe.**
When I have hundreds of routes I would like to have the ability to organize them under folders to easily find what I need later.

**Describe the solution you'd like**
- The "+" button over the routes sidebar could open a contextual menu with choices: one to create a new route and a second one to create a folder
- Multi-select the routes to organize under a single folder, right-clicking on the selection will open a contextual menu and give the possibilities to delete selected routes or create a folder

**Additional context**
Postman is divided into collections and every collection can have a hierarchy of folders. A good starting point is having just one level of directories.

How postman handle this thing image example:

<img width="332" alt="Schermata 2021-03-08 alle 14 45 38" src="https://user-images.githubusercontent.com/25618834/110329806-601f4100-801d-11eb-9181-27deb8d15f1d.png">

**Comment by 255kb** [comment]
This should be covered by #97. I think the users' preference (according to the votes) would be for automatic grouping based on path sections rather than manual folder creation. 
That being said, it's not on the roadmap, yet.

**Comment by Ishwor-Shrestha** [comment]
What is the status for this request? Is this still being considered?
