### ISSUE TITLE
Option to manage max-http-header-size

### ISSUE THREAD

**Issue by pavelpipus** [mockoon/mockoon#442]
Some applications requires large cookies to be sent to server and mockoon has no options to change standard node
--max-http-header-size option. It should be useful to add this option for a server

Now in this case server responds with http error 431 Request Header Fields Too Large

**Comment by 255kb** [comment]
@pavelpipus Which size do you expect to pass in headers? Node.js lowered the max size from 80kb to 8kb in v10 I think.

**Comment by 255kb** [comment]
In fact, in current Mockoon version 1.12.0, it's limited to 8kb (Node.js v12). But in our next release due next week, it will uses Node.js v14 which increase the limit to 16kb. Let me know @pavelpipus if this would be enough so we can close this issue and wait for the release.

**Comment by pavelpipus** [comment]
@255kb thanks, 16kb should be enough

**Comment by 255kb** [comment]
@pavelpipus great, then it will be solved by next release, this week.
