### ISSUE TITLE
Sync environment across multiple devices

### ISSUE THREAD

**Issue by LeandroSQ** [mockoon/mockoon#457]
**Is your feature request related to a problem? Please describe.**
We use Mockoon on a lot of different projects with a lot of people,
But keeping the environments updated across everyone's computer is a hard task. Sometimes even requiring merging different json files.

**Describe the solution you'd like**
A way of sharing an environment to multiple people, therefore any changes would automatically broadcasted to everyone elses.

**Describe alternatives you've considered**
Problably using accounts 
Or even setting up a server to keep track of the changes and push tem to the clients

**Additional context**
None

**Comment by 255kb** [comment]
Hi @LeandroSQ thank you for opening this issue. This is a great idea that has been requested a lot of times. 
To be completely transparent, this is on the roadmap (just not public), but it will be a paid option part of a commercial offer around the open-source project. However, it's not planned before the end of the year or next year for multiple reasons:
- it's definitely not the highest priority right now. 
- it's a lot of work as many parts of the app are not ready for this. 
- it requires also a lot of additional coding for invoicing, account creation, etc. 
So this will eventually come but not quite yet 😃 
In the meantime, we are working on #16 and more generally on revamping the storage engine. This would allow users to open and store each environment independently anywhere on their computer. As a side effect it will be way easier to set up a git repository where the environment file is stored, and thus, share it with coworkers. 

I will be closing this as "won't fix", but it's not a definite "no", it's just temporary. Stay tuned!
