### ISSUE TITLE
Enable pinning of the collapsible environment sidebar

### ISSUE THREAD

**Issue by amilor** [mockoon/mockoon#465]
**Is your feature request related to a problem? Please describe.**
The collapsible environment sidebar is useless in its collapsed state showing only 2 letters from the environment name.

**Describe the solution you'd like**
Add ability to pin the sidebar in its expanded state.

**Describe alternatives you've considered**
Show more of the environment name in the collapsed state.

**Additional context**
None.

**Comment by 255kb** [comment]
Thanks @amilor for your change request. This is already cover by #386. Not sure how it will look but it will definitely change in a near future.

**Comment by amilor** [comment]
Thanks! Sorry I missed that one.

**Comment by 255kb** [comment]
No problem! It wasn't obvious 😃
