### ISSUE TITLE
[Enhancement] Remove trailing commas from JSON response

### ISSUE THREAD

**Issue by TillThomas** [mockoon/mockoon#470]
I'm working with angular 9 and I was stumped when my Observables did not emit the response of the API call to Mockoon.
I finally found a trailing comma in one of my nested JSON Objects.

Mockoon json/application-responses could remove dangling commas.

Any meaningful error message or basic JSON validation would also work.

Chrome allows trailing commas, but the angular http-client seems to silently error.

**Comment by 255kb** [comment]
I think fixing bad JSON should be the user's responsibility and I won't add this to the roadmap. I will reconsider if the issue gather more interest.
