### ISSUE TITLE
Add option to return a specific response on route response to use a specific response if file did not exist

### ISSUE THREAD

**Issue by louiealmeda** [mockoon/mockoon#473]
**Is your feature request related to a problem? Please describe.**
We have setup our mocks in our directories like this:

Users/
- GET.json
- POST.json
- Xq138f/
  - GET.JSON
- Pm5eR/
  - GET.JSON
  

And have a rule matcher set for that in mockoon
`GET: users/:userId`

File: `mocks/users/{{urlParam 'userId'}}/GET.json`

Now here's the issue:

`GET /users/Xq138f` -> returns 200 with the GET.JSON file as body (all good)
`GET /users/doesnotexist` -> returns 200 with Error while serving the file content: ENOENT: no such file or directory, open 'mocks/users/doesnotexist/GET.json' (could have been 404?)

**Describe the solution you'd like**
A checkbox under the `Settings` tab of the `route response` to use the response when the matcher got nothing
`GET /users/doesnotexist`. 

![image](https://user-images.githubusercontent.com/5992303/117453458-8eff5800-af77-11eb-8044-abbbd2a96bac.png)

WebApp options:

> **Fallback Response**
> Return a different response when there were no files matched the template

Response Model:  

```javascript
{
    "uuid": "",
    "body": "{\n  \"id\": 1,\n  \"firstname\": \"John\",\n  \"Lastname\": \"Snow\",\n  \"status\": \"Learning things\"\n}",
    "latency": 0,
    "statusCode": 200,
    "label": "Get userId 1",
    "headers": [
        //...
    ],
    "filePath": "mocks/users/{{urlParam 'userId'}}/GET.json`",
    "fallbackResponseUuid": "",                   // <------------ This one
    "sendFileAsBody": true,
    "rules": [
        //...
    ],
    "disableTemplating": false,
    "rulesOperator": "OR"
}
```

**Describe alternatives you've considered**
I've tried using the rules to handle 404s, but it's quite counter intuitive for that usecase as it becomes a whitelist. And the consumer now needs to be aware which requests patterns would respond a 404.

**Additional context**

**Comment by louiealmeda** [comment]
Hi @255kb, 

Are you good with the approach for the WebApp and the response model? I'm proposing to have a new property `fallbackResponseUuid` for that.

I notice though that there were no uuids being set for each response as of the moment.

Let me know what you think, thanks 🙂

**Comment by 255kb** [comment]
@louiealmeda uuids are set for route responses too. 
I understand the need, but I feel like this approach (having another place where you can setup the returned response) makes the UI a little more confuse. Knowing which response will be returned is already not easy. It depends on the responses order and the rules. 
Also, this behavior could already be achieved with rules, route params or templating. I know it's not the perfect solution, but for testing purposes one can "hardcode" some ids in the rules, using regexes, to serve either a 200 or a 404. 

One quicker and easier to implement solution could be a checkbox that overrides the selected status and send a 404 if the file was not found. The body wouldn't be customizable but I think it would be more in line with what has been done until now.

**Comment by louiealmeda** [comment]
> One quicker and easier to implement solution could be a checkbox that overrides the selected status and send a 404 if the file was not found. The body wouldn't be customizable but I think it would be more in line with what has been done until now.

Yeah I think this works. so the option could be:
> **Respond with 404 when the file path did not match to any files**

then in the Response model:
```
{
    ...
    "body": "{\n  \"id\": 1,\n  \"firstname\": \"John\",\n  \"Lastname\": \"Snow\",\n  \"status\": \"Learning things\"\n}",
    "statusCode": 200,
    "label": "Get userId 1",
    "filePath": "mocks/users/{{urlParam 'userId'}}/GET.json`",
    "fallbackTo404": true,
    ...
}
```

What do you think @255kb?

**Comment by 255kb** [comment]
@louiealmeda yes I think it should work like this. 
Do you want to work on this feature?

**Comment by louiealmeda** [comment]
Yes please @255kb, thank you for asking 🙂

**Comment by 255kb** [comment]
Let me know (here or on [Discord](https://discord.com/invite/JmTBk59MTb)) if you need any help!

**Comment by louiealmeda** [comment]
Hello @255kb, I think I'm almost done with it, I'm just testing. But I'm having issues with the nested npm link.
So i have changes to the following repos/packages:
* commons (RouteResponse Model)
* commons-server (deciding when to return 404)
* mockoon (UI, saving the value etc..)

I think my issue is specific to npm, I can't seem to `link` both `commons` and `commons-server` at the same time to `mockoon`. I think when I'm linking `mockoon` to `commons-server` it is not respecting `commons-server` link to `commons` and resolving dependencies directly from npm. Any tips for this kind of workflow? Thank you :)

**Comment by 255kb** [comment]
I never use `npm link` for the same reasons I think. What I usually do is the following (considering that `mockoon`, `commons` and `commons-server` are in folders side-by-side):
1. Commons lib: `npm run build`
2. Commons server lib: `npm i ../commons && npm run build` 
3. Mockoon app: `npm i ../commons && npm i ../commons-server`

You will get something like `"@mockoon/commons" : "file://../commons"` in your dependencies. And it should work most of the time. 

This will of course not work in the CI (there are currently no integration tests with the libs). What I usually do is to retest everything locally and then create releases for the libs first, then the main app (or CLI) CI will work.

**Comment by louiealmeda** [comment]
That worked quite nicely! Thank you @255kb

**Comment by louiealmeda** [comment]
Hello @255kb,

I can't seem to get the tests working for `mockoon`. I'm getting `"before all" hook for "Should wait for window to be ready"` errors. Can't seem to find the error through google or anywhere in the code. Any tips for this? Thanks.

**Comment by 255kb** [comment]
Hard to say, without seeing it. Those tests are a bit tricky. 😅
I suggest that you push everything, open the PRs for all projects and I will have a look and test on Monday.

**Comment by louiealmeda** [comment]
Hi @255kb, I've created PRs for each. Thanks for checking it out!

**Comment by barefootdeveloper** [comment]
> 
> 
> Hello @255kb,
> 
> I can't seem to get the tests working for `mockoon`. I'm getting `"before all" hook for "Should wait for window to be ready"` errors. Can't seem to find the error through google or anywhere in the code. Any tips for this? Thanks.

I know I'm a bit late to the party, but I got those errors whenever I didn't use build:CI:all prior to running the tests.

**Comment by 255kb** [comment]
Yeah sorry, I think I didn't warn you. As part of the recent webpack changes, I also modified how the tests are run. You now have to use build:ci:all before running the tests. It won't work with other NPM scripts.
