### ISSUE TITLE
Decode gzip/deflate automatically when mocking a proxied request

### ISSUE THREAD

**Issue by jschroeter** [mockoon/mockoon#479]
**Is your feature request related to a problem? Please describe.**
When the origin server that I'm proxying responses with gzip/deflate encoded body, mockoon just shows the raw content when mocking the request. This is annoying since it's impossible to quickly adjust the response in the mock. See https://github.com/mockoon/mockoon/discussions/453

**Describe the solution you'd like**

- mockoon should automatically decode these response bodies when creating a mock
- the returned mocked response should then be encoded again
- an icon could indicate that the original response was and and the mocked one will be gzipped
- optionally there could be a way of switching back to the raw content, but I personally don't have a use case for that

**Describe alternatives you've considered**

- there also could be a checkbox in the proxy settings to disable this feature, but I would prefer the icon/toggle described above

**Additional context**

![image](https://user-images.githubusercontent.com/487046/118486613-18eab600-b71a-11eb-8f60-01ffb9e119b8.png)

I worked around it by setting a proxy request header, but that's not very intuitiv:
![image](https://user-images.githubusercontent.com/487046/118486662-27d16880-b71a-11eb-8c85-843d6d57c029.png)

**Comment by 255kb** [comment]
My understanding is that the current way Mockoon proxies a response from a third party API is correct. It it transferred as-is, gzipped or not, depending on what the third party API responded. 
The only reason for this change is for convenience purpose, to actually be able to see what was answered in the recording/logs tab. 
Am I correct? 

Concerning the implementation, I would say it would be easy as the only place needing modification is the `CreateTransaction` function in [commons-server utils.ts](https://github.com/mockoon/commons-server/blob/main/src/libs/utils.ts#L74).
Concerning a specific icon, I would only add a mention that it was unzipped next to the response body to avoid cluttering the interface: 
![image](https://user-images.githubusercontent.com/7489814/118507223-53f6e480-b72e-11eb-890a-ccf5cd07c4f4.png)

**Comment by rubaiate** [comment]
**Implementation suggestions**
1. Decompress incoming message within proxy middleware based on the content-encoding, transfer-encoding. Message will be sent and recorded as plain message. Simple and already tested locally.
2. Proxy message as it is. But record the decompress message within mockoon. If coverted into mock message it should be compressed again acording to content-encoding

**Comment by rubaiate** [comment]
> My understanding is that the current way Mockoon proxies a response from a third party API is correct. It is transferred as-is, gzipped or not, depending on what the third party API responded.
> The only reason for this change is for convenience purpose, to actually be able to see what was answered in the recording/logs tab.
> Am I correct?
> 
> Concerning the implementation, I would say it would be easy as the only place needing modification is the `CreateTransaction` function in [commons-server utils.ts](https://github.com/mockoon/commons-server/blob/main/src/libs/utils.ts#L74).
> Concerning a specific icon, I would only add a mention that it was unzipped next to the response body to avoid cluttering the interface:
> ![image](https://user-images.githubusercontent.com/7489814/118507223-53f6e480-b72e-11eb-890a-ccf5cd07c4f4.png)

Seemed to be the better approach. If we convert this into mocked api, is it needed to compress again when replaying? Othrewis need to remove content-encoding, trnasfer-encoding headers.

**Comment by 255kb** [comment]
I didn't think about the "auto-mock" feature at all @rubaiate. 😅 
I would say, Mockoon's purpose is to be able to modify and customize mock responses, so I would create the mock's body in plain text. Then maybe we would need to remove the two headers automatically, otherwise it doesn't make sense.
Enabling gzip when sending responses should be a separated option at the environment or route level in my opinion. But this is for another time.

**Comment by rubaiate** [comment]
Actually this is how I work. Decode compressed body initially and record without headers. Then I can mock and change response as I need. 
I was thinking about @jschroeter requirement that's why asked about compressing again.

So can we only fix first requirement from @jschroeter request from this ticket.
Message replay always will not have any encoding as usual.

**Comment by rubaiate** [comment]
Actually this is my initial requirement. Decode compressed body initially and record without headers. Then I can mock and change response as I need. 
I was thinking about @jschroeter requirement that's why asked about compressing again.

So can we only fix first requirement from @jschroeter request from this ticket.
Message replay will not have any encoding as usual.

**Comment by jschroeter** [comment]
> Concerning a specific icon, I would only add a mention that it was unzipped next to the response body to avoid cluttering the interface

Good idea, I like that!

> Actually this is my initial requirement. Decode compressed body initially and record without headers. Then it is possible to mock and change response as needed.

Yes, absolutely fine with that! For me it's also not important that the replay will be encoded again. As you said, we just need to make sure to remove the headers in that case.

**Comment by 255kb** [comment]
great, so if I summarize: 
- decode the body if encoding is detected (through the headers), when creating a log entry (when [creating a `EnvironmentLog`](https://github.com/mockoon/commons-server/blob/main/src/libs/utils.ts#L74)) 
- add a mention "unzipped" (or something else) next to the logs response body when gzip header is detected 
- strip the compression headers when adding a route from the logs (in environment service `createRouteFromLog` method). Log body is already unzipped.

@rubaiate do you still want to work on this?

**Comment by rubaiate** [comment]
Sure. I am happy to go ahead.

**Comment by rubaiate** [comment]
Need advise. There is changes in common-server library for this ticket. Is it needed to create new ticket in  common-server repo related to this one?

**Comment by 255kb** [comment]
@rubaiate No it's ok, you can just refer to this issue in commons-server PR and also in the commit, something like "See mockoon/mockoon#479". Keep it simple 😄

**Comment by rubaiate** [comment]
@255kb The feature is implemented successfully. common-server test cases are fine. But no solid idea about implementing tests for mockoon.
Btw I don't have permission to push feature branches to repos.

**Comment by 255kb** [comment]
@rubaiate I can add the UI tests, ni problem. 
You won't have write access to the repos, you need to fork, branch and open PRs on both repositories where you made changes. I will then review through GitHub.
