### ISSUE TITLE
Environment headers being duplicated when using CORS

### ISSUE THREAD

**Issue by andreluizbellon** [mockoon/mockoon#480]
**Describe the bug**
Some CORS related headers are being duplicated when using CORS

**To Reproduce**
Enable CORS and click on "Add CORS headers to environment headers below" button

**Expected behavior**
The requests should have the headers properly added. Instead, many of them are being duplicated

**Screenshots**
![image](https://user-images.githubusercontent.com/7075343/118695711-de4d5000-b7e3-11eb-9655-13081c681879.png)
![image](https://user-images.githubusercontent.com/7075343/118695774-edcc9900-b7e3-11eb-9feb-bffbde67a4de.png)

**Mockoon version:**
1.14.0

**OS / OS version:**
Mac OS, Linux Ubuntu 18.xx

**Comment by arslivinski** [comment]
I'm having the same issue running on Ubuntu 18.04

**Comment by 255kb** [comment]
Strangely I cannot reproduce your issue, but by allowing non-standard duplicated headers in #318 it introduced some unwanted behavior that I didn't anticipated. I will publish a new version only supporting duplicated headers for `Set-Cookie`.

**Comment by andreluizbellon** [comment]
@255kb thank you! :)
