### ISSUE TITLE
Support Linux ARM

### ISSUE THREAD

**Issue by hmsjy2017** [mockoon/mockoon#507]
**Is your feature request related to a problem? Please describe.**
I want to run mockoon on my Raspberry Pi. However, there are no deb packages for ARM.

**Describe the solution you'd like**
Add support for Linux ARM (deb package is required).

Travis CI already supports building on the arm64 architecture. I think it might be a good choice to use Travis CI to compile software that supports ARM.
https://docs.travis-ci.com/user/multi-cpu-architectures/

**Describe alternatives you've considered**
No.

**Additional context**
There is no more to say.

**Comment by realtica** [comment]
Nobody answer this :(
I need the same for raspberry pi, AARCH64.

**Comment by akkie** [comment]
Would also be great to publish docker images for ARM. Currently only amd64 images are published. This would make it more easy to run the docker image on Apple Silicon machines.

**Comment by 255kb** [comment]
📦 Arm64 deb version in now available in [v6.2.0](https://mockoon.com/releases/6.2.0/).
