### ISSUE TITLE
Can't import OpenAPI files

### ISSUE THREAD

**Issue by joeshub** [mockoon/mockoon#525]
**Describe the bug**
Using the import/export > Import Swagger menu option to import either .yaml file or .json file fails. 
See screenshot below

**Screenshots**
<img width="284" alt="Screen Shot 2021-07-22 at 2 39 20 PM" src="https://user-images.githubusercontent.com/764006/126713294-475b0cc0-8361-47fb-b4ef-daaa6e84f9ea.png">

**Mockoon version:**
1.14.1

**OS / OS version:**
Mac OS 11.4

**Comment by 255kb** [comment]
Could you please share the OpenAPI file you are importing so I can try to reproduce the error? Thanks.

**Comment by 255kb** [comment]
@joeshub without data to reproduce it, we won't be able to investigate this issue. 
One thing though, I had the same error after trying to import an incomplete OpenAPI definition file. I copy pasted a very long definition in the browser and didn't realize it was truncated. You may want to check that your file is in good shape.
