### ISSUE TITLE
Ability to resolve template file path based on environment file

### ISSUE THREAD

**Issue by xutzin** [mockoon/mockoon#531]
**Is your feature request related to a problem? Please describe.**
I tried to save environment in git repo as a submodule and serve some of request body using template files.
However, it seems `filePath` stored by 'Browse files' is absolute `C:\\Users\\${user}\\Repository\\submodules\\mockoon\\...\\template.json`, and even if I changed the value of `filePath` to relative `./.../template.json`, the base URL of `filePath` is fixed to `C:\Users\${user}\AppData\Local\Programs\mockoon\` so it will be resolve to `C:\Users\${user}\AppData\Local\Programs\mockoon\...\template.json`.

**Describe the solution you'd like**
Read environment file as a workspace and resolve relative file path according to environment file path

- environment.json
  /* File path: /home/${user}/Repository/submodules/environment.json */
  ```
  "responses": [
        {
            ...
            "filePath": "./a/b/c/template.json",
            /* Resolve to: /home/${user}/Repository/submodules/a/b/c/template.json */
            ...
        }
    ],
  ```

**Describe alternatives you've considered**
A setting in UI & an option in CLI for specifying base path of relative file path

**Comment by 255kb** [comment]
This is actually already in progress but undocumented. 
I am currently working on a [new storage system](#16) where you can open env files from anywhere on you hard drive. They are not necessarily in the application/user data folder. 
Part of this (huge) refactoring include this change. File path will accept both absolute and relative paths, but the relative path will start from the loaded environment file. This will easier sharing among teams. 
No ETA yet but it should be available in a future release (september/october).

**Comment by xutzin** [comment]
Thanks for your quick reply and bringing the good news.
Looking forward to it :)

**Comment by 255kb** [comment]
> Thanks for your quick reply and bringing the good news.
> Looking forward to it :)

You're welcome, and thank you for your awesome donation! It means a lot 😃
