### ISSUE TITLE
Please add support for random route latency (from a given interval)

### ISSUE THREAD

**Issue by edstefan-ts** [mockoon/mockoon#568]
As of now we can define a latency value for a given route.
Is it possible to specify an interval from which a random value will be used as the latency?

**Comment by 255kb** [comment]
I think this is gathering a bit of interest. 

There are multiple ways of implementing this and I think the UI should be kept simple:

1. latency is **always** randomized between 0 and the value provided. I would be in favor of this, as it requires no UI changes. 

2. we add a new setting at the environment level, `randomizeLatency`, if true, all latencies (route responses and environment) will be automatically randomized from 0 to the value provided. 

3 we add a new field next to each latency to provide an interval. While this looks more in line with what was requested here, I am not sure it adds much value compared to a randomization from 0 (no. 2). Also, it will add a new input in two places which contributes to the cluttering of the UI. 

I vote for no. 2.

**Comment by edstefan-ts** [comment]
Having a bit of variation while preserving the slow/fast category of response times would be great for most scenarios, at least in my experience.
An alternative would be to use the env var from option 2 to indicate a percent (e.g. a latency of 2 seconds and a 10% in the env var would indicate a desired interval of 1.8 - 2.2 seconds)

**Comment by kierangirvan** [comment]
This would be super useful to have a randomised latency rather than fixed.

**Comment by impeas** [comment]
Hey @255kb, I tried to roll up a draft [PR](https://github.com/mockoon/mockoon/pull/1429) for this feature, any feedback is welcome (this is my first contribution attempt to open source, so forgive if I missed something). 

Assign issue to me if possible and I'll try to follow up with the suggestions and add tests perhaps.

I thought of something like this. What do you think?

![Alt](https://s7.ezgif.com/tmp/ezgif-7-fc602bfc99.gif)

**Comment by 255kb** [comment]
@impeas Thank you for opening a PR! 

Here are my thoughts on this feature in general: 

While I see the value in having a randomized latency, there are other considerations to take into account. 

1. The relatively low popularity of this issue (upvotes)
2. The extra UI required by providing a way to give an interval
3. The data model change requiring a major release. We try to slow down on majors, as migrations are most of the time painful for teams (not even talking about the fact we now have a [cloud](https://mockoon.com/pro/), with desktop apps where we don't force updates...).

Considering this parameters, I would prefer to go with the simplest implementation, which is randomizing from 0 to the value provided in the field. 
Also, one could argue that latency shouldn't be randomized all the time, and that this option shouldn't be shared across a team. For your information, when using the cloud, environment settings are immediately propagated. 
This setting could instead be at the application level (+ CLI flag and serverless option). Like this, no UI change is required, no major release either, and I think it's a good balance. 

What do you think?

**Comment by 255kb** [comment]
📦 This was released in [v8.4.0](https://mockoon.com/releases/8.4.0/)
