### ISSUE TITLE
Enhance rule engine to check all values of a property in an array

### ISSUE THREAD

**Issue by aevalo** [mockoon/mockoon#577]
**Is your feature request related to a problem? Please describe.**
I have an JSON structure in POST body, which contains an array of objects at certain key. Order of said objects might change due to development, and using fixed indexes causes problems when rules get out-of-date.

**Describe the solution you'd like**
For example, let's say my structure is like so:
```
{
  "attributes": [
    {"attributeName": "foo", "attributeValue": "42"}, 
    {"attributeName": "bar", "attributeValue": "69"}, 
    {"attributeName": "baz", "attributeValue": "0"}
  ]
}
```

Instead of having two rules "attributes.2.attributeName = baz" and "attributes.2.attributeValue = 0", I could simply have a single rule, which checks if array in given object path contains object, with given keys and values. For example:
attributes contains {"attributeName": "baz", "attributeValue": "0"}

**Describe alternatives you've considered**
I tried writing the value as {"attributeName": "baz", "attributeValue": "0"} and object path as path to the array, but this seems not to work

**Comment by acmh** [comment]
+1 to this feature

**Comment by ajatkj** [comment]
Recently merged PR [1131](https://github.com/mockoon/mockoon/pull/1131) adds support for jsonpath in all helpers in Mockoon - request, response, data buckets, rules and so on. 
You can use something like below in your rule to get the desired result. You still need 2 rules but it has no dependency on order and indexes of your desired object.

Rule 1:
body=`$.attributes[?(@.attributeName=="foo" && @.attributeValue=="42")].attributeName`
value=`foo`
Rule 2:
body=`$.attributes[?(@.attributeName=="foo" && @.attributeValue=="42")].attributeValue`
value=`42`

Look out for the latest release. I have tested it on this version and seems to be working without any problems.

**Comment by 255kb** [comment]
Indeed this will be possible in v5.0.0 that will be released soon.
