### ISSUE TITLE
Windows Security Trojan detection

### ISSUE THREAD

**Issue by samsonv** [mockoon/mockoon#578]
**Description**
Windows Defender thinks the mockoon.setup.1.16.0.exe is a threat, and puts the file in quarantine when downloaded

**To Reproduce**
* Open mockoon 1.15
* It seems to then automatically download the update

**Expected behavior**
It should update to last version

**Actual Behavior**
Windows defender pops up

**Screenshots**
![image](https://user-images.githubusercontent.com/239889/137450417-cad1c27f-fcd4-4f89-96a3-d77dea62d40d.png)

**Mockoon version:**
1.15.0

**OS / OS version:**
Windows 10 Pro
Version	10.0.19043 Build 19043

**Comment by 255kb** [comment]
Good news! I was crossing my fingers so hard 😄
