### ISSUE TITLE
Environment does not reflect JSON file's changes

### ISSUE THREAD

**Issue by nodehi** [mockoon/mockoon#580]
**Describe the bug**
With introduction of Mockoon v1.16.0, we updated our environments to stand alone JSON files, and we included them into our Git Repo, so all team members can update and share changes easily. 
However, when you pull latest changes from Git, even though you have updated JSON files in your local branch, the environments which are already open in Mockoon app, will not reflect those changes.
The work-around for now is to close the environments and reopen them, or restart the Mockoon App after each git pull that has changes to any of JSON files.

**To Reproduce**
Open an environment from a JSON  file.
Make some changes to the JSON file in another editor app.
The environment in Mockoon will stay unchanged.
Close and reopen the environment, you will see the changes. 

**Expected behavior**
Environment which are already open, should get dynamically updated as the JSON files changes.

**Mockoon version:**
1.16.0

**OS / OS version:**
Mac OS

**Comment by 255kb** [comment]
I will work on this soon, but I am not sure about the implementation. 
Seeing the issues and talking with some users, I see two possibilities: 
1. It could be automatic and transparent for the user. The environment could be updated in the UI immediately after a file change without prompting. I don't see any issue choosing this implementation and not prompting the user. 
2. Another solution would be to prompt the user in the UI to "Reload from disk", like VSCode or other editors do. But this raises more questions like: if someone has multiple opened environments updated by a single `git pull`, should we prompt once for all environments or for each of them? (Each of them could be really annoying)
I vote for 1. 😀

**Comment by roybarber** [comment]
@255kb I think both options are viable, I agree with the annoyance of option 2. 

Is there a way to have two buttons, Where a user accepts the current notification, or accepts all?

But for a quicker fix i think option 1 is best, it also avoids some users not updating and presenting back with api data issues which could have been avoided.

**Comment by 255kb** [comment]
@roybarber True. But Mockoon autosave happens around 1 or 2 seconds after the last modification. So, it means that if you go to your favorite git tool and pull, you will have to commit your local changes anyway and merge, and then you shouldn't lose anything.
Automatically reloading after the commit+merge should work then. 
Or am I missing something?

**Comment by roybarber** [comment]
Yes good point the file will be marked as changed anyway. 

Solution 1 vote from me.

**Comment by nodehi** [comment]
@255kb , I vote for Option 1,
For a team that their main focus is not API development (e.g.we are team of iOS developers) , we all run Mockoon, and rarely go to check on it.
If one member update some mock and commit it,, it is easier for the rest of team that Mockoon automatically return updated response after we pull the new changes from Git Repo.

**Comment by victorzw895** [comment]
Hi guys, has this been fixed on mockoon v4.1? I am still getting the exact same issue right now. Whenever I pull changes from main or switch branches, instead of updating my mockoon environment. It updates my json file with Mockoon's app current environment.
This makes it really easy to accidentally make mistakes and remove changes

**Comment by 255kb** [comment]
@victorzw895 This was [released in 1.18.0](https://mockoon.com/blog/file-monitoring-mock-api-samples/#file-monitoring). It's not enabled by default though and you need to go in the settings.

**Comment by mahdiraad** [comment]
Dear @255kb
Is there any option for this watcher in mockoon-cli?

**Comment by 255kb** [comment]
@mahdiraad not yet, but there is an [opened issue](https://github.com/mockoon/mockoon/issues/665).
