### ISSUE TITLE
Templating body

### ISSUE THREAD

**Issue by hargut** [mockoon/mockoon#59]
**Describe the bug**
Setting up a template as described on the Wiki Page:
https://github.com/255kb/mockoon/wiki/%7B-%7D-JSON-templating

Sending the described `GET` request without JSON body returns an empty body with the selected Status code 200.

**Expected behavior**
Return body with selected status code and 'default' body template value.

I'm not really sure if this is a bug. Eventually there are good reasons why the above described behavior would be desired. Still I do think that the 'default' value should be returned with a full body containing the template.

Just started with mockoon, and I really like the concept of the software. It is very easy to use and straight forward, with a lot of options! Keep on the good work & many thanks for your efforts creating this great mock-server.

**Comment by 255kb** [comment]
True, apparently there is a bug with the `body` template helper. I will investigate.
Thank you.

**Comment by hargut** [comment]
Many thanks for your fast response.

Just tried a little more, and it seems as soon as one sends `{}` in the body, the `default` works as expected.

**Comment by 255kb** [comment]
Yes I just saw this, it's not very tolerant :)

**Comment by hargut** [comment]
Perfect. Thank you very much for your fast help. :+1:

**Comment by 255kb** [comment]
No problem :) 
But don't expect a release very soon, it may take some weeks as I have limited time to work on Mockoon
