### ISSUE TITLE
Apple Silicon builds

### ISSUE THREAD

**Issue by sezabass** [mockoon/mockoon#591]
### Discussed in https://github.com/mockoon/mockoon/discussions/590

<div type='discussions-op-text'>

<sup>Originally posted by **sezabass** November 16, 2021</sup>
It would be lovely to see a Mockoon release that is compatible with M1 chips.</div>

Electron supports this [since v11](https://www.electronjs.org/pt/blog/electron-11-0).

**Comment by seravifer** [comment]
If you need it, I can test this version on my MacBook Air M1. Or even work in PR if @sezabass can't.

**Comment by 255kb** [comment]
https://github.com/electron-userland/electron-builder/issues/5689

**Comment by 255kb** [comment]
I just built v1.17.0 for mac in 3 versions: 
- universal (contains both x64 and arm64 binaries): https://github.com/mockoon/mockoon/releases/download/v1.17.0/mockoon.setup.1.17.0.universal.dmg
- x64: https://github.com/mockoon/mockoon/releases/download/v1.17.0/mockoon.setup.1.17.0.x64.dmg
- arm64: https://github.com/mockoon/mockoon/releases/download/v1.17.0/mockoon.setup.1.17.0.arm64.dmg

I would be glad if you could test the arm64 versions @seravifer @sezabass 
Thank you!

**Comment by seravifer** [comment]
![Captura de pantalla 2021-12-01 a las 11 20 14](https://user-images.githubusercontent.com/5394989/144216793-6e0d4e35-e211-4da6-90f5-b0e4c9961cc7.png)
It works!

**Comment by 255kb** [comment]
Marvellous!

**Comment by 255kb** [comment]
@seravifer Any issue with the icon in the dock?

**Comment by seravifer** [comment]
No, it looks perfect.

**Comment by 255kb** [comment]
Thanks!

**Comment by sezabass** [comment]
Sorry for the delay, I've been really really busy lately.
I've tested the arm64 version, everything's fine here as well 👍 
![image](https://user-images.githubusercontent.com/782204/144274041-10a1b090-3f29-4b49-926a-aadfaced7475.png)

**Comment by 255kb** [comment]
Great! Thank you @sezabass
