### ISSUE TITLE
Don't support dollar char in path

### ISSUE THREAD

**Issue by heavenwing** [mockoon/mockoon#606]
**Describe the bug**
I want to mock Microsoft Graph api, it contain dollar char ($) in path, like below:
https://docs.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-beta&tabs=http

```http
POST https://graph.microsoft.com/beta/groups/{group-id}/members/$ref
Content-type: application/json

{
  "@odata.id": "https://graph.microsoft.com/beta/directoryObjects/{id}"
}
```

but Mockoon always return 404 not found response

**To Reproduce**
Add a new route with path "/beta/groups/{group-id}/members/$ref"
send http request from any client (ex: PostMan)

**Expected behavior**
Mockoon can caught this request, match it into my route

**Screenshots**

**Mockoon version:**
1.15

**OS / OS version:**
Windows 10 19044.1348

**Comment by 255kb** [comment]
This is a "feature" of Expressjs that Mockoon is using. Express is treating the `$` like its regex counterpart: https://expressjs.com/en/guide/routing.html#route-paths
You must escape the `$` when declaring your route. 
Anything like this should work: 
```
/route/\$ref
/route/[\$]ref
/route/([\$])ref
```
