### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by bevinhex** [mockoon/mockoon#615]
only few json api and few test file server is created, already used up 5.8GB memory, nothing else is running after fresh restart, not much autostart applications except essentials

**Expected behavior**
For a single program to mockup , it is not exceptable to use up that much memory, should be under 100mb, our whole distributed cross platform sdk uses up 1mb ram, yet mockup crashes when sdk tries to fetch multiple files in parallel, suspect it is out of memory problem

**Screenshots**
![image](https://user-images.githubusercontent.com/9736688/145805444-0db0e5c8-392b-4fda-8da0-22b499c79df4.png)
![image](https://user-images.githubusercontent.com/9736688/145805535-eb7f26a2-24f3-424e-8687-d82060a4a77a.png)

**Mockoon version:**
1.17

**OS / OS version:**
ubuntu 20.04

**Comment by 255kb** [comment]
Could you please share more details about your routes, and the content you are trying to send through Mockoon? Seeing the screenshot I suspect that you are serving big file (1Gb). Mockoon wasn't optimized for such use case (yet). 
Depending on your answer, it may be related to #605 and both problems could be solved at once.
