### ISSUE TITLE
Multiple Users using checked in environment.json

### ISSUE THREAD

**Issue by roybarber** [mockoon/mockoon#621]
**Describe the bug**
When we have multiple developers working on a project, all with mockoon (app) open and reading from an environment json file thats stored in version control, If we pull down a branch, mockoon doesnt apply the changes to the environment from the new json file, instead it immediately creates a changed version ready to commit. To avoid this happening you have to close mockoon before pulling from git.

**Expected behavior**
Mockoon app updates to reflect the changes coming in from source

**Mockoon version:**
1.17.0

**OS / OS version:**
Windows 10, Mac OS - Not tested on others

**Comment by 255kb** [comment]
@roybarber Indeed, it's a bit annoying right now. This is already planned in #580
