### ISSUE TITLE
Run in background

### ISSUE THREAD

**Issue by mallowigi** [mockoon/mockoon#624]
**Is your feature request related to a problem? Please describe.**
Hi, I'd like to have mockoon run in the background, .e.g in the TaskBar/MenuBar/etc. Currently the application runs in a separate window and by the time this window is closed the application exits and the servers are disconnected. 

**Describe the solution you'd like**
It would be great if Mockoon can be included in the Taskbar (Windows) or MenuBar (Mac/Ubuntu) and runs in the background, rather than having to quit once clicking the X button.

**Comment by LucaSorvillo** [comment]
Has this functionality been implemented? Because it would be convenient if it were provided, I don't see it in the settings..
