### ISSUE TITLE
Route specific latency not working properly

### ISSUE THREAD

**Issue by Bruno13** [mockoon/mockoon#638]
**Describe the bug**
The Route specific latency set for the first response it's being set for all others. Seems like all the responses added uses the latency route definition from the default response.

**To Reproduce**
1. Add New Environment
2. Add route
3. Add response
4. Set Route specific latency 1000ms in the first response
5. Set Route specific latency 0ms in the second response
6. Enable Sequential Response

Now make a request to the route added and you will observe that first response is with 1000ms of latency. Make a request again and you'll observe that second response is also with 1000ms of latency even then the latency is setted with 0ms for the second response. 

**Expected behavior**
The route specific latency should be set by each response.

**Mockoon version:**
v1.17.0

**OS / OS version:**
Windows 10 Pro x64

**Comment by 255kb** [comment]
@Bruno13 I just tested and experienced no issue. I tested by reordering the responses, using sequential or randomized responses and result was consistent. 
Could you please share you environment JSON data (right-click on the environment in the list, then --> "Copy to clipboard (JSON)", so I can try to reproduce the issue?
