### ISSUE TITLE
Mockoon fails to import a mockoon exported json file on other OS

### ISSUE THREAD

**Issue by alpap** [mockoon/mockoon#647]
**Describe the bug**
When you are using the mockoon in windows and export a project to a mockoon json file, you cannnot open it in linux or mac

**To Reproduce**
- Open Mockoon on Windows
- Create a project 
- Export to mockoon format json 
- Import the mockoon project json in mac or linux

**Expected behavior**
Mockoon should load the json file

**Screenshots**
![image](https://user-images.githubusercontent.com/7300731/156536571-42dc7cd4-93ca-4851-a8fd-97c56b02805b.png)

**Mockoon version:**
v1.17.0

**OS / OS version:**
Windows 10, Mac OS latest, Linux Ubuntu 21.04

**Comment by 255kb** [comment]
The export in Mockoon's format feature [has been removed](https://github.com/mockoon/mockoon/issues/626) in latest version v1.18.0. It won't be supported anymore as you can share environments files "as-is".
Could you please check that sharing between the two systems works with environments files directly? ([Find your environment files](https://mockoon.com/docs/latest/mockoon-data-files/data-storage-location/#locating-the-files)
Thanks.

**Comment by alpap** [comment]
yep it seem to work :)

**Comment by OluAgunloye** [comment]
Hello, 

This issue isn't quite solved actually. On Windows this issue persists, any now deprecated format imported seems to import correctly, but when you want to export to the "new" format, the export "loses" data. That is not expected, as what Mockoon imports it should surely be able to export correctly.
