### ISSUE TITLE
Automatic env reload reloads forever and shuffles the sidebar

### ISSUE THREAD

**Issue by manofthepeace** [mockoon/mockoon#649]
First off thank you for this great tool.

**Describe the bug**
After loading Mockoon 1.18 when I launch Mockoon, I see the notification on the side about the env changed externally, and it reloads the files, but it reloads endlessly so mockoon is unusable for me I had to go back to 1.17. For some reason something seems to modify the file, and then mockoon reloads it.  Even worse I have about 10 mocks on the side bar, and while the each reload forever, like every second they shuffle on the side bar so I lose my order of things it becomes totally random which is quite annoying. At some point the tool even deletes all my env, then reloads them all in random order.

Is there a way to disable that feature?

**To Reproduce**
Steps to reproduce the behavior.
Just start mockoon with existing env

Behaviour is always different when I start the tool, sometimes it works, sometimes all env reloads every second, sometime just 1 env get stuck..

**Expected behavior**
I am not really fond myself of that feature in the first place, the fact it changes the order in the side bar is a no go for me. I'd like to disable it at least if it cannot be fixed or cause cannot be determined.

**Screenshots**
I cannot share those env /screenshot unfortunately, I can try making the mock more generic so I can share

**Mockoon version:**
mockoon 1.18

**OS / OS version:**
Mac os 11.6.4

**Comment by 255kb** [comment]
I am sorry to read that. This feature was thoroughly tested on multiple platforms, so I am not sure what is the cause. 
Could you please verify that you don't have any software that is modifying the environment files? 
Also, the order of the environments should be maintained, but if they are all reloading randomly everything is broken, of course. 

There is currently no option to disable this option. As you may not be alone, and consequences are quite annoying, I will think about what to do in the coming days and maybe publish a new version where the app prompts the user, and this feature can be disabled.

**Comment by manofthepeace** [comment]
Thanks for your prompt response. I can try giving a bit more context, minimal but better than nothing. Good to know the env are not supposed to lose ordering; I kind of expected that was a side effect of the initial problem.

So I have 2 sets of files for 2 projects, one is from a really old mockoon installation and I never bother moving them
`~/Library/Application Support/mockoon`
the other are in a git repo where we update the env as our project goes. All files are at migration 19

I did run mockoon as the only program on my laptop so I do not see at first glance anything that could modify the files.

What is really odd is that I really get inconsistent behavior each time I start mockoon 1.18

Sometimes;
1. it just works, I start mockoon, no notification on file update and it just work (what I expect).
2. it's a party on the screen! all files seems to get updated every second and things are getting shuffled, and when they get reloaded, I kind of suspect the uuid to update and then it causes the loop
3. I start the app, all file seems to update a couple time then it settles, but one single env keeps reloading every seconds, forever.

If you need anything please let me know I'll do my best to support that investigation. I can surely try to anonymize the envs names / endpoints, but at the same time I am not doing anything fancy or out of the ordinary.

**Comment by 255kb** [comment]
Thank you for the details. I suspect that Mockoon is detecting its own change event after it saved a file, which should definitely not happen.
Could you please give me the approx. size of your environment files?

**Comment by manofthepeace** [comment]
I have 9 env files: ranging from about 6KB to about 17KB

**Comment by 255kb** [comment]
Thank you. 
I will investigate and probably revert to a prompt system that can be disabled.

**Comment by 255kb** [comment]
I just released a v1.18.1 where the file monitoring is disabled until I investigate the issue and come up with a better implementation. Sorry for the mess 🙇

**Comment by manofthepeace** [comment]
Oh don't be sorry! Bug happens. Thanks a lot for the quick turnaround. Please let me know if you need anything from me.

**Comment by 255kb** [comment]
@manofthepeace Would you help me test the new version? If yes, could you please join the [Discord server](https://discord.com/invite/JmTBk59MTb)?
Thanks 😀
