### ISSUE TITLE
Configurable SSL on start. 

### ISSUE THREAD

**Issue by mynameisandreas** [mockoon/mockoon#668]
Wanted to ask if it's possible to have an override ssl flag of some sort when starting with mockoon-cli start. 
Why I would like to have this is becuase my hosting provider allowes me to deploy an docker image withouth SSL and they will 
handle the SSL. 
But running locally, I have to switch off SSL and then put it on when pushing it to my hosting partner. 

Would it be possible to add an option flag that can override the json config?

**Comment by 255kb** [comment]
📦 This was added in [v8.1.0](https://mockoon.com/releases/8.1.0/)
