### ISSUE TITLE
Cli Parameter to Set Faker.JS Locale

### ISSUE THREAD

**Issue by melkyfb** [mockoon/mockoon#669]
I'm working for a german company and I'd like to create the mockoon api using the German Locale in Faker.js.
The options is available in the GUI.
![image](https://user-images.githubusercontent.com/44884373/145837876-5f06e784-d3cd-4f91-81f8-062827b21375.png)

The simple solution would be a way to launch the cli with some parameter like `mockoon --data=file.js --locale=de`

**Comment by jamsch0** [comment]
It would be great if this could be passed as an option to the serverless package too.

**Comment by 255kb** [comment]
📦 This is now released in [v6.1.0](https://mockoon.com/releases/6.1.0/).
