### ISSUE TITLE
Support localhost subdomains through automatic /etc/hosts file modification

### ISSUE THREAD

**Issue by enozero** [mockoon/mockoon#67]
I have some projects that access specific subdomains, but the routes may be the same. It would be great to allow subdomains.

Ideally, there would be a textbox to the left of "localhost:" to setup a subdomain for the environment.

**Comment by 255kb** [comment]
I don't think you can setup a subdomain for localhost. So there is no way I could create a server through Mockoon that lives on `subdomain.localhost:3000`.

But you could add something to your /etc/hosts so `sub.localhost` would be the same as `localhost`:
`127.0.0.1 sub.localhost`

**Comment by enozero** [comment]
There could still be a way. Mockoon could put the entry in the `hosts` file, and then the server could parse out the domain information. If it sees a subdomain, it would do a lookup to see if any environment is specifically listening for that subdomain.

I'm imagining something in the `ServerService` that would add another `use` and filter out requests that don't match the subdomain. If the environment doesn't have a subdomain present, then it would be a wildcard and allow all requests through.

**Comment by 255kb** [comment]
Make sense. But before implementing something that messes up with the hosts file I would be sure that it make sense for other people too. 
I will reopen this issue and change the title to something more explicit and see if it gets interest.

**Comment by 255kb** [comment]
Considering the lack of interest for this request, and also the fact that we want to keep Mockoon simple, and not mess with system files, this won't be implemented.
