### ISSUE TITLE
Add include helper

### ISSUE THREAD

**Issue by paour** [mockoon/mockoon#672]
**Is your feature request related to a problem? Please describe.**
In order to reuse data between routes, I would like to be able to include files in my mock responses. 

**Describe the solution you'd like**
For example if my API serves info about states, I could create one file per state. Then I could have a route like `random5`, which returns a JSON array generated by something like

```
[{{join (include (someOf (array './states/AL.json' './states/AK.json' './states/AZ.json' …) 5 5)) ',')}}
```

It would be very nice if this could be recursive (with a safety to avoid infinite loops).

**Describe alternatives you've considered**
I could use scripts to generate variants outside Mockoon, then add generated variants as route responses. That would make it harder to update the sample data.

**Additional context**

**Comment by 255kb** [comment]
I think this should be covered by the [data bucket](https://mockoon.com/docs/latest/data-buckets/overview/) feature. I'm closing this for now.
