### ISSUE TITLE
Ability to export to OpenApi V3 Using the CLI

### ISSUE THREAD

**Issue by roybarber** [mockoon/mockoon#678]
**Is your feature request related to a problem? Please describe.**
I cant export my environment to OpenApi V3 (Json) using the CLI

**Describe the solution you'd like**
When using the CLI, i'd like the ability to export my environment to OpenApi v3 (JSON), like i can do using the Mockoon UI

**Describe alternatives you've considered**
Only option currently is using the Mockoon UI (App)

**Comment by Mavbraz** [comment]
Hey, @255kb.

I have a few thoughts to say about what could generate more outcome for users:
- It makes more sense to export to OpenApi v3 (JSON) just passing a data file and output a json than to export an environment that is running
- As it's being developed to export to OpenApi v3 (JSON), the import function can also be implemented for Swagger v2/OpenApi v3 (JSON or YALM)

I'd like to contribute by developing this task. Could I be assigned to this one?

**Comment by 255kb** [comment]
@Mavbraz Sure, I assigned the task to you. Let's discuss the details on Discord!

**Comment by 255kb** [comment]
📦 This is now released in [v6.0.0](https://mockoon.com/releases/6.0.0/).

**Comment by roybarber** [comment]
Amazing @255kb Absolute legend!

**Comment by 255kb** [comment]
@roybarber  You must thank @Mavbraz 😊
