### ISSUE TITLE
Logs' delete button is not well positioned

### ISSUE THREAD

**Issue by kajweb** [mockoon/mockoon#686]
![image](https://user-images.githubusercontent.com/2993320/163120984-5b2255c3-c8e8-4c8d-946c-28d67d6810be.png)

When I first used it, I thought this would just delete one of my records. In fact, he will delete all logs

v1.18.1

**Comment by deosrc** [comment]
Ran into this earlier for a different reason. I was wanting to clear all logs but the button wasn't there. Realised you have to open one of the entries for the button to appear.
