### ISSUE TITLE
Partial mocking proxy mode based on routes and rules

### ISSUE THREAD

**Issue by martin-bucinskas** [mockoon/mockoon#687]
**Is your feature request related to a problem? Please describe.**

I find that mockoon partial mocking using the proxy mode is not very useful as it is at the moment, since it only
forwards the requests that do not match a declared route to the URL of our choice.

**Describe the solution you'd like**

Mockoon should be able to partially mock APIs using proxy mode where the proxy pass-through is defined as a route or a template rule.

This would provide a more powerful implementation and use case for mockoon, where we can selectively proxy based on different rules or routes, rather than when facing a failure case of route not being defined.

**Describe alternatives you've considered**

N/A

**Additional context**

Rule example:
> I have a template with a query parameter `id`.
> I want to be able to respond with mocked template for all `id`s unless the `id` matches `ABC-123`.
> If the `id` matches the value `ABC-123`, the request should be proxied to a service to handle this accordingly.

Route example:
> I have the following routes:
> `POST /pets`
> `PUT /pets`
> `GET /pets`
> `POST /store/order`
> `GET /store/order/{orderId}`
> 
> I mark `POST /pets` and `PUT /pets` routes with a flag to proxy only these requests across to another service.
> All other routes should respond with the mockoon templates.
> This ensures that in any error case, the service that is being proxied to is only reachable with a known configuration of routes.

**Comment by 255kb** [comment]
Thanks for opening this issue. 
It is already covered by #363 where we will track this feature.
