### ISSUE TITLE
CLI flag `--log-transaction` should have an option to hide credentials

### ISSUE THREAD

**Issue by martin-bucinskas** [mockoon/mockoon#688]
**Is your feature request related to a problem? Please describe.**
Running mockoon cli in a containerised environment, I'd like to log each transaction in verbose mode to have the ability to be able to debug or have an insight on the requests coming in and their responses.

When the `--log-transaction` flag is enabled, the current behaviour is to log the entire content of the transaction including any credentials passed along.

This would result in leaking credentials to anyone who has the ability to view the logs.

**Describe the solution you'd like**
An optional parameter could be passed to mask any specified header in the log to prevent leaking of credentials to stdout.
This would allow verbose logging without leaking credentials.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by 255kb** [comment]
📦 This is now available with [release v4.0.0](https://mockoon.com/releases/4.0.0).
