### ISSUE TITLE
Using variable nested in helper

### ISSUE THREAD

**Issue by iFederx** [mockoon/mockoon#699]
**Bug description**

I'm not sure if this is a bug, maybe it's my fault.
I'm trying to create a mock for an API that returns a list of transactions.
Within each transaction I get the fields authorized amount and captured amount. The captured amount must be a causal number, but must not exceed the authorized amount.

**To Reproduce**

To achieve this, I've written the template below (`application/json`):
```
{
    "list": [
      {{# repeat (queryParam 'limit' '10') }}
          {{setVar 'amount' (faker 'datatype.number' min=100000 max=9999999999)}}
          {
              "amount": {
                "authorizedAmount": {{@amount}},
                "capturedAmount": {{int 100000 @amount}},
                "fee": 0,
                "currency": "EUR"
              },
              [...]
          }
      {{/ repeat }}

    ]
  }
}
```
but it seems that the higher limit `@amount` isn't considered.

How can I achieve the desired result?

**Mockoon version:**

1.18.1

**OS / OS version:**

Windows 10

**Comment by 255kb** [comment]
I just investigated and it's indeed a bug. 
Our `faker` helper is at fault here as it always returns a string. 

I will fix this for the next release.

**Comment by iFederx** [comment]
Thank you very much, Guillaume.
Okay, I'll wait for the next release.

Btw, Mockoon is a wonderful tool! ;)

**Comment by 255kb** [comment]
Thank you! Glad you like it 😄
