### ISSUE TITLE
Pretty print body responses in storage file

### ISSUE THREAD

**Issue by Otiel** [mockoon/mockoon#726]
When "Pretty print JSON storage files" is checked, would it be possible to also pretty print the content of the responses body (be it JSON, XML, others formats?)?

I have responses that contains dozens / hundreds of (pretty) lines, and it is currently impossible to read the changes using git when those lines are written on only one line in the environment file.

**Comment by 255kb** [comment]
I would say no. One reason would be that if you add line returns to the JSON stored in a string, it would create a invalid JSON.
Something like:
```json
{
  "body": "{
  <-- multi line string is not valid
  }"
}
```

The workaround would be to use external files.
![image](https://user-images.githubusercontent.com/7489814/171701971-58c5b118-7b8b-4a13-b246-fe46e6b2740e.png)
They also support templating helpers.

**Comment by Otiel** [comment]
That makes sense. Thanks for the workaround, I'll move my responses to external files.

**Comment by Otiel** [comment]
Do you think it would be a good idea to display and be able to edit an external file content directly from Mockoon? In place of the body control for instance.

**Comment by 255kb** [comment]
Why not, but I think it would be a lot of changes UI wise. 
I'm guessing that at one point response bodies will be stored in separated files but it's not planned yet.
