### ISSUE TITLE
Will `cli` support `toggle` feature of desktop

### ISSUE THREAD

**Issue by hbrls** [mockoon/mockoon#735]
I can temp disable a `route` with right click the `route` and select `toggle`.
The exported json does not support the `disabled state` of a route.

The senario: I have a local version and a server version of the mock. If the local mock is diabled, it will proxy to the server mock. So I can flexibly use a mixed mock of local and server.

Will `cli` support the feature?

**Comment by hbrls** [comment]
After some investigation, I think the `export environment json` support this by default. The problem is `OpenAPI Spec` does not support it. And it's not related to `cli`.

**Comment by 255kb** [comment]
Definitely, the export to OpenAPI has no equivalent for all of Mockoon's features. So, it's **not** a way to share your mocks or run them with the CLI. 
More infos [here](https://mockoon.com/docs/latest/openapi/openapi-specification-compatibility/).

The CLI indeed supports OpenAPI but only as a quick way to run a mock from a spec. If you want to use Mockoon's specific features (rules, etc.) you have to [run your Mockoon's files with the CLI](https://github.com/mockoon/mockoon/tree/main/packages/cli#run-a-mock-api-with-the-cli).
