### ISSUE TITLE
Add Mockoon to Winget

### ISSUE THREAD

**Issue by seanmudbath** [mockoon/mockoon#747]
Can you please add Mockoon to Winget packages? This way we can install mockoon from winget cli as well as choco:
https://docs.microsoft.com/en-us/windows/package-manager/package/repository

**Comment by 255kb** [comment]
I just checked this and apparently as Mockoon is already in the MS Store it's automatically on WinGet. 
I just tried `winget search mockoon` and `winget install mockoon` and it worked perfectly on Windows 11. 
![image](https://user-images.githubusercontent.com/7489814/181518934-e070b599-0069-42d2-8599-d00c526a9c7c.png)

I will close this but let me know if there is an issue. 
I will also update the website.

**Comment by seanmudbath** [comment]
Great thanks for checking it out!

**Comment by 255kb** [comment]
Not for later, winget does not report the current version of the package as it is coming from MS Store. Also, it's automated so we don't provide a manifest directly on the winget repo. 
Apparently, they are aware of the lack of version report and are working on it: 
https://github.com/microsoft/winget-cli/issues/2374#issuecomment-1195628362
