### ISSUE TITLE
Multiple responses per route

### ISSUE THREAD

**Issue by KevinRizzoTO** [mockoon/mockoon#75]
**Is your feature request related to a problem? Please describe.**
Often times when mocking I want to have a variety of responses come back from a request. For instance, when testing a UI I want to test both successful and failed responses. Right now I need to rewrite my response in mockoon to achieve this.

**Describe the solution you'd like**
It would be great to have an "Active Response" selector and a list of possible responses that I can edit. That way I could easily change between responses without having to alter a response. I'm not sure how the UI would look for this on mockoon. Perhaps nested tabs within the `Response & Body` screen? Whichever tab you have selected could be the "Active Response"

**Describe alternatives you've considered**
I've considered writing different responses as files and then switching between them as I need to. However, I still need to update the status code manually which isn't ideal.

If you need help with this I would be willing to contribute 😄

**Comment by 255kb** [comment]
Nice idea, and it has been asked in #63 too. 
For me there are two possible implementations: 
- declare multiple responses (code, body, headers) and declare an active one like you suggested
- declare multiple responses (code, body, headers) used depending on defined rules: route param contains x or y, header contains z, query param contains a or b, etc 

First one is easier, but I would definitely prefer the second version. What do you think? It's more work but it would also be possible to keep conditions simple. For example one input with a predefined syntax similar to body templating like `routeParam.userId === '1234'` .

**Comment by KevinRLeC** [comment]
Sorry for the late response to this @255kb .  I have used the second approach before for some projects! Some mock servers do this currently, like [mockyeah](https://www.npmjs.com/package/mock-yeah). I've found that it becomes difficult to remember what the "magic values" are that will trigger a certain response. Personally, I think the first option as a start would be great 😄 And then maybe we can reassess if people are interested in the second way?

**Comment by mixels** [comment]
@255kb The route params idea sounds very useful. Currently you can achieve that with body templating but it makes the response body in the editor pretty ugly if you're covering several different possible response codes (which could have significantly different response bodies). Consider 200 OK, 403 Forbidden, 409 Conflict, 415 Unsupported Media Type... The list of possible status codes that can result from any particular call to a real API is pretty long.

Route params with a multiple responses feature would greatly simplify what is probably one of the main use cases for body templating today. Would love to see it in Mockoon.

**Comment by 255kb** [comment]
@mixels I am more and more thinking that this would be very useful. Also I am currently working on OpenAPI/swagger format import, in which you can specify multiple responses (200, 403, etc). For now I will only import the first one but I can immediately see the benefit of being able to provide multiple responses. So this feature will be on the roadmap for sure. I just don't know when yet!
