### ISSUE TITLE
Environment json files removed after update

### ISSUE THREAD

**Issue by jimschmit** [mockoon/mockoon#755]
**Describe the bug**
When updating the application, I lose all my environment files that I created in the default folder (C:\Users\XXXX\AppData\Local\Programs\mockoon) so I have to recreate everything from scratch...

**To Reproduce**

1. Install earlier version
2. Create environment file in default location
3. Make the update
4. Environment file created before is no longer present in the default location

**Mockoon version:**

Not sure anymore from which version I updated, updated to latest, 1.19.0.
Tested from 1.17.0 to 1.19.0

**OS / OS version:**

Windows 10

**Comment by 255kb** [comment]
I'm sorry this happened to you, but you shouldn't use the `~/AppData/Local/Programs/mockoon` folder to store your mocks. 
This folder will get wiped and recreated every time there is a new install/update (not only for Mockoon but for a lot of application using the same kind of installer). 
You can save your mocks anywhere on your hard drive, or in Mockoon's data folder which is in `~/AppData/Roaming/mockoon`.

I investigated a bit and saw that this Programs folder is the default after a fresh install which is a bit unfortunate. I will open a new issue and change this behavior so this doesn't happen to anyone else in the future.
