### ISSUE TITLE
Is the specify-proxy function worth adding?

### ISSUE THREAD

**Issue by lizy-CZ** [mockoon/mockoon#759]
[whistle](https://github.com/avwo/whistle) is a broswer debugging proxy tool, But in my case, whistle does not catch proxy requests from mockoon.

Is the system proxy function worth adding?

System Proxy: http://127.0.0.1:8899/ “whistle catch successfully”

proxy requests is mean "enabled proxy mode"

**Comment by 255kb** [comment]
Could you please elaborate a bit on what you expect from this feature that is not already covered by Mockoon's [proxy mode](https://mockoon.com/docs/latest/proxy-mode/)?

**Comment by lizy-CZ** [comment]
Some api access to real addresses through mockoon proxy mode, but they through system proxy so whistle is a broswer debugging tool can't catch them.

I hope add new feature: Send the real address to the ip address I set
![](https://s3.bmp.ovh/imgs/2022/07/20/a449674aef621fad.png)

**Comment by 255kb** [comment]
Sorry, we don't plan to support third-party proxy for now. I will close this issue as not planned.

**Comment by lizy-CZ** [comment]
Thank you for your listening and feedback!
