### ISSUE TITLE
queryParams numbers are strings

### ISSUE THREAD

**Issue by Rpgilligan85** [mockoon/mockoon#764]
**Describe the bug**

When I create a queryParam that is a number and attempt to use the param to get faker data, I get mixed results because it is a string and not a number.  I can replace the variable with the same number and everything works as expected. I have a work around where I add 0 to the queryParam and it converts it to a number.

**To Reproduce**

Use setVar and queryParam to retrieve a parameter that is a number. I used (faker 'address.longitude' max min) and when I was getting negative numbers it would the error Max number should be larger than Min number. The numbers I were using were max=-76 and min=-77.

This is what I have and it treats the var as a string: 
```
{{setVar 'myLat'  (queryParamRaw 'lat')  }}
{{setVar 'myLon'  (queryParamRaw 'lon')  }}
```

in this example lets say myLat = -76 and myLon = -77.

`{{faker 'address.latitude' -76 -77 5 }} `---- this will work
`{{faker 'address.latitude' myLat myLon 5 }}` ---- this will not work - I get the Max number should be Larger than Min number

This is my work around:
```
{{setVar 'myLat' (add (queryParamRaw 'lat') 0) }} 
{{setVar 'myLon' (add (queryParamRaw 'lat') 0) }}
```

**Mockoon version:**

1.19

**OS / OS version:**

Windows 11

**Comment by 255kb** [comment]
Query params are always transmitted as strings and parsed as strings by most libraries (we are using [qs](https://www.npmjs.com/package/qs). 
But I think your problem is coming from elsewhere. The `address.latitude` and `address.longitude` helpers both accept a `max` and `min` params, but `max` has to come first: https://fakerjs.dev/api/address.html#latitude

When I try this, it's working:

```
{{setVar 'myLat'  (queryParamRaw 'lat')  }}
{{setVar 'myLon'  (queryParamRaw 'lon')  }}

// myLat and myLon were inverted:
{{faker 'address.latitude' myLon myLat 5 }}
```

**Comment by Rpgilligan85** [comment]
Thanks, I had an if statement checking which was greater and whichever was greater I had places first in my code. It still didn't work for negative numbers but worked for positive numbers. Which is why if I replaced the variable with the actual value it worked.

{{faker 'address.latitude' -76 -77 5 }} ---- this will work
{{faker 'address.latitude' myLat myLon 5 }} ---- this will not

In the example posted, -76 is greater than -77 but those numbers as variables did not work.
