### ISSUE TITLE
Use the falso instead of fakerjs

### ISSUE THREAD

**Issue by tim-hub** [mockoon/mockoon#775]
In the faker parse, we dependents on fakerjs to generate fake data.

- https://github.com/mockoon/mockoon/blob/f88b033cad/packages/commons-server/package.json

Actually, it would be better to switch to other lib (such as falso) to replace fakerjs (for security reason), or add the configuration to let users to switch between falso and fakerjs (to offer the flexibilit)

- [Open source developer corrupts widely-used libraries](https://www.theverge.com/2022/1/9/22874949/developer-corrupts-open-source-libraries-projects-affected)
- [Meet Falso: The Replacement for Faker.js](https://javascript.plainenglish.io/thank-you-faker-now-its-time-to-move-on-27253d3b0885)

**Comment by 255kb** [comment]
Soon after the Faker.js thing we switched to a community maintained package: https://fakerjs.dev/
They are really active and took over the project and the Open Collective. I think it's even more active than Falso. 

So, I think we are safe now. And there is currently no plan to add another lib, and probably adding Falso alongside Faker.js would be a bit redundant.
