### ISSUE TITLE
Cannot open environment

### ISSUE THREAD

**Issue by Ishwor-Shrestha** [mockoon/mockoon#803]
**Describe the bug**
Cannot open environment

The stacktrace
```
[APPLICATION]Unexpected error: Cannot read properties of null (reading 'lastMigration') - TypeError: Cannot read properties of null (reading 'lastMigration')
    at n.verifyData (file:///opt/Mockoon/resources/app.asar/dist/renderer/main.c5647f2e2d39d3be.js:1:850397)
    at file:///opt/Mockoon/resources/app.asar/dist/renderer/main.c5647f2e2d39d3be.js:1:844965
    at e.subscribe.u (file:///opt/Mockoon/resources/app.asar/dist/renderer/main.c5647f2e2d39d3be.js:1:321444)
    at Te._next (file:///opt/Mockoon/resources/app.asar/dist/renderer/main.c5647f2e2d39d3be.js:1:156670)
    at Te.next (file:///opt/Mockoon/resources/app.asar/dist/renderer/main.c5647f2e2d39d3be.js:1:151586)
    at Te._next (file:///opt/Mockoon/resources/app.asar/dist/renderer/main.c5647f2e2d39d3be.js:1:151891)
    at Te.next (file:///opt/Mockoon/resources/app.asar/dist/renderer/main.c5647f2e2d39d3be.js:1:151586)
    at file:///opt/Mockoon/resources/app.asar/dist/renderer/main.c5647f2e2d39d3be.js:1:160505
    at v.invoke (file:///opt/Mockoon/resources/app.asar/dist/renderer/polyfills.317d143b3e61de53.js:1:7221)
    at Object.onInvoke (file:///opt/Mockoon/resources/app.asar/dist/renderer/main.c5647f2e2d39d3be.js:1:251360)
```

**Mockoon version:**
1.20.0

**OS / OS version:**
elementary OS 5.1.7 Hera
Built on Ubuntu 18.04.6 LTS
Linux 5.4.0-91-generic
GTK 3.22.30

**Comment by RossHS** [comment]
Hello everyone, while working with a colleague, I found exactly the same error. Experimentally, i find out that the problem was hidden in the file name, my work colleague created a file with that name `WEB-2177,WEB-2092`, but macOS converted it to `WEB-2177%2CWEB-2092` (idk how). And the file was impossible to open on other PCs, but if you remove the symbols in the middle, then everything works as it should

**Comment by saeedhbi** [comment]
> Unfortunately, the application updated itself to release 3.0.0 and now I do have this error in the Linux Ubuntu environment.
> 
> `[APPLICATION]Unexpected error: Cannot read properties of null (reading 'lastMigration') - TypeError: Cannot read properties of null (reading 'lastMigration')`
> 
> I didn't change anything. I just reopened the application and now I can't access my environments.
> 
> Also, I tried to create a new environment but now I even can't create with this error:
> 
> `[SERVICE][STORAGE]Error while saving /home/www/snap/mockoon/25/.config/mockoon/storage/dev.json: Error: EACCES: permission denied, open '/home/www/snap/mockoon/25/.config/mockoon/storage/dev.json.lock'`

I tried to change the location of environments and now it's working. Please add this to the release changelog breaking part because I used everything with default configuration.

**Comment by 255kb** [comment]
> I tried to change the location of environments and now it's working. Please add this to the release changelog breaking part because I used everything with default configuration.

Sorry you had to go through this. It's the first time it was reported, and it seems to be linked to the way Snap packages update themselves. They remove the old version folder, where you saved your environment. This folder shouldn't be used to store environments, but I guess it was suggested by default, a bit like in #756 
I will open a new issue and try to prevent this situation in the future.
