### ISSUE TITLE
[win11] This logo is not easy to see in the menu bar

### ISSUE THREAD

**Issue by Romic77** [mockoon/mockoon#807]
![image](https://user-images.githubusercontent.com/14304457/187074748-d5116bb1-351f-462b-abcb-e4dc17ffa400.png)
This logo is not easy to see in the menu bar

**Comment by bewareilive** [comment]
![image](https://user-images.githubusercontent.com/26020170/188532849-386fcca9-8b20-4d94-9b44-085f38460e27.png)
错的不是mockoon，错的是windows ←_←
