### ISSUE TITLE
Allow cli to connect to remote mockoon environment

### ISSUE THREAD

**Issue by Erf-** [mockoon/mockoon#815]
Allowing cli to connect to remote mockoon environment would require:
- enabling cli commands entrypoint configuration in the remote environments
- enabling cli commands default target configuration in the cli settings
- enabling cli commands multiple targets configuration in the cli settings
- adding flags to target the desired remote mockoon environment

This new feature could also change the behaviour of existing commands. For instance the list command could either:
- provide a listing of mock servers running on the default target environment and accept flags to target another
- and/or provide the listing of mock servers running on the targets environments described in the cli settings

**Comment by 255kb** [comment]
Considering the recent changes to the CLI, I don't think this will ever happen. I will close in favor of #901 which make more sense.
