### ISSUE TITLE
Mockoon freezes when opening menu in Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by timpelo** [mockoon/mockoon#817]
Opening application any application menus in Mockoon seems to freeze whole application in Ubuntu 22.04 LTS. Application works well when opening. I can use editor and browse different endpoints. But once I open menu, it shows up as blank and soon after application freezes and doesn't wake up. I am forced to force quit application.

I have tried reinstall Mockoon multiple times. Both using Snap GUI and Snap from terminal. Both ways end up freezing the application. Attached image shows what happens, right after taking screenshot, application freezes and I have to force quit it.
![mockoon_freeze](https://user-images.githubusercontent.com/12793475/191426600-2f5ef7b5-8beb-49f0-ab40-a3f8f8b0a861.png)

**Comment by 255kb** [comment]
Tested latest build, where Electron was updated to v21, with Ubuntu 20 and 22 and everything seems to be ok.
