### ISSUE TITLE
Not able to use query params in data-buckets for dynamic response generation

### ISSUE THREAD

**Issue by kalpeshhpatel** [mockoon/mockoon#848]
1. Define the data-buckets like below:

```
[
  {
    "userId": 1,
    "name": "{{queryParam 'name'}}",  <== Here we are using `name` queryParams to return dynamic response based on request
  }
]
```

2. Use the above data-buckets in the given route.
3. Start the server
4. Visit the API with `?name=john` queryparam.
5. The response contains the expected JSON with ```name:john```
6. Now, hit the same request with different value for the ```name``` param
7. The API response still contains the JSON with ```name:john``` and not the current/latest value of query params.

The above is just an example with queryParams template helper. Not sure if there and issues with other template helpers also.

**Mockoon version:**

1.21.1

**OS / OS version:**

MAC

**Comment by 255kb** [comment]
This is by design. Databuckets are generated at server start, except when they contain request helpers. They are then generated during the first call and persisting with the same data during all the calls.
See docs https://mockoon.com/docs/latest/data-buckets/overview/
