### ISSUE TITLE
CORs blocking when trying to include credentials

### ISSUE THREAD

**Issue by pflima92** [mockoon/mockoon#85]
**Describe the bug**
The API request is failing when the request includes credential.

`Access to fetch at 'http://mockoon/api/foo' from origin 'http://localhost' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.`

**To Reproduce**

From browser make a request with a header: `Access-Control-Allow-Credentials: true`

**Expected behavior**
Respond when trying to include a credential

**Mockoon version:**
1.2.0

**OS / OS version:**
Windows 10

**Comment by 255kb** [comment]
Where did you define http://mockoon domain? In the hosts file?

**Comment by pflima92** [comment]
> Where did you define http://mockoon domain? In the hosts file?

Yes, it's happening because my application needs to send credentials. I've an api gateway that can be used to avoid that, but call directly mockoon would be great for the development process. Btw, awesome work so far.

**Comment by 255kb** [comment]
Thank you :) 
I will investigate this for the next release (but this will not be soon as I just released one) .

**Comment by pflima92** [comment]
I tried to update the Environment Headers setting: Access-Control-Allow-Origin: http://localhost:3001

![image](https://user-images.githubusercontent.com/13289463/50231546-3030e800-0396-11e9-89b0-b8485e19aa35.png)

But the options route still returning the wildcard *:

HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET,POST,PUT,PATCH,DELETE,HEAD,OPTIONS
Access-Control-Allow-Headers: Content-Type, Origin, Accept, Authorization, Content-Length, X-Requested-With
Content-Type: text/plain; charset=utf-8
Content-Length: 2
ETag: W/"2-nOO9QiTIwXgNtWtBJezz8kv3SLc"
Date: Wed, 19 Dec 2018 15:54:25 GMT
Connection: keep-alive

**Comment by 255kb** [comment]
@thammadi Thank you :) 

I think the fix should be simple, the "CORS" headers automatically added cannot be overridden by the environment headers. 
I will plan this for the next release.

**Comment by wfpaisa** [comment]
just to share if anyone has the same problem it can be solved with `Access-Control-Allow-Credentials=true` and changing the '*' to the domain name.
![image](https://user-images.githubusercontent.com/1735752/189215859-f88b50ec-5fd1-4033-b754-d06787a31498.png)
