### ISSUE TITLE
Add padLeft / padRight helpers

### ISSUE THREAD

**Issue by Otiel** [mockoon/mockoon#855]
It would be great to have `padLeft` / `padRight` helpers in order to pad a string with other characters.

For instance, I'd like to generate identifiers starting with zeros using `{{@index}}` in a `{{#repeat }}` loop: instead of having the following ids : `1, 2, 3, 4, 5, ...`, I'd like to get `00001, 00002, 00003, 00004, 00005, ...`

faker.js doesn't offer this kind of helper.

_Originally asked on discussion #850_

**Comment by 255kb** [comment]
This has been released in [v3.0.0](https://mockoon.com/releases/3.0.0/).

**Comment by Otiel** [comment]
Thank you!
