### ISSUE TITLE
Add import/export for Swagger / OpenAPI format

### ISSUE THREAD

**Issue by 255kb** [mockoon/mockoon#86]
Implement feature to import/export JSON or YAML files in Swagger / OpenAPI format.
Both v2.0 and 3.0 of the format will be supported.

(OpenAPI format was chosen after a poll in #38)

**Comment by mixels** [comment]
This issue mentions both Swagger and OpenAPI. Is that Swagger v2 _and_ OpenAPI v3? Or one or the other?

**Comment by 255kb** [comment]
Yes, Swagger format (Swagger 2.0) is now OpenAPI v3. (Source: https://swagger.io/docs/specification/about/) They are basically two versions of the same thing, a little bit different but not too much. So creating one parser for both should not be that complicated (it's already WIP). 
However, I won't be able to support everything from the specification, some complex behaviors are not easily importable.

**Comment by aakash1313** [comment]
@255kb : When is swagger import expected to be released?

**Comment by 255kb** [comment]
@aakash1313 I started working on it, but I have very limited time at the moment to work on Mockoon, so don't expect this feature before several weeks / months

**Comment by alexsandro-xpt** [comment]
+1

**Comment by bart** [comment]
+1

**Comment by gervaisb** [comment]
Exporting a mock to OpenApi will be a great feature too. 
For sure you will not be able to generate a fully featured spec but the skeleton will be a good starting point.

**Comment by 255kb** [comment]
@gervaisb I wanted to ask this exact question! I am currently working on this, import is already well advanced (multiple route support, headers, etc only thing is to generate mock data based on the objects references in the openapi file). But I wondered if export would make sense as we may not generate something as rich as an regular OpenAPI file.

**Comment by gervaisb** [comment]
I can easily imagine that someone will use _mockoon_ to draw the API. When the state is tested and approved by other it generate the spec and give it as base document for others that complete it with the details. 
But since the routes, responses and main rules are defined the remaining part is documentation and "implementation detail"..

**Comment by 255kb** [comment]
@gervaisb that's true, it would definitely be useful. 
It will be in release 1.6.0 but there is still some work to do

**Comment by fsalata** [comment]
Any update on this?

**Comment by 255kb** [comment]
@fsalata I finished the import part, I must now write the tests and the export (which will be quicker). But I have limited time to work on Mockoon (it's a side project), and reviewing contributions, answering messages, etc is already taking a lot of time!
I hope you understand :)
But it will definitely be in the next version.

**Comment by mackelito** [comment]
I just found this project and just wanted to say how nice it is!
Keep up the good work! If I'm ever in Luxembourg I'll buy you a 🍺! 😄

**Comment by 255kb** [comment]
@mackelito thanks for the kind words! :smile: 
This feature is definitely coming for v1.8.0, which will be quite a big release. 
Everything took more time than planned and the time I could spend on the project was scarcer during the last months...
