### ISSUE TITLE
this can't be used in helpers

### ISSUE THREAD

**Issue by volkerrichert** [mockoon/mockoon#860]
**Describe the bug**

I try to use "this" from an each loop inside other helpers. This will result in an error "Error while serving the content: (depth0 || alias2).call is not a function".

I'd like to access the data store like so: {{dataRaw 'ID' (this)}}. I like to return some predefined values for that store depending on the query params

**To Reproduce**

This is just a breakdown
[
  {{#each (queryParamRaw 'arrayParam')}}
{{lowercase (this)}}{{#unless @last}},{{/unless}}  
  {{/each}}
]

**Mockoon version:** 1.21.1

**OS / OS version:** MacOS

**Comment by 255kb** [comment]
I just figured this out. You have to remove the parentheses around this, otherwise, Handlebars will look for a helper. 
I am afraid there is no way to make the error message clearer.
