### ISSUE TITLE
setVar helper create empty lines

### ISSUE THREAD

**Issue by O-heu** [mockoon/mockoon#872]
**Describe the bug**

The setVar helper creates empty lines in the response.

**To Reproduce**

_Template_
```
[
  {{#each (array 'Test1' 'Test2' 'Test3' 'Test4' 'Test5' 'Test6' 'Test7' 'Test8' 'Test9' 'Test10')}}
      {{setVar 'maxResult' (add 1 @maxResult)}}
      {{#if (lte @maxResult (queryParamRaw 'maxResult'))}}
       {"name": "{{this}}"},
      {{/if}}
  {{/each}}
]
```

_Call_
`http://localhost:3000/test?maxResult=1`

_Response_
```
[
      
       {"name": "Test1"},
      
      
      
      
      
      
      
      
      
]
```

**Mockoon version:**

v1.21.1

**OS / OS version:**

MacOS 12.6.1

**Comment by 255kb** [comment]
This is not a bug. The line returns are part of what you wrote and not generated by the helpers: 
![image](https://user-images.githubusercontent.com/7489814/205020593-aac68153-531f-4cf3-81f1-df6f90155db3.png)
There is no plan to change this behavior.

**Comment by O-heu** [comment]
I see, so maybe an option to prettify the response would be nice. Because writing complex templates in one line would be very difficult to read.

**Comment by 255kb** [comment]
That would make more sense. Could you please open a separated issue for such a feature? Like "enable JSON response pretty print".
Thanks 😀
