### ISSUE TITLE
Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by eliseubamaral** [mockoon/mockoon#878]
**Describe the bug**
When I request mockoon, an expected response is not returned and on logs I can see this error:
`2022-12-03 11:33:49 (node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit`

**To Reproduce**
Justa run mock on and make any request.

**Mockoon version:**
Mockoon/cli:2.2.1

**OS / OS version:**
macOs Ventura 13.0.0

**Comment by 255kb** [comment]
Could you please indicate your Node.js version?

**Comment by 255kb** [comment]
We tried to reproduce with the same setup with no luck. 
Could you please provide you Mockoon data file to see if it is linked to a specific feature? 
Thank you.

**Comment by 255kb** [comment]
@eliseubamaral Could you retry with the latest CLI version (v3.0.0)? A lot of dependencies were updated, something may have fixed this issue. Thank you.

**Comment by 255kb** [comment]
Closing this as non reproducible.
