### ISSUE TITLE
Add cli parameter or environment variable to provide proxyHost value

### ISSUE THREAD

**Issue by MPritsch** [mockoon/mockoon#886]
Hello,

I was recently tasked to provide mockoon as a mocking service with our dev environment in the cloud. As far as I can tell the local and cloud mockoon configuration can stay the same with the exception of the proxyHost variable. Locally it needs to be "http://localhost:8080" while in the cloud it needs to point to our backend server URL.
Maybe I'm overlooking something, but I couldn't find an option to provide this proxyHost parameter with the CLI or an environment variable.

We want to use a docker image to provide mockoon. Without a parameter for the proxyHost we are left with 2 options. Both are suboptimal:
* Use somekind of sed or envsubst solution to modify the data.json during the docker build or entrypoint process
* Duplicate the data.json per environment and only change the proxyHost variable. This is obviously error prone when having to manage multiple environments.

If this is not implemented yet I would suggest a environment variable like this, which would overwrite the parameter defined in the data.json:
PROXY_MODE
PROXY_HOST

For the cli directly it could be something like this for the start command:
--proxy-host <proxy-backend-url>

Best Regards

**Comment by 255kb** [comment]
Thank you for opening this issue. 
I would rather try to limit the number of flags the CLI offers and favor the env var approach. 
A contributor is currently working on [bringing env vars to Mockoon](https://github.com/mockoon/mockoon/issues/849). It would work both with the CLI and the desktop app. 
The idea is to automatically detect the env vars prefixed with MOCKOON_, and create a new templating helper `{{env 'VAR_NAME'}}` that we could use in the different input fields (or JSON values). 
If this would work for you I will close this issue as duplicate. 
Let me know.

**Comment by MPritsch** [comment]
If the env variables just mirror the json fields this will work fine.

**Comment by 255kb** [comment]
Ok, I will close it as dup then. 
The implementation will be a bit different though. We will have to indicate in the various fields that env vars must be used. So, there will be no automatic use of env vars (at least yet).
