### ISSUE TITLE
mockbin / request recording option

### ISSUE THREAD

**Issue by hargut** [mockoon/mockoon#89]
Hello,

thank you very much for creating mockoon. It's a nice and easy tool which I like using.
Sometimes I'd really love to have a request recording option, to mock API's even faster.

The idea here would be to open a port, accept all requests (mockbin style, return 200), and add an according route pre-filled with the requested parameters (method, path, parameters, body), so the user "just" has to care about the response body to be updated/corrected/templated.

It would also be helpful to have an option to convert logged requests into routes.

Many thanks for your consideration.

Best regards,
Harald

**Comment by 255kb** [comment]
Closing this in favor of #139
