### ISSUE TITLE
Templating request helper: queryParam fails with objects

### ISSUE THREAD

**Issue by elrasco** [mockoon/mockoon#891]
Mockoon Desktop Relase: 1.21.1
Mockoon cli: 2.2.1

About queryParam request helper, [documentation](https://mockoon.com/docs/latest/templating/mockoon-request-helpers/#queryparam) says: **Complex query strings with arrays and objects are supported**.

This is the url I'm mocking: ```http://localhost:3100/comlex/qs?p={"page":2}```

This is the body
```
{
  "page": "{{queryParam 'p.page' }}"
}
```
[here](https://gist.github.com/elrasco/c5df8aca86b1a008060b2c9a60c1837a) mockoon file

As response, I would expect 
```
{page: "2"}
```

I have this 
```
{page: ""}
```

**Comment by 255kb** [comment]
Sorry for the confusion, JSON is not directly supported in the query string. Mockoon is using Express which is using [qs](https://www.npmjs.com/package/qs) to parse the query string. 
The supported syntaxes to create objects and arrays are the following: 
```
// objects
?prop1[prop2]=value
--> 
{
    prop1: {
        prop2: 'value'
    }
}
```

```
// arrays
?prop[]=value1&prop[]=value1
--> 
{
    prop: [
        'value1',
        'value2'
    ]
}
```

I will update the documentation to avoid any confusion in the future.
