### ISSUE TITLE
Path selection with dataRaw does not work

### ISSUE THREAD

**Issue by dashie** [mockoon/mockoon#892]
**Describe the bug**

I'm trying to use `{{dataRaw 'datatest' 'items'}}` into a API but it continues to return the full data bucket content

**To Reproduce**

Creating the data bucket `datatest` with this content:

```
{
  items: [
    {
      "id": "1",
      "desc": "data 1"
    },
    {
      "id": "2",
      "desc": "data 2"
    },  
  ]
}
```

Create and API and try to use that data bucket:

```
----
{{dataRaw 'datatest' 'items'}}
----

```

**Mockoon version:**

v1.21.1

**OS / OS version:**

Mac OS (Apple Silicon)

**Comment by dashie** [comment]
Maybe it is because `items` is not between double quotes? But I do not have any error about that.

**Comment by 255kb** [comment]
> Maybe it is because `items` is not between double quotes? But I do not have any error about that.

Yes, this should be it. 
The data bucket will be generated in two passes. Frist, is the templating system with all the helpers, then it will try to parse from JSON. But it has to be valid JSON, which lack of double quotes is not. Also, the trailing comma after the second object is not valid either.
This should work: 
```
{
  "items": [
    {
      "id": "1",
      "desc": "data 1"
    },
    {
      "id": "2",
      "desc": "data 2"
    }
  ]
}
```
