### ISSUE TITLE
Silent mode

### ISSUE THREAD

**Issue by vltansky** [mockoon/mockoon#895]
I'd be really happy for silent mode, can be introduec as flag `-s, --silent. I'm using mockoon-cli to run mocks parallel with my client. I'd want to see the output only from my client cli. Probably there are some workarounds to achieve this of course but a silent flag could be a good addition to cli.

**Comment by 255kb** [comment]
Could you please elaborate a bit on what you expect from such flag? Would it just suppress all logging sent to the console?

**Comment by vltansky** [comment]
Yes that’s exactly what I would expect. No console output

**Comment by 255kb** [comment]
I wonder if this could be solved together with #868 

Using a flag like `--logging file,console`, or `--logging none`. Not sure if it's a standard way to do it. 

Current logging default is: 
- files: always
- console: if `--daemon-off`

**Comment by vltansky** [comment]
yep, sounds good

**Comment by dosmanak** [comment]
I am not sure it is a good idea to disable logging at all.
Especially when you can disable stdout and stderr using `>&/dev/null`. However id there is such need I am not against it.

**Comment by vltansky** [comment]
@dosmanak good point about `>&/dev/null`
changed my package.json script to:

`mockoon-cli start .... &> '/dev/null'`

**Comment by 255kb** [comment]
I will close this issue as `> /dev/null` or `> NUL` (Windows) is a common/standard workaround and avoid introducing a new flag. I will update the documentation.
