### ISSUE TITLE
start/stop all environments simultaniously

### ISSUE THREAD

**Issue by hargut** [mockoon/mockoon#90]
Hello,

during the past usage of mockoon I've already created several environments which do their job nicely. I've created each API on a separate environment, one per service, and need most of the time all of them running.

So far I could not find an easy way to start/stop all of them at the same time.
It would be helpful to have a "start all"/"stop all" option.

Best regards,
Harald

**Comment by Manikkumar1988** [comment]
Why do you have single API in one environment? Any specific purpose?

**Comment by 255kb** [comment]
@Manikkumar1988 Can make sense because you can name them differently, have different ports, etc.
But I think this feature could be useful anyway.

**Comment by axc450** [comment]
I can look into adding this, but it might not make it into the next release

**Comment by codingcircus** [comment]
I created a PR for this: https://github.com/mockoon/mockoon/pull/348
