### ISSUE TITLE
Serverless package is not publicly available

### ISSUE THREAD

**Issue by delenamalan** [mockoon/mockoon#919]
Not sure if this was intended, but the serverless package isn't publicly available at https://www.npmjs.com/package/@mockoon/serverless or via the CLI:

```
npm install @mockoon/serverless
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@mockoon%2fserverless - Not found
npm ERR! 404
npm ERR! 404  '@mockoon/serverless@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git URL
```

**Comment by 255kb** [comment]
Package is not yet published. The release will come in the coming days. Unfortunately, I realize that I merged the branch including the repository documentation before christmas 🥴
Sorry for this!
