### ISSUE TITLE
Can't maximize the window on Linux

### ISSUE THREAD

**Issue by instalab** [mockoon/mockoon#92]
**Describe the bug**
When I try to maximise the window (because I have small screen and I am always working with maximised windows), nothing happens, I can press the icon/button next to the close button but it's not responding, F11 is not working either.

**To Reproduce**
Press the 'maximise' button and nothing happens. 

**Expected behavior**
The window should enlarge itself to cover the whole screen. 
F11 should enlarge the window to cover absolutely whole screen, even panels.

**Mockoon version:**
1.3.0

**OS / OS version:**
Arch Linux x86_64, xfwm4 4.12.5-1 (XFCE 4)

**Comment by axc450** [comment]
I cannot reproduce this on Ubuntu 18.04 and I don't have an Arch VM set up atm ☹️ 
Have you tried building from npm, running the dev version and looking at the console for any errors?

**Comment by tiagoppinho** [comment]
Having the same issue.

The maximize button doesn't even show up on my case. F11 does also does not work, same with all the shortcuts to resize windows.

I can resize it to larger on the right and left sides but can't resize to smaller in any of the sides or corners.

**Mockoon version:**
1.3.0

**OS / OS version:**
Linux - Ubuntu 18.04.2 LTS

**Comment by 255kb** [comment]
@tiagoppinho @instalab Is this still an issue with latest version (1.7.0)?

**Comment by instalab** [comment]
> @tiagoppinho @instalab Is this still an issue with latest version (1.7.0)?

Sorry for taking ages to respond (wow, this is an old bug :P)
I just tested .AppImage on my ArchLinux and the 'resize' button seems to be working :+1: 
The F11 is still not working for me, but it's not a big issue as I can just use the 'resize' button.

**Comment by 255kb** [comment]
Thank you for your answer. Indeed it's an old bug 🙂

Apparently it was a problem with electron itself.
If you want to be able to use keyboard shortcuts to resize, feel free to open an issue.
