### ISSUE TITLE
Git integration

### ISSUE THREAD

**Issue by matheus-miranda** [mockoon/mockoon#924]
Would be really nice to have some sort of git integration, color-coding lines where edits are being made, kinda like on VS code.

**Comment by 255kb** [comment]
You can already easily [track your data files with git](https://mockoon.com/docs/latest/mockoon-data-files/sharing-mock-api-files/#use-a-git-tracked-folder) and an external tool. I don't think we should implement this inside of Mockoon's interface. 

I will close this issue for now. We may reopen if it gathers more interest.
