### ISSUE TITLE
Data bucket behaves different with same template

### ISSUE THREAD

**Issue by IchHabRecht** [mockoon/mockoon#928]
**Describe the bug**

**To Reproduce**

Given template:

```
{{#repeat (queryParamRaw 'limit' (faker 'datatype.number' min=3 max=20)) comma=true}}test{{/repeat}}
```

- create a route with the given template as inline body
- call the route and you see a list of "tests"

- add a data bucket using the same template
- change the route's body to use the data bucket
- call the route again and you get an empty respose
- it's the same using the query param or not

**Mockoon version:**

1.22.0

**OS / OS version:**

Windows

**Comment by 255kb** [comment]
Could you please provide samples of the request's full URL (including the query string). Thanks.

**Comment by 255kb** [comment]
Thank you. 
I think there is a mistake in the regex detecting imbricated request helpers. Thus, they get ignored. 
I will fix this for the next release.
