### ISSUE TITLE
Support Hide / Hide Others / Settings standard shortcuts on macOS

### ISSUE THREAD

**Issue by joshlewis** [mockoon/mockoon#93]
Nearly every Mac app supports a few standard keyboard shortcuts. Quit being ⌘Q is one of those, and you're supporting that. That's good!

Here are a few others I'd love to see supported, in order of importance:

Hide: ⌘H
Settings / Preferences: ⌘,   (That's Command-Comma, and yes, that's a standard! 😄)
Hide Others: ⌥⌘H  (Option-Command-H)

**Comment by axc450** [comment]
Added this:
https://github.com/255kb/mockoon/pull/108

**Comment by 255kb** [comment]
Thank you for the contribution @axc450 !

**Comment by 255kb** [comment]
Released in v1.4.0
