### ISSUE TITLE
Expose port in Dockerfile

### ISSUE THREAD

**Issue by pedroescumalha** [mockoon/mockoon#932]
### Issue

The current Dockerfile for the mockoon cli doesn't expose a port. This would be very useful for developers trying to run this image as a [service in a gitlab's CI/CD pipeline](https://docs.gitlab.com/ee/ci/services). Gitlab doesn't allow to specify a port in this feature, they use the exposed port of the Dockerfile, and since there's none, it fails to start the service.

### Solution

Expose the port 3000 (I believe it's the default for the mockoon server) on the Dockerfile.

**Comment by 255kb** [comment]
I am not very familiar with GitLab CI, but you mean you cannot publish ports at runtime (like `docker run -p 3000:3000`)?
The main reason we don't have an exposed port in the published image is that we do not know in advance on which port the mock is supposed to run.  
I guess we could just add an `EXPOSE 3000` and it would still let users override at runtime with `-p xxxx:xxxx`.

**Comment by pedroescumalha** [comment]
Unfortunately no. There's a feature request on Gitlab's side to allow publishing ports dynamically, but it has been open for a while.
I think that solution makes sense, because if we don't specify a port in the CLI command it also starts on the port 3000, and if we do, then it's overridden by the parameter `-p xxxx:xxxx`.

I have, but no luck. Looking at [Wiremock's Dockerfile](https://github.com/wiremock/wiremock-docker/blob/main/Dockerfile#L52), currently they are also exposing ports and navigating back on the repo looks like they always were. Seems like that user's problem was a different one.

**Comment by 255kb** [comment]
@pedroescumalha thanks for the feedback!

**Comment by RaHehl** [comment]
@pedroescumalha I'm also currently trying to use mockoon as a service in a GitLab CI pipeline. https://docs.gitlab.com/ci/services/ "The service must detect when the job directory is populated and ready for processing. For example, wait for a specific file to become available." How did you solve this? I'm currently building a custom image with a customized entrypoint.

**Comment by pedroescumalha** [comment]
@RaHehl at the time I copied [mockoon's dockerfile](https://github.com/mockoon/mockoon/blob/main/packages/cli/docker/Dockerfile) and created a custom image with the exposed port, that way gitlab knows the port where the service runs on. i believe the port has been exposed by @255kb since then

**Comment by 255kb** [comment]
> [@RaHehl](https://github.com/RaHehl) at the time I copied [mockoon's dockerfile](https://github.com/mockoon/mockoon/blob/main/packages/cli/docker/Dockerfile) and created a custom image with the exposed port, that way gitlab knows the port where the service runs on. i believe the port has been exposed by [@255kb](https://github.com/255kb) since then

Indeed, the default port (3000) is exposed in the Dockerfile: https://github.com/mockoon/mockoon/blob/main/packages/cli/docker/Dockerfile#L14
