### ISSUE TITLE
Node.js 14 end of support

### ISSUE THREAD

**Issue by 255kb** [mockoon/mockoon#959]
In april 2023, remove Node.js 14 from supported engines for the CLI/libs.

- [ ] update `engine` from multiple package.json
- [ ] Use Node 16 (or 18, with longer LTS) in all CI workflows
- [ ] update Node.js versions for the CLI test matrix with more recent versions and remove 14
- [ ] update dockerfile node version and dockerize command template

**Comment by likileads** [comment]
Hi @255kb, I wish to work on this issue.
Can you please assign this to me.

**Comment by 255kb** [comment]
Sure, thank you :) 
Let me know if you have any question. You can also join our [Discord server](https://discord.com/invite/JmTBk59MTb).

**Comment by likileads** [comment]
Please review my [PR](https://github.com/mockoon/mockoon/pull/998).
Let me know if there's any changes.

**Comment by 255kb** [comment]
If you don't mind I will finalize this PR today as it is currently blocking two other. Thanks 🙂

**Comment by 255kb** [comment]
This has been released in [v3.0.0](https://mockoon.com/releases/3.0.0/).
