### ISSUE TITLE
Support for current/system date-time in response body

### ISSUE THREAD

**Issue by thammadi** [mockoon/mockoon#96]
Hi @255kb,

I bumped into a requirement, where I'm expecting one or more attributes in my response body to have the current system timestamp. Just like how we use {{guid}} for random guid, is it possible to add support for date-time please? may be {{date}}, {{time}} or both together {{datetime}}?

Cheers,

**Comment by thammadi** [comment]
@255kb Yes, I have read the documentation and I'm using it something like this:
`"created": "{{date '2019-01-01' '2019-01-30' 'YYYY-mm-ddThh:mm:ssZZ'}}"`

However, Dummy JSON template will always return a random date time.
What I am looking for is {{current-system-datetime}} which would return '2019-01-29T12:45:50'

Is it possible?

**Comment by 255kb** [comment]
This will be in the next release where you will be able to use `now 'YYYY-MM-DD'` (format is optional and default to ISO string)

**Comment by Lepidopteron** [comment]
Does not work any longer on v1.12
```
Error while serving the content: Format string contains an unescaped latin alphabet character `Z`
```

Also the `T` in between the date and time is now formatted to a timestamp.

**Comment by 255kb** [comment]
> Does not work any longer on v1.12
> 
> ```
> Error while serving the content: Format string contains an unescaped latin alphabet character `Z`
> ```
> 
> Also the `T` in between the date and time is now formatted to a timestamp.

It's a little bit tricky since a `date-fns` update but this should work: `{{ now "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" }}` (note the double and single quotes) or this: `{{ now 'yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\''}}`

**Comment by Lepidopteron** [comment]
Thanks for pointing me to the right direction.
Solution would look like `{{ now "yyyy-MM-dd'T'HH:mm:ssXXX" }}`
Timezone is now `XXX`: https://date-fns.org/v2.22.1/docs/Time-Zones
