### ISSUE TITLE
Search not working with folders

### ISSUE THREAD

**Issue by TheoQQP** [mockoon/mockoon#960]
**Describe the bug**

Since the latest Mockoon version, we are unable to search for a route that is inside a collapsed folder.

**To Reproduce**

Create a route, put it inside a route folder. Collapse that folder. Try and search for the route (using the filter text box), it cannot be found . I don't know if this is really a bug or a wanted behavior but it does make finding routes a bit harder when they are organized into folders. If it's wanted behavior, could we have an option to filter/search routes inside all folders (opened or not) and another option that only filters/searches with opened folders? Thank you!
Edit: another quick fix that could do the job would be to have a button to expand all folders so search would work fine

**Mockoon version:**

1.22.0

**OS / OS version:**

N/A

**Comment by 255kb** [comment]
📦 This is now available with [release v4.0.0](https://mockoon.com/releases/4.0.0).
