### ISSUE TITLE
Use OpenAPI examples

### ISSUE THREAD

**Issue by mathilde-lannes** [mockoon/mockoon#962]
Hello,

Thanks for all the great work on Mockoon, it's an amazing tool.

I'm using Mockoon to generate a mock server for my API, based on an OpenAPI spec file. I have examples for each endpoint response in my spec and I'd like to get one different possible response for each example in Mockoon.

For instance this endpoint has two examples : 

```yaml
  '/categories/{id}/activities':
    get:
      summary: List of activities
      tags:
        - categories
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/activities'
              examples:
                Sport:
                  value:
                    - id: 7
                      name: Basket-ball
                    - id: 8
                      name: Tennis
                Hobbies:
                  value:
                    - id: 9
                      name: Knitting
```

And I'd like to get this result in Mockoon when I import my OpenAPI specification file :  

<img width="563" alt="image" src="https://user-images.githubusercontent.com/10697680/221143245-fd48328b-fc1a-404e-99e6-6ac04ad6439d.png">

I saw on the discussion #519 that you don't support the `examples` OpenAPI property. Is supporting this property on your roadmap ?

Thanks again and have a great day!

**Comment by 255kb** [comment]
Thanks for the kind words 🙂
This is not yet on the roadmap (you can find the roadmap [here](https://github.com/orgs/mockoon/projects/2), we try to avoid listing everything there because we cannot and don't want to add every single feature request by default and not work on them in the end). 
This would probably be a great addition. We currently only [uses the `schema`](https://github.com/mockoon/mockoon/blob/main/packages/commons-server/src/libs/openapi-converter.ts#L297-L322) to generate a body. 
It raises a question though: do we create a response for each example + the schema? 

I'm open to PR if you want to work on this.

**Comment by mathilde-lannes** [comment]
> It raises a question though: do we create a response for each example + the schema?

Maybe the default response can be the one created from the schema, and other responses are created from each example ?


> I'm open to PR if you want to work on this.

Great, I cloned Mockoon locally and managed to develop the feature I wanted. I'll submit a PR soon.

**Comment by 255kb** [comment]
> Maybe the default response can be the one created from the schema, and other responses are created from each example ?
Ok, it makes sense. 

> Great, I cloned Mockoon locally and managed to develop the feature I wanted. I'll submit a PR soon.
Let me know if you need some help. You can also reach me on our [Discord server](https://discord.com/invite/JmTBk59MTb).
I will assign this issue to you.

**Comment by franok** [comment]
Hi, I just found this new awesome feature contribution is now part of the Desktop 1.23.0 release.

The cli release 2.4.0 says it has support for the Desktop version 1.23.0.

**How can I make use of this feature in the mockoon-cli?**

**Comment by 255kb** [comment]
Hi @franok 
It depends. When you import an OpenAPI spec file with desktop v1.23.0 it will automatically add responses for each OpenAPI `example`. Then, you can use your Mockoon data file with the CLI. 
You can also directly run an OpenAPI spec file with the CLI, see: https://github.com/mockoon/mockoon/tree/main/packages/cli#use-an-openapi-specification-file
But please not that by using this approach you are not benefiting from all of Mockoon's features (latency, rules, etc.).

**Comment by franok** [comment]
Hi @255kb thanks for the reply.
I understand that I can generate a Mockoon data file from an openapi.yml and use it with the cli.
However, I wanted to know if openapi-examples can be used with the cli and an openapi.yml file _only_?

I tried the following and it seems like the examples are not used:
```
mockoon-cli start --data https://raw.githubusercontent.com/mockoon/mockoon/d091b91c6c67b13fb40343fec0fe0287a1db2183/packages/commons-server/test/data/openapi/openapi-v3.yaml --daemon-off
```
`GET http://localhost:3000/with-examples`
The response is never one of [the examples defined in the openapi yml](https://github.com/mockoon/mockoon/blob/d091b91c6c67b13fb40343fec0fe0287a1db2183/packages/commons-server/test/data/openapi/openapi-v3.yaml#L41-L66), but always a generated one, e.g.:
```
[
  {
    "id": 33724,
    "name": ""
  }
]
```


Is this a bug or is it expected to not work this way?

Thanks

**Comment by 255kb** [comment]
This is expected. 
If you import the OpenAPI spec in the desktop app you will see that it creates 3 responses but no rules. So, only the first response (the default one will be served). 
![image](https://user-images.githubusercontent.com/7489814/227721525-23505b07-61be-4747-9da8-79c7b9f033fa.png)

Running an OpenAPI mock directly with the CLI is an interesting starting point but it does not configure much out of the box. 
We could eventually go a bit further and decide that after an OpenAPI import, responses are randomize, or sequentialized. But then it would be a default that people may dislike. I don't know, but I don't have a strong opinion on this.

**Comment by franok** [comment]
Ok, thanks for the clarification.
I don't think the default should be changed, but maybe the cli can be enhanced to accept a flag `--use-openapi-examples` (or even better some config file `-c mockoon-cli.config.yaml` with a property `open-api.use-examples: true`)?
With this config/flag being set, the existing OpenAPI examples are used instead of the generated ones.

**Comment by 255kb** [comment]
I have mixed feelings introducing these kind of CLI-specific options. It makes sense when it's something needed in a server environment or facilitate the deployment, like overriding the port, hostname, etc. 
But the OpenAPI import feature in the CLI is shared with the desktop app and I would prefer to implement this globally. The more I think about it the more it seems that randomizing the example responses by default would make sense. 
Maybe you could open a new issue referencing this one?

**Comment by is516972** [comment]
We need option to use examples from OpenApi as is. My be make it optional while import?
