### ISSUE TITLE
Edit File body type in app

### ISSUE THREAD

**Issue by TheoQQP** [mockoon/mockoon#964]
Hello, thank you for this great app!

Could it be possible to edit a file body type directly in Mockoon? (same editor as inline body type would be sufficient)
This would be a great feature as we wouldn't have to find the JSON file we have associated to that response, open that JSON file in any other editor (such as vscode for example) and edit it there. Instead we could simply point to the file in Mockoon, and directly edit it there in-app. It would simplify the editing of a response and improve the experience we have with the app.

This feature might have been already discussed or looked at, but I couldn't find any open issue that had that particular idea or solution.

Edit: Another solution could be to have a "Open file" button next to the "browse" button which would open the file in default editor.

Again, thank you for this great tool, it has been really helpful to us!

**Comment by 255kb** [comment]
📦 This was improved in [v8.0.0](https://mockoon.com/releases/8.0.0/)
