### ISSUE TITLE
Routes Group

### ISSUE THREAD

**Issue by callmedo** [mockoon/mockoon#97]
**Is your feature request related to a problem? Please describe.**
I created one environment for one application project, it has bunch of routes. 

**Describe the solution you'd like**
It would be nice if we can group the routes into folder in current routes list. So we can separate each routes based on their functionality (eg: products -> get,create,delete,etc)

**Describe alternatives you've considered**
Currently i sort it by functionality and placed the related routes near each other

**Comment by hariesnurikhwan** [comment]
We really need this feature as we have nearly 100 of apis to mock. It's really messy right now having ungroup apis.

**Comment by axc450** [comment]
I can look into adding this, but it might not make it into the next release

**Comment by 255kb** [comment]
Yes I think we will keep next release focused on refactoring / performances and OpenAPI import export. 
But this is definitely something we could tackle after this release.

**Comment by Ishwor-Shrestha** [comment]
What is the status for this request? Is this still being considered?

**Comment by 255kb** [comment]
@Ishwor-Shrestha it's definitely on the roadmap but not with a high priority, so no ETA for now

**Comment by Luckey-Elijah** [comment]
This enhancement would be great for those trying to group their mocked API by features for and end-client. Folder-based grouping or even endpoint tagging would be ideal. Just throwing out a use case. Thanks, for the great tool (I really like the search feature 😄)!

**Comment by vuvdoan** [comment]
soo during my christmas holidays I spent sometimes looking into this. I've just started using Mockoon recently, but really like it.  
I am not a frontend developer and the last time I develop something for the real production is like 3-4 years ago.  So you can say, everything here is new to me :)  I was hoping to find someone experienced to discuss about this feature. 

For example:
I started grouping the routes into 'folder' in a classical tree data structure:
`
   folder 1
      |- route 1
      |- route2
   folder 2
     |- route 3
     |- route 4
`
But then I realise Mockoon event management focuses on routes. Having this kind of data structure requires either a lot of refactoring or  having a lot of expensive operations (see the reducer) to check the path of one specific route.  So I decided to use a map as a metadata for each route, which specify in which folder it belongs to.  When rendering I am using something I called virtual folder structure and reconstruct the folder tree using that routes metadata information.

`
   Environment:
       Routes
            route1
                folderPath: 'folder1'
            route2
                folderPath: 'folder2'
            route3
               folderPath: 'folder1/folder1_1'
       Folders
            folder 1
                 folder1_1
            folder2
`

There are advantages and disadvantages doing so.  One biggest advantage for me is, there will be no breaking changes  and it is backward compatible with previous releases and no big changes in the overall architecture (again I am not a frontend developer :) )

I would really love to hear from someone @255kb 

Attached is my progress on this.    
https://user-images.githubusercontent.com/44056027/147551144-67a1e507-73e1-4391-b7a5-0dbc1d3bd4ee.mov

Here is my forked repo:
https://github.com/vuvdoan/mockoon/tree/feature/folders
https://github.com/vuvdoan/mockoon-commons

**Comment by 255kb** [comment]
@vuvdoan Sorry I didn't answer to your message until yet. 
I'm impressed by the amount of work you pulled on this one!

I would like to be sure we are heading toward the right direction before implementing this feature. 
My personal opinion is that it should be enough to have automatic grouping based on the path sections, like Swagger UI does. Which means, you create two routes `GET /users` and `POST /users` and it will create a (virtual) folder `users` without storing anything or requiring any manual step. It would be something visual only and would require less code/maintenance. 
I also know that this is what some users here would expect.
This kind of automatic behavior would be a bit incompatible with manual folder creation I guess. But we could also combine the automated folders based on paths with a "tag" system later for example.

Anyway, I would like to hear other opinions on automated folder display based on path vs manual folder creation.

**Comment by Flavsditz** [comment]
Just my 2 cents here:

Although the idea of automatic grouping sounds good I think it will lead to a lot of grouping that was not desired.
I think the manual solution is better and allows each one to decide on what and how they want to organize.

One example to show problems of the automatic:

I worked at a company where there were some endpoints that were "relics of a distant past". They weren't conforming to the format for naming the API paths but were still in use and management didn't want to spend time on those old products.
These were in theory a group but the paths didn't match.

Also we might just want to group routes by tool or teams (suppose it is a mock for an api-gateway), those might have different path versions: `/api/v1/blabla` and `/api/v2/blabla` and those wouldn't be grouped together although they might need to.

So just some examples to back my claim up ;)

**Comment by 255kb** [comment]
Thanks for the feedback @Flavsditz !
I must admit that the more feedback I get, the less I am sure about what is really needed. I guess manual folder creation is appealing and would solve more use cases. Also, @vuvdoan approach could be interesting. 
1. Manual folders creation.
2. Option to create folders from the paths sections automatically.
