### ISSUE TITLE
List of environments is empty

### ISSUE THREAD

**Issue by danieldaeschle** [mockoon/mockoon#973]
**Describe the bug**

I can click on that pane and hit some different environments that I opened before. But the names won't get displayed. I checked; they have a name in settings.
![image](https://user-images.githubusercontent.com/30751516/222171496-33c07f21-ad21-475f-b60d-244a2b6b8b36.png)

**To Reproduce**

🤷🏼 
It happens with all environments. 

**Mockoon version:**

1.23

**OS / OS version:**

Windows 11

**Comment by 255kb** [comment]
Could you please provide the Mockoon JSON data file?
We are unable to reproduce this behavior on our side.

**Comment by danieldaeschle** [comment]
```
{
  "uuid": "1286d88a-793c-4d28-a93a-02951995a8cf",
  "lastMigration": 27,
  "name": "Test",
  "endpointPrefix": "",
  "latency": 0,
  "port": 3001,
  "hostname": "",
  "folders": [],
  "routes": [
    {
      "uuid": "09990b18-175e-4f79-a03b-0acd121a154d",
      "type": "http",
      "documentation": "",
      "method": "get",
      "endpoint": "",
      "responses": [
        {
          "uuid": "d64eecd0-75b8-46cc-9732-029f9f545b73",
          "body": "{}",
          "latency": 0,
          "statusCode": 200,
          "label": "",
          "headers": [],
          "bodyType": "INLINE",
          "filePath": "",
          "databucketID": "",
          "sendFileAsBody": false,
          "rules": [],
          "rulesOperator": "OR",
          "disableTemplating": false,
          "fallbackTo404": false,
          "default": true
        }
      ],
      "enabled": true,
      "responseMode": null
    }
  ],
  "rootChildren": [
    {
      "type": "route",
      "uuid": "09990b18-175e-4f79-a03b-0acd121a154d"
    }
  ],
  "proxyMode": false,
  "proxyHost": "",
  "proxyRemovePrefix": false,
  "tlsOptions": {
    "enabled": false,
    "type": "CERT",
    "pfxPath": "",
    "certPath": "",
    "keyPath": "",
    "caPath": "",
    "passphrase": ""
  },
  "cors": true,
  "headers": [
    {
      "key": "Content-Type",
      "value": "application/json"
    }
  ],
  "proxyReqHeaders": [
    {
      "key": "",
      "value": ""
    }
  ],
  "proxyResHeaders": [
    {
      "key": "",
      "value": ""
    }
  ],
  "data": []
}
```

**Comment by 255kb** [comment]
Thanks. I forgot, could you also check the logs? https://mockoon.com/docs/latest/mockoon-data-files/settings-and-logs/
This seems to be a UI crash, it should have some logs.

**Comment by danieldaeschle** [comment]
[main.log](https://github.com/mockoon/mockoon/files/10868806/main.log)

**Comment by 255kb** [comment]
I see when the crash is coming from but not why. Nothing changed there since the last version. 
Could you try to close the app, open the settings.json file (see the link I posted earlier to find its location) and remove the content of the `environments` array. Then save the file, relaunch the app, and try to reopen the environment (which seems also fine by the way).

**Comment by danieldaeschle** [comment]
That helped. Thanks!

**Comment by 255kb** [comment]
Great. 
If you reproduce the issue I would be interested to know how. 
Honestly, I don't understand how this happened. This part of the code is quite old. 

I will still update the code a bit to try to prevent further issues like this. Thanks again for reporting.

**Comment by danieldaeschle** [comment]
It happens when there is a path that does not exist anymore, I think.

**Comment by 255kb** [comment]
In the settings file? Normally the app should get rid of these.

**Comment by danieldaeschle** [comment]
Yeah, but there was a path that I think wasn't there anymore...

**Comment by 255kb** [comment]
Ok, strange. I just tested and the wrong path was removed at startup.
