### ISSUE TITLE
Rules don't seem to work

### ISSUE THREAD

**Issue by patlecat** [mockoon/mockoon#975]
**Describe the bug**
I can set whatever rule I want and it doesn't seem to make a difference in the output

**To Reproduce**
I defined in my query: "contacts/:oid/contact/basefields/:contact_id"
that the query param "contact_id" = 111 should throw a 404. But nothing happens, also inverting not. Also applying the inverted rule in 200 won't do anything. Also setting the default to the 404 instead of the 200 won't make a difference.

**Mockoon version:**
1.23.0

**OS / OS version:**
Windows 11

**Comment by 255kb** [comment]
oid and contact_id are not query params but URL params. Query parameters are the one following the interrogation mark.

Could you please retry using the URL param rule option?
Thank you

**Comment by patlecat** [comment]
Awesome, thanks for your help. I could not understand what they mean not from the GUI nor from the manual. Now I get it!
