### ISSUE TITLE
Request body for HTTP POST request  to be logged for serverless moockoon

### ISSUE THREAD

**Issue by indraneel76** [mockoon/mockoon#978]
Currently the request body for POST request is not getting logged in the logs . This would be useful from debugging perpective specially when using moockon on AWS

**Comment by indraneel76** [comment]
Need logging for all HTTP verbs , POST ,GET , PUT , DETELE

**Comment by 255kb** [comment]
As we will reuse the CLI's logging code, it will log every transaction including the request and response information.
https://github.com/mockoon/mockoon/tree/main/packages/cli#logs

**Comment by 255kb** [comment]
📦 This is now available with [release v4.0.0](https://mockoon.com/releases/4.0.0).
