### ISSUE TITLE
Group environments into folders

### ISSUE THREAD

**Issue by fiss7** [mockoon/mockoon#980]
Hi, first, thanks for this very useful project !
It would be great to be able to group environments into folders and start / stop all those are in a folder in one click.
Because for example, in my case, I have a lot of external services proxied (which could be grouped in several categories), and I have to start them one by one. Having the possibility to select a category and start all services inside would be really nice.

**Comment by 255kb** [comment]
Thank you :) 
In the meantime, I know that it's not directly solving your problem, but since v1.23.0 there is an option to auto-start all the environments (but it's starting all of them). You will find this option in the app settings.

**Comment by fiss7** [comment]
Sorry, I didn't see it, it solves it partially, thank you for the tip :)

**Comment by 255kb** [comment]
Considering where the UI is currently headed with the upcoming cloud features, I don't think this will ever be implemented.
