### ISSUE TITLE
Rule doesn't match complex query string

### ISSUE THREAD

**Issue by sonam69** [mockoon/mockoon#981]
**Describe the bug**

Can't create a rule to match a complex query string
The query string i use in postman is party[?(@.role%3D%3D"user")].id
which when decoded results in party[?(@.role=="user")].id
I've tried to add as query string in rules both prementioned version but it never matches the rule.

In mockoon logs i can see the following under the Query params list
Raw query string: party[?(@.role%3D%3D"user")].id = 56ABCGH5
party.?(@.role=="user"): 56ABCGH5

**To Reproduce**
Get Route /user
with multiple responses
first response has no rules and returns all users
other responses have rule to match the query string party[?(@.role%3D%3D"user")].id in order to return a single user

**Mockoon version:** 1.23.0

**OS / OS version:** Windows 11

**Comment by 255kb** [comment]
I don't know what this syntax is but I don't think it is supported by the [qs](https://www.npmjs.com/package/qs) package Mockoon is using to parse que query string. 
You can send objects or arrays using these kind of syntaxes: 
```
foo[bar][baz]=foobarbaz
-->
{
    foo: {
        bar: {
            baz: 'foobarbaz'
        }
    }
}

a[]=b&a[]=c
--> 
{ a: ['b', 'c'] }
```
You can see in the logs tab what has been parse, which is basically this object: 
`{ 'party.?(@.role=="user")': '56ABCGH5' }`

There is no plan to extend the supported syntax or use something else than qs.
