### ISSUE TITLE
Use data buckets in response rules

### ISSUE THREAD

**Issue by 255kb** [mockoon/mockoon#988]
### Discussed in https://github.com/mockoon/mockoon/discussions/986

<div type='discussions-op-text'>

<sup>Originally posted by **Jerantony** March 23, 2023</sup>
It would be great if one could use the data buckets in response rules, so that one can configure for example route parameters which trigger a certain response on the fly. In my case, in a test, I want to receive a 400 response for a route parameter which is randomly generated during the test.

Maybe this could be done either by allowing the data helper in the value of response rules or by including all configured data buckets in comparison operator list of the rule and then using the value as the object path.</div>

**Comment by Jerantony** [comment]
Opened a PR: https://github.com/mockoon/mockoon/pull/1095 🙂
