### ISSUE TITLE
Update UI to reflect server binding on multiple network interfaces

### ISSUE THREAD

**Issue by bracco23** [mockoon/mockoon#99]
**Is your feature request related to a problem? Please describe.**
I was trying to use Mockoon to mock an API to develop a mobile application, but my requests were being rejected because Mockoon is binding on localhost but I'm trying to reach it from outside my PC.

**Describe the solution you'd like**
It would be nice to be able to change the IP on which Mockoon binds so that it is possible to reach it from the local network.

**Describe alternatives you've considered**
I tried to see if it was possible to redirect al request from local network to the loopback interface, but I found nothing.

**Comment by Eido95** [comment]
It seems that `localhost` is hard-coded as environment host.

**Comment by bracco23** [comment]
@Eido95 Yes, I saw that too, that's why I opened this issue. In the end I was actually able to make it work using `socat`, but it would still be better to allow for discovery and selection of network interface from inside the application itself.

**Comment by Eido95** [comment]
@255kb what your thoughts about this one? looks straightforward.

**Comment by 255kb** [comment]
@Eido95 actually, Mockoon is using Express and `listen` on the port you provide without passing any IP or even 'localhost' ([see here](https://github.com/mockoon/mockoon/blob/master/src/app/services/server.service.ts#L57)). So, by default, mocked servers should be available on all network adapters IPs.
I just tested here with Mockoon 1.4.0 (Windows 10) and the mocked server is available on all IPs, and some of them are also available on the local network for my colleagues.

Which OS are you using? 

It's also true that the UI is confusing and only show "localhost". This could be improved.

**Comment by bracco23** [comment]
I am too on Windows 10 and at the time it was not working. I don't remember the version I am using, I will check later when I am able to. Showing `0.0.0.0` or nothing at all might be a better choice, in my opinion.

**Comment by Eido95** [comment]
I tried it now and it works fine.
I successfully accessed Mockoon server outside localhost environment (specifically I accessed it from LAN).

Additionally, I verified on what host does Mockoon server listening on:
```
eido@:~$ lsof -i :3000
COMMAND PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
mockoon 723 eido   47u  IPv6 420211      0t0  TCP *:3000 (LISTEN)
```

Technically it works, I guess visually specifying the host as "localhost" might be misleading in this context?

**Comment by 255kb** [comment]
@Eido95 perfect! 
I will keep this issue open and modify it so we update the interface in the next release to make it less confusing. 

Thank you for your investigation 👍

**Comment by bracco23** [comment]
Well, I just tried again with the same setup, with version 1.3.0, and it works fine. Probably something else was going wrong previously.

**Comment by 255kb** [comment]
@bracco23 I am glad to hear this!

**Comment by 255kb** [comment]
What do you think would be best instead of current UI ("localhost" in front of port input)
- Nothing 
- localhost + an explanation tooltip 
- x.x.x.x + an explanation tooltip
- an "i" icon with an explanation tooltip in front of localhost 
- an "i" icon with an explanation tooltip in front of x.x.x.x
- something else?

**Comment by bracco23** [comment]
If I can have a say, I would go for `0.0.0.0` + i icon with explanation tooltip

- For users with a minimum of networking knowledge, it would be self-explanatory, since it is common to have this address related to this use ( so common, even [wikipedia mentions it](https://en.wikipedia.org/wiki/0.0.0.0) )

- For users without a networking knowledge, well, the explanation tooltip should be enough to clarify the meaning.

**Comment by 255kb** [comment]
@bracco23 ok, but when I test a mocked server with 0.0.0.0:port it does not work. Apparently this is one IP to which the server is not bound. 
Or am I missing something? (I am probably in the second group :))

**Comment by bracco23** [comment]
Well, you are missing that 0.0.0.0 is not a valid destination IP :).

Several sources online point to why this happens and the reasons behind it ( [this superuser question](https://superuser.com/questions/846721/chrome-wont-access-http-0-0-0-04200) is quite good at explaining it ) and if your concern is about people actually trying to use it, well, I can't blame you.

My proposal does indeed build on the assumption that a majority of Mockoon users know about the `0.0.0.0` address meaning or have sufficient knowledge of networking to smell something fishy about the application saying "I am listening on 0.0.0.0", which would then lead to a google search or look at the explanation tooltip, which would then provide enough information to understand "just use any address that can reach this computer." This would allow using something which is closer to the actual behaviour without causing too much discomfort to the user.

On the other hand, it is not really an issue if `0.0.0.0` or `localhost` is used since I assume the relevant information would be included in the explanation tooltip and whoever would actually need to know if they can use an address different than the one showed would look there first.

Regardless of the actual string used, I think it would be better to use an `i` icon, to make it clear that there is more information available if needed, and I would avoid a plain `x.x.x.x` which would lead to a moment of confusion almost everybody, in my opinion.

**Comment by 255kb** [comment]
Thanks for the explanation! There is always something new to learn :)

Your proposal is very clear indeed. I will replace localhost by 0.0.0.0 and add a tooltip stating that the mocked server is available on any IP.

**Comment by Eido95** [comment]
Glad about your conclusion,
`0.0.0.0` with a tooltip presumably explain it visually better than localhost.

Much thanks guys.
