### ISSUE TITLE
cli-ux 6.0.9 deprecated

### ISSUE THREAD

**Issue by mfrancisbeehive** [mockoon/mockoon#997]
**Describe the bug**

Doesn't necessarily stop the CLI from working, but upon install I get this message 

```
npm WARN deprecated cli-ux@6.0.9: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
```

**To Reproduce**

Install npm using command provided in documentation

**Mockoon version:**

2.4.0

**OS / OS version:**

Ubuntu 20.04.5

**Comment by 255kb** [comment]
This has been released in [v3.0.0](https://mockoon.com/releases/3.0.0/).
